// ==================== medicines12.js — دوولسمه برخه ====================
export const medicines12 = [
  {
    id: '551',
    name: 'Thiotepa',
    generic: 'Thiotepa',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د ځینو سرطانونو او د stem cell transplant دمخه.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د انتاناتو خطر، د پوستکي خارښت.',
    warning: 'د وینې د حجرو منظم څارنه اړینه ده.',
  },
  {
    id: '552',
    name: 'Procarbazine',
    generic: 'Procarbazine',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د Hodgkin lymphoma او ځینو نورو لپاره.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، د وینې د حجرو کمښت، د مزاج بدلونونه.',
    warning: 'د MAOIs او tyramine لرونکو خوړو سره تعامل لري.',
  },
  {
    id: '553',
    name: 'Estramustine',
    generic: 'Estramustine',
    category: 'Antineoplastic',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Capsule'],
    side_effects: 'د سینې پړسوب، د وینې د لخته خطر، زړه بدوالی.',
    warning: 'د وینې د لخته څارنه.',
  },
  {
    id: '554',
    name: 'Mitotane (High Dose)',
    generic: 'Mitotane',
    category: 'Antineoplastic (Adrenal Cytotoxic)',
    uses: 'د Adrenal cortical carcinoma لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، اسهال، د CNS اغیزې.',
    warning: 'د adrenal function څارنه مهمه ده.',
  },
  {
    id: '555',
    name: 'Arsenic Trioxide',
    generic: 'Arsenic Trioxide',
    category: 'Antineoplastic',
    uses: 'د Acute Promyelocytic Leukemia (APL) لپاره.',
    forms: ['Injection'],
    side_effects: 'د QT اوږدوالی، د وینې د حجرو کمښت، د ځیګر زهرجنیت.',
    warning: 'د QT اوږدوالی څارنه مهمه ده.',
  },
  {
    id: '556',
    name: 'Tretinoin',
    generic: 'Tretinoin (ATRA)',
    category: 'Antineoplastic (Retinoid)',
    uses: 'د Acute Promyelocytic Leukemia (APL) لپاره.',
    forms: ['Capsule'],
    side_effects: 'د differentiation syndrome، د پوستکي وچوالی، سرخوږی.',
    warning: 'د differentiation syndrome څارنه مهمه ده.',
  },
  {
    id: '557',
    name: 'Bexarotene',
    generic: 'Bexarotene',
    category: 'Antineoplastic (Retinoid)',
    uses: 'د Cutaneous T-cell Lymphoma لپاره.',
    forms: ['Capsule', 'Topical gel'],
    side_effects: 'د وینې د شکرې لوړوالی، د کولیسټرول لوړوالی، د پوستکي وچوالی.',
    warning: 'د وینې د شکرې او کولیسټرول څارنه.',
  },
  {
    id: '558',
    name: 'Vorinostat',
    generic: 'Vorinostat',
    category: 'Antineoplastic (HDAC inhibitor)',
    uses: 'د Cutaneous T-cell Lymphoma لپاره.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، اسهال، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو او د زړه څارنه.',
  },
  {
    id: '559',
    name: 'Romidepsin',
    generic: 'Romidepsin',
    category: 'Antineoplastic (HDAC inhibitor)',
    uses: 'د Cutaneous T-cell Lymphoma او Peripheral T-cell Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'زړه بدوالی، ستړیا، د زړه د ریتم بدلونونه.',
    warning: 'د زړه د ریتم څارنه.',
  },
  {
    id: '560',
    name: 'Panobinostat',
    generic: 'Panobinostat',
    category: 'Antineoplastic (HDAC inhibitor)',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Capsule'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، د زړه د ریتم بدلونونه.',
    warning: 'د زړه د ریتم څارنه.',
  },
  {
    id: '561',
    name: 'Azacitidine',
    generic: 'Azacitidine',
    category: 'Antineoplastic (Hypomethylating Agent)',
    uses: 'د Myelodysplastic Syndrome او AML لپاره.',
    forms: ['Injection', 'Tablet'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د انجیکشن ځای غبرګونونه.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '562',
    name: 'Decitabine',
    generic: 'Decitabine',
    category: 'Antineoplastic (Hypomethylating Agent)',
    uses: 'د Myelodysplastic Syndrome او AML لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، ستړیا، د وینې بهیدنه.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '563',
    name: 'Asparaginase (Erwinia)',
    generic: 'Asparaginase (Erwinia chrysanthemi)',
    category: 'Antineoplastic Enzyme',
    uses: 'د ALL لپاره، د E. coli-derived asparaginase په وړاندې د hypersensitivity لرونکو ناروغانو لپاره.',
    forms: ['Injection'],
    side_effects: 'د hypersensitivity غبرګونونه، pancreatitis، thrombosis.',
    warning: 'د pancreatitis او thrombosis څارنه.',
  },
  {
    id: '564',
    name: 'Erlotinib (High Dose)',
    generic: 'Erlotinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د NSCLC لپاره.',
    forms: ['Tablet'],
    side_effects: 'د پوستکي خارښت، اسهال، ستړیا.',
    warning: 'د ILD خطر او د ځیګر زهرجنیت.',
  },
  {
    id: '565',
    name: 'Afatinib',
    generic: 'Afatinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د خولې زخمونه.',
    warning: 'د اسهال او د پوستکي څارنه.',
  },
  {
    id: '566',
    name: 'Dacomitinib',
    generic: 'Dacomitinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د خولې زخمونه.',
    warning: 'د اسهال او د پوستکي څارنه.',
  },
  {
    id: '567',
    name: 'Neratinib',
    generic: 'Neratinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د اسهال څارنه مهمه ده.',
  },
  {
    id: '568',
    name: 'Lapatinib',
    generic: 'Lapatinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د زړه د فعالیت بدلون.',
    warning: 'د زړه د فعالیت څارنه.',
  },
  {
    id: '569',
    name: 'Tucatinib',
    generic: 'Tucatinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د لاسونو او پښو سندروم، د ځیګر انزایم لوړوالی.',
    warning: 'د اسهال او د ځیګر څارنه.',
  },
  {
    id: '570',
    name: 'Palbociclib',
    generic: 'Palbociclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د وینې د حجرو کمښت، ستړیا، زړه بدوالی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '571',
    name: 'Ribociclib',
    generic: 'Ribociclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د حجرو کمښت، د QT اوږدوالی، ستړیا.',
    warning: 'د QT اوږدوالی او د وینې د حجرو څارنه.',
  },
  {
    id: '572',
    name: 'Abemaciclib',
    generic: 'Abemaciclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د اسهال او د وینې د حجرو څارنه.',
  },
  {
    id: '573',
    name: 'Olaparib',
    generic: 'Olaparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer، سینې د سرطان، prostate cancer او pancreatic cancer لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'زړه بدوالی، ستړیا، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '574',
    name: 'Rucaparib',
    generic: 'Rucaparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer او prostate cancer لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، ستړیا، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '575',
    name: 'Niraparib',
    generic: 'Niraparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer، fallopian tube cancer او peritoneal cancer لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، ستړیا.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '576',
    name: 'Talazoparib',
    generic: 'Talazoparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې د حجرو کمښت، ستړیا، سرخوږی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '577',
    name: 'Enasidenib',
    generic: 'Enasidenib',
    category: 'Antineoplastic (IDH2 inhibitor)',
    uses: 'د AML لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، اسهال، د differentiation syndrome.',
    warning: 'د differentiation syndrome څارنه.',
  },
  {
    id: '578',
    name: 'Ivosidenib',
    generic: 'Ivosidenib',
    category: 'Antineoplastic (IDH1 inhibitor)',
    uses: 'د AML او cholangiocarcinoma لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، اسهال، د differentiation syndrome.',
    warning: 'د differentiation syndrome څارنه.',
  },
  {
    id: '579',
    name: 'Gilteritinib',
    generic: 'Gilteritinib',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-mutated AML لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د حجرو کمښت، اسهال، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی او د وینې د حجرو څارنه.',
  },
  {
    id: '580',
    name: 'Midostaurin',
    generic: 'Midostaurin',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-mutated AML او Systemic Mastocytosis لپاره.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، د وینې د حجرو کمښت، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی څارنه.',
  },
  {
    id: '581',
    name: 'Quizartinib',
    generic: 'Quizartinib',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-ITD positive AML لپاره.',
    forms: ['Tablet'],
    side_effects: 'د QT اوږدوالی، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د QT اوږدوالی څارنه مهمه ده.',
  },
  {
    id: '582',
    name: 'Pexidartinib',
    generic: 'Pexidartinib',
    category: 'Antineoplastic (CSF1R inhibitor)',
    uses: 'د Tenosynovial Giant Cell Tumor لپاره.',
    forms: ['Capsule'],
    side_effects: 'د ځیګر زهرجنیت، ستړیا، د پوستکي خارښت.',
    warning: 'د ځیګر زهرجنیت څارنه.',
  },
  {
    id: '583',
    name: 'Selpercatinib',
    generic: 'Selpercatinib',
    category: 'Antineoplastic (RET inhibitor)',
    uses: 'د RET-fusion NSCLC او thyroid cancer لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې فشار لوړوالی، د QT اوږدوالی، ستړیا.',
    warning: 'د فشار او QT څارنه.',
  },
  {
    id: '584',
    name: 'Pralsetinib',
    generic: 'Pralsetinib',
    category: 'Antineoplastic (RET inhibitor)',
    uses: 'د RET-fusion NSCLC او thyroid cancer لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې فشار لوړوالی، ستړیا، د ځیګر انزایم لوړوالی.',
    warning: 'د فشار او د ځیګر څارنه.',
  },
  {
    id: '585',
    name: 'Tepotinib',
    generic: 'Tepotinib',
    category: 'Antineoplastic (MET inhibitor)',
    uses: 'د MET-mutated NSCLC لپاره.',
    forms: ['Tablet'],
    side_effects: 'د پښو پړسوب، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر څارنه.',
  },
  {
    id: '586',
    name: 'Capmatinib',
    generic: 'Capmatinib',
    category: 'Antineoplastic (MET inhibitor)',
    uses: 'د MET-mutated NSCLC لپاره.',
    forms: ['Tablet'],
    side_effects: 'د پښو پړسوب، زړه بدوالی، ستړیا.',
    warning: 'د ILD خطر او د ځیګر څارنه.',
  },
  {
    id: '587',
    name: 'Sotorasib',
    generic: 'Sotorasib',
    category: 'Antineoplastic (KRAS inhibitor)',
    uses: 'د KRAS G12C-mutated NSCLC لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر زهرجنیت څارنه.',
  },
  {
    id: '588',
    name: 'Adagrasib',
    generic: 'Adagrasib',
    category: 'Antineoplastic (KRAS inhibitor)',
    uses: 'د KRAS G12C-mutated NSCLC لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، اسهال، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی او د ځیګر څارنه.',
  },
  {
    id: '589',
    name: 'Entrectinib',
    generic: 'Entrectinib',
    category: 'Antineoplastic (NTRK/ROS1 inhibitor)',
    uses: 'د NTRK-fusion tumors او ROS1-positive NSCLC لپاره.',
    forms: ['Capsule'],
    side_effects: 'ستړیا، د وزن زیاتوالی، د مزاج بدلونونه.',
    warning: 'د CNS اغیزې او د زړه څارنه.',
  },
  {
    id: '590',
    name: 'Larotrectinib',
    generic: 'Larotrectinib',
    category: 'Antineoplastic (NTRK inhibitor)',
    uses: 'د NTRK-fusion tumors لپاره.',
    forms: ['Capsule', 'Oral solution'],
    side_effects: 'ستړیا، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر او د CNS څارنه.',
  },
  {
    id: '591',
    name: 'Futibatinib',
    generic: 'Futibatinib',
    category: 'Antineoplastic (FGFR inhibitor)',
    uses: 'د cholangiocarcinoma لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د فاسفورس لوړوالی، د سترګو ستونزې، ستړیا.',
    warning: 'د فاسفورس او د سترګو څارنه.',
  },
  {
    id: '592',
    name: 'Pemigatinib',
    generic: 'Pemigatinib',
    category: 'Antineoplastic (FGFR inhibitor)',
    uses: 'د cholangiocarcinoma لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د فاسفورس لوړوالی، د سترګو ستونزې، اسهال.',
    warning: 'د فاسفورس او د سترګو څارنه.',
  },
  {
    id: '593',
    name: 'Erdafitinib',
    generic: 'Erdafitinib',
    category: 'Antineoplastic (FGFR inhibitor)',
    uses: 'د bladder cancer لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د فاسفورس لوړوالی، د سترګو ستونزې، ستړیا.',
    warning: 'د فاسفورس او د سترګو څارنه.',
  },
  {
    id: '594',
    name: 'Infigratinib',
    generic: 'Infigratinib',
    category: 'Antineoplastic (FGFR inhibitor)',
    uses: 'د cholangiocarcinoma لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې د فاسفورس لوړوالی، د سترګو ستونزې، ستړیا.',
    warning: 'د فاسفورس او د سترګو څارنه.',
  },
  {
    id: '595',
    name: 'Trastuzumab Emtansine',
    generic: 'Trastuzumab Emtansine (T-DM1)',
    category: 'Antineoplastic (Antibody-Drug Conjugate)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د ځیګر انزایم لوړوالی، ستړیا.',
    warning: 'د ځیګر او د وینې د حجرو څارنه.',
  },
  {
    id: '596',
    name: 'Trastuzumab Deruxtecan',
    generic: 'Trastuzumab Deruxtecan (T-DXd)',
    category: 'Antineoplastic (Antibody-Drug Conjugate)',
    uses: 'د HER2-positive سینې د سرطان او gastric cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د ILD خطر، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د ILD خطر څارنه مهمه ده.',
  },
  {
    id: '597',
    name: 'Brentuximab Vedotin',
    generic: 'Brentuximab Vedotin',
    category: 'Antineoplastic (Antibody-Drug Conjugate)',
    uses: 'د Hodgkin lymphoma او Anaplastic Large Cell Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د اعصابو درد، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د اعصابو څارنه.',
  },
  {
    id: '598',
    name: 'Gemtuzumab Ozogamicin',
    generic: 'Gemtuzumab Ozogamicin',
    category: 'Antineoplastic (Antibody-Drug Conjugate)',
    uses: 'د AML لپاره.',
    forms: ['Injection'],
    side_effects: 'د ځیګر زهرجنیت، د وینې د حجرو کمښت، د وینې بهیدنه.',
    warning: 'د ځیګر زهرجنیت څارنه.',
  },
  {
    id: '599',
    name: 'Inotuzumab Ozogamicin',
    generic: 'Inotuzumab Ozogamicin',
    category: 'Antineoplastic (Antibody-Drug Conjugate)',
    uses: 'د ALL لپاره.',
    forms: ['Injection'],
    side_effects: 'د ځیګر زهرجنیت، د وینې د حجرو کمښت، د وینې بهیدنه.',
    warning: 'د ځیګر زهرجنیت څارنه.',
  },
  {
    id: '600',
    name: 'Sacituzumab Govitecan',
    generic: 'Sacituzumab Govitecan',
    category: 'Antineoplastic (Antibody-Drug Conjugate)',
    uses: 'د triple-negative سینې د سرطان او bladder cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د اسهال او د وینې د حجرو څارنه.',
  },
];
