// ==================== medicines19.js — نولسمه برخه ====================
export const medicines19 = [
  {
    id: '901',
    name: 'Zynlonta (Loncastuximab Tesirine)',
    generic: 'Loncastuximab Tesirine',
    category: 'Antibody-Drug Conjugate',
    uses: 'د Large B-cell Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د ځیګر انزایم لوړوالی، ستړیا.',
    warning: 'د ځیګر او د وینې د حجرو څارنه.',
  },
  {
    id: '902',
    name: 'Akalux (Cetuximab Sarotalocan)',
    generic: 'Cetuximab Sarotalocan',
    category: 'Photodynamic Therapy',
    uses: 'د Head and Neck Cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د پوستکي خارښت، د سوزش خطر.',
    warning: 'د لیزرو څارنه مهمه ده.',
  },
  {
    id: '903',
    name: 'Ontak (Denileukin Diftitox)',
    generic: 'Denileukin Diftitox',
    category: 'Biologic (IL-2 fusion toxin)',
    uses: 'د Cutaneous T-cell Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د وینې د حجرو کمښت.',
    warning: 'د انفوزیون غبرګونونه څارنه.',
  },
  {
    id: '904',
    name: 'Yervoy (Ipilimumab)',
    generic: 'Ipilimumab',
    category: 'Monoclonal Antibody (CTLA-4 inhibitor)',
    uses: 'د Melanoma او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '905',
    name: 'Opdivo (Nivolumab)',
    generic: 'Nivolumab',
    category: 'Monoclonal Antibody (PD-1 inhibitor)',
    uses: 'د Melanoma، NSCLC او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '906',
    name: 'Keytruda (Pembrolizumab)',
    generic: 'Pembrolizumab',
    category: 'Monoclonal Antibody (PD-1 inhibitor)',
    uses: 'د Melanoma، NSCLC او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '907',
    name: 'Tecentriq (Atezolizumab)',
    generic: 'Atezolizumab',
    category: 'Monoclonal Antibody (PD-L1 inhibitor)',
    uses: 'د NSCLC، bladder cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '908',
    name: 'Imfinzi (Durvalumab)',
    generic: 'Durvalumab',
    category: 'Monoclonal Antibody (PD-L1 inhibitor)',
    uses: 'د NSCLC او bladder cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '909',
    name: 'Bavencio (Avelumab)',
    generic: 'Avelumab',
    category: 'Monoclonal Antibody (PD-L1 inhibitor)',
    uses: 'د Merkel Cell Carcinoma او bladder cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '910',
    name: 'Libtayo (Cemiplimab)',
    generic: 'Cemiplimab',
    category: 'Monoclonal Antibody (PD-1 inhibitor)',
    uses: 'د Cutaneous Squamous Cell Carcinoma او NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '911',
    name: 'Jemperli (Dostarlimab)',
    generic: 'Dostarlimab',
    category: 'Monoclonal Antibody (PD-1 inhibitor)',
    uses: 'د Endometrial cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '912',
    name: 'Imjudo (Tremelimumab)',
    generic: 'Tremelimumab',
    category: 'Monoclonal Antibody (CTLA-4 inhibitor)',
    uses: 'د Hepatocellular Carcinoma او NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا، د پوستکي خارښت.',
    warning: 'د immune-mediated غبرګونونه څارنه مهمه ده.',
  },
  {
    id: '913',
    name: 'Rybrevant (Amivantamab)',
    generic: 'Amivantamab',
    category: 'Monoclonal Antibody (anti-EGFR/MET)',
    uses: 'د EGFR exon 20 insertion-positive NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د پوستکي خارښت، د وینې د لخته خطر.',
    warning: 'د انفوزیون غبرګونونه څارنه.',
  },
  {
    id: '914',
    name: 'Lazcluze (Lazertinib)',
    generic: 'Lazertinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، د وینې د لخته خطر، ستړیا.',
    warning: 'د وینې د لخته څارنه.',
  },
  {
    id: '915',
    name: 'Exkivity (Mobocertinib)',
    generic: 'Mobocertinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR exon 20 insertion-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'اسهال، د پوستکي خارښت، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی څارنه.',
  },
  {
    id: '916',
    name: 'Tepmetko (Tepotinib)',
    generic: 'Tepotinib',
    category: 'Antineoplastic (MET inhibitor)',
    uses: 'د MET-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر څارنه.',
  },
  {
    id: '917',
    name: 'Tabrecta (Capmatinib)',
    generic: 'Capmatinib',
    category: 'Antineoplastic (MET inhibitor)',
    uses: 'د MET-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، زړه بدوالی، ستړیا.',
    warning: 'د ILD او د ځیګر څارنه.',
  },
  {
    id: '918',
    name: 'Retevmo (Selpercatinib)',
    generic: 'Selpercatinib',
    category: 'Antineoplastic (RET inhibitor)',
    uses: 'د RET-fusion NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې فشار لوړوالی، د QT اوږدوالی، ستړیا.',
    warning: 'د فشار او QT څارنه.',
  },
  {
    id: '919',
    name: 'Gavreto (Pralsetinib)',
    generic: 'Pralsetinib',
    category: 'Antineoplastic (RET inhibitor)',
    uses: 'د RET-fusion NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې فشار لوړوالی، ستړیا، د ځیګر انزایم لوړوالی.',
    warning: 'د فشار او د ځیګر څارنه.',
  },
  {
    id: '920',
    name: 'Rozlytrek (Entrectinib)',
    generic: 'Entrectinib',
    category: 'Antineoplastic (NTRK/ROS1 inhibitor)',
    uses: 'د NTRK-fusion tumors او ROS1-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'ستړیا، د وزن زیاتوالی، د مزاج بدلونونه.',
    warning: 'د CNS او د زړه څارنه.',
  },
  {
    id: '921',
    name: 'Vitrakvi (Larotrectinib)',
    generic: 'Larotrectinib',
    category: 'Antineoplastic (NTRK inhibitor)',
    uses: 'د NTRK-fusion tumors لپاره.',
    forms: ['Oral capsule', 'Oral solution'],
    side_effects: 'ستړیا، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر او د CNS څارنه.',
  },
  {
    id: '922',
    name: 'Augtyro (Repotrectinib)',
    generic: 'Repotrectinib',
    category: 'Antineoplastic (ROS1/NTRK inhibitor)',
    uses: 'د ROS1-positive NSCLC او NTRK-fusion tumors لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د CNS اغیزې، د عضلاتو درد، ستړیا.',
    warning: 'د CNS اغیزې څارنه.',
  },
  {
    id: '923',
    name: 'Lorbrena (Lorlatinib)',
    generic: 'Lorlatinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د کولیسټرول لوړوالی، د پښو پړسوب، د مزاج بدلونونه.',
    warning: 'د CNS او د کولیسټرول څارنه.',
  },
  {
    id: '924',
    name: 'Alunbrig (Brigatinib)',
    generic: 'Brigatinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د وینې لوړ فشار.',
    warning: 'د ILD او د فشار څارنه.',
  },
  {
    id: '925',
    name: 'Alecensa (Alectinib)',
    generic: 'Alectinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'ستړیا، د پښو پړسوب، د پوټکي خارښت.',
    warning: 'د ځیګر او د ILD څارنه.',
  },
  {
    id: '926',
    name: 'Zykadia (Ceritinib)',
    generic: 'Ceritinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral capsule', 'Oral tablet'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر او د زړه څارنه.',
  },
  {
    id: '927',
    name: 'Xalkori (Crizotinib)',
    generic: 'Crizotinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د لید ستونزې، زړه بدوالی، د پښو پړسوب.',
    warning: 'د لید او د زړه څارنه.',
  },
  {
    id: '928',
    name: 'Zelboraf (Vemurafenib)',
    generic: 'Vemurafenib',
    category: 'Antineoplastic (BRAF inhibitor)',
    uses: 'د Melanoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، د بندونو درد، ستړیا.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '929',
    name: 'Tafinlar (Dabrafenib)',
    generic: 'Dabrafenib',
    category: 'Antineoplastic (BRAF inhibitor)',
    uses: 'د Melanoma، NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule', 'Oral tablet'],
    side_effects: 'د پوستکي خارښت، ستړیا، تبه.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '930',
    name: 'Braftovi (Encorafenib)',
    generic: 'Encorafenib',
    category: 'Antineoplastic (BRAF inhibitor)',
    uses: 'د Melanoma او Colorectal Cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د پوستکي خارښت، ستړیا، د بندونو درد.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '931',
    name: 'Mekinist (Trametinib)',
    generic: 'Trametinib',
    category: 'Antineoplastic (MEK inhibitor)',
    uses: 'د Melanoma، NSCLC او thyroid cancer لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، ستړیا، د زړه د فعالیت بدلون.',
    warning: 'د زړه او د سترګو څارنه.',
  },
  {
    id: '932',
    name: 'Cotellic (Cobimetinib)',
    generic: 'Cobimetinib',
    category: 'Antineoplastic (MEK inhibitor)',
    uses: 'د Melanoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د زړه د فعالیت بدلون.',
    warning: 'د زړه او د سترګو څارنه.',
  },
  {
    id: '933',
    name: 'Mektovi (Binimetinib)',
    generic: 'Binimetinib',
    category: 'Antineoplastic (MEK inhibitor)',
    uses: 'د Melanoma او NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'ستړیا، د پوستکي خارښت، د زړه د فعالیت بدلون.',
    warning: 'د زړه او د سترګو څارنه.',
  },
  {
    id: '934',
    name: 'Koselugo (Selumetinib)',
    generic: 'Selumetinib',
    category: 'Antineoplastic (MEK inhibitor)',
    uses: 'د Neurofibromatosis Type 1 (NF1) لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د پوستکي خارښت، اسهال، د زړه د فعالیت بدلون.',
    warning: 'د زړه او د سترګو څارنه.',
  },
  {
    id: '935',
    name: 'Turalio (Pexidartinib)',
    generic: 'Pexidartinib',
    category: 'Antineoplastic (CSF1R inhibitor)',
    uses: 'د Tenosynovial Giant Cell Tumor لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د ځیګر زهرجنیت، ستړیا، د پوستکي خارښت.',
    warning: 'د ځیګر زهرجنیت څارنه.',
  },
  {
    id: '936',
    name: 'Stivarga (Regorafenib)',
    generic: 'Regorafenib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Colorectal Cancer، GIST او Hepatocellular Carcinoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'ستړیا، اسهال، د وینې فشار لوړوالی، د لاسونو او پښو سندروم.',
    warning: 'د ځیګر زهرجنیت او د فشار څارنه.',
  },
  {
    id: '937',
    name: 'Lenvima (Lenvatinib)',
    generic: 'Lenvatinib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Thyroid Cancer، Hepatocellular Carcinoma او Renal Cell Carcinoma لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې فشار لوړوالی، اسهال، ستړیا.',
    warning: 'د فشار او د زړه څارنه.',
  },
  {
    id: '938',
    name: 'Cabometyx (Cabozantinib)',
    generic: 'Cabozantinib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Renal Cell Carcinoma او Hepatocellular Carcinoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د وینې فشار لوړوالی، ستړیا.',
    warning: 'د فشار او د وینې بهیدو څارنه.',
  },
  {
    id: '939',
    name: 'Sutent (Sunitinib)',
    generic: 'Sunitinib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Renal Cell Carcinoma او GIST لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'ستړیا، اسهال، د وینې فشار لوړوالی.',
    warning: 'د فشار او د زړه څارنه.',
  },
  {
    id: '940',
    name: 'Nexavar (Sorafenib)',
    generic: 'Sorafenib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Hepatocellular Carcinoma، Renal Cell Carcinoma او Thyroid Cancer لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، اسهال، د وینې فشار لوړوالی.',
    warning: 'د فشار او د وینې بهیدو څارنه.',
  },
  {
    id: '941',
    name: 'Votrient (Pazopanib)',
    generic: 'Pazopanib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Renal Cell Carcinoma او Soft Tissue Sarcoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د وینې فشار لوړوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر او د فشار څارنه.',
  },
  {
    id: '942',
    name: 'Inlyta (Axitinib)',
    generic: 'Axitinib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Renal Cell Carcinoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د وینې فشار لوړوالی، ستړیا.',
    warning: 'د فشار او د وینې بهیدو څارنه.',
  },
  {
    id: '943',
    name: 'Caprelsa (Vandetanib)',
    generic: 'Vandetanib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Medullary Thyroid Cancer لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، اسهال، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی او د فشار څارنه.',
  },
  {
    id: '944',
    name: 'Cometriq (Cabozantinib)',
    generic: 'Cabozantinib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Medullary Thyroid Cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'اسهال، د وینې فشار لوړوالی، ستړیا.',
    warning: 'د فشار او د وینې بهیدو څارنه.',
  },
  {
    id: '945',
    name: 'Lenvatinib (Thyroid)',
    generic: 'Lenvatinib',
    category: 'Antineoplastic (Kinase inhibitor)',
    uses: 'د Thyroid Cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې فشار لوړوالی، اسهال، ستړیا.',
    warning: 'د فشار او د زړه څارنه.',
  },
  {
    id: '946',
    name: 'Tafinlar + Mekinist',
    generic: 'Dabrafenib + Trametinib',
    category: 'Combination Therapy',
    uses: 'د Melanoma، NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule + Oral tablet'],
    side_effects: 'د پوستکي خارښت، ستړیا، د زړه د فعالیت بدلون.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '947',
    name: 'Braftovi + Mektovi',
    generic: 'Encorafenib + Binimetinib',
    category: 'Combination Therapy',
    uses: 'د Melanoma او Colorectal Cancer لپاره.',
    forms: ['Oral capsule + Oral tablet'],
    side_effects: 'د پوستکي خارښت، ستړیا، د زړه د فعالیت بدلون.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '948',
    name: 'Zelboraf + Cotellic',
    generic: 'Vemurafenib + Cobimetinib',
    category: 'Combination Therapy',
    uses: 'د Melanoma لپاره.',
    forms: ['Oral tablet + Oral tablet'],
    side_effects: 'د پوستکي خارښت، اسهال، د زړه د فعالیت بدلون.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '949',
    name: 'Keytruda + Axitinib',
    generic: 'Pembrolizumab + Axitinib',
    category: 'Combination Therapy',
    uses: 'د Renal Cell Carcinoma لپاره.',
    forms: ['Injection + Oral tablet'],
    side_effects: 'د immune-mediated غبرګونونه، د وینې فشار لوړوالی، ستړیا.',
    warning: 'د immune-mediated غبرګونونه او د فشار څارنه.',
  },
  {
    id: '950',
    name: 'Opdivo + Cabometyx',
    generic: 'Nivolumab + Cabozantinib',
    category: 'Combination Therapy',
    uses: 'د Renal Cell Carcinoma لپاره.',
    forms: ['Injection + Oral tablet'],
    side_effects: 'د immune-mediated غبرګونونه، د وینې فشار لوړوالی، ستړیا.',
    warning: 'د immune-mediated غبرګونونه او د فشار څارنه.',
  },
];
