// ==================== medicines15.js — پنځلسمه برخه ====================
export const medicines15 = [
  {
    id: '701',
    name: 'Aloe Vera',
    generic: 'Aloe vera',
    category: 'Herbal Topical',
    uses: 'د سوځېدنې او د پوستکي د التهاب لپاره.',
    forms: ['Gel', 'Cream'],
    side_effects: 'د پوستکي خارښت، الرژي.',
    warning: 'د خولې له لارې د استعمال لپاره نه دی ټاکل شوی.',
  },
  {
    id: '702',
    name: 'Tea Tree Oil',
    generic: 'Melaleuca alternifolia',
    category: 'Herbal Topical Antimicrobial',
    uses: 'د پوستکي د ځینو انتاناتو او د اکې لپاره.',
    forms: ['Oil', 'Cream', 'Gel'],
    side_effects: 'د پوستکي خارښت، الرژي.',
    warning: 'د خولې له لارې د استعمال لپاره نه دی ټاکل شوی.',
  },
  {
    id: '703',
    name: 'Witch Hazel',
    generic: 'Hamamelis virginiana',
    category: 'Herbal Topical',
    uses: 'د پوستکي د التهاب او د کوچنیو زخمونو لپاره.',
    forms: ['Lotion', 'Solution'],
    side_effects: 'د پوستکي وچوالی، خارښت.',
    warning: 'د سترګو له تماس څخه ډډه وکړئ.',
  },
  {
    id: '704',
    name: 'Arnica',
    generic: 'Arnica montana',
    category: 'Herbal Topical',
    uses: 'د کبودۍ او د عضلاتو د درد لپاره.',
    forms: ['Gel', 'Cream', 'Ointment'],
    side_effects: 'د پوستکي خارښت، الرژي.',
    warning: 'د خولې له لارې د استعمال لپاره نه دی ټاکل شوی.',
  },
  {
    id: '705',
    name: 'Calendula',
    generic: 'Calendula officinalis',
    category: 'Herbal Topical',
    uses: 'د پوستکي د التهاب او د کوچنیو زخمونو لپاره.',
    forms: ['Cream', 'Ointment'],
    side_effects: 'د پوستکي خارښت، الرژي.',
    warning: 'د سترګو له تماس څخه ډډه وکړئ.',
  },
  {
    id: '706',
    name: 'Eucalyptus Oil',
    generic: 'Eucalyptus globulus',
    category: 'Herbal',
    uses: 'د زکام او د تنفسي لارو د خلاصون لپاره.',
    forms: ['Oil', 'Inhalation', 'Ointment'],
    side_effects: 'د پوستکي خارښت، د تنفس ستونزه په ماشومانو کې.',
    warning: 'په ماشومانو کې د تنفسي ستونزو خطر.',
  },
  {
    id: '707',
    name: 'Lavender Oil',
    generic: 'Lavandula angustifolia',
    category: 'Herbal',
    uses: 'د اضطراب او د خوب د ستونزو لپاره.',
    forms: ['Oil', 'Capsule', 'Tea'],
    side_effects: 'د پوستکي خارښت، خوبولي.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '708',
    name: 'Lemon Balm',
    generic: 'Melissa officinalis',
    category: 'Herbal',
    uses: 'د اضطراب او د خوب د ستونزو لپاره.',
    forms: ['Capsule', 'Tea', 'Cream'],
    side_effects: 'د معدې ناراحتي، سرګرداني.',
    warning: 'د thyroid درملو سره تعاملات لري.',
  },
  {
    id: '709',
    name: 'Milk Thistle',
    generic: 'Silybum marianum',
    category: 'Herbal Hepatoprotective',
    uses: 'د ځیګر د ساتنې لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، الرژي.',
    warning: 'د ځیګر د درملو سره تعاملات لري.',
  },
  {
    id: '710',
    name: 'Saw Palmetto',
    generic: 'Serenoa repens',
    category: 'Herbal',
    uses: 'د Benign Prostatic Hyperplasia لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، سرخوږی.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '711',
    name: 'Cranberry',
    generic: 'Vaccinium macrocarpon',
    category: 'Herbal',
    uses: 'د ادرار د لارې د انتاناتو د مخنیوي لپاره.',
    forms: ['Capsule', 'Juice', 'Tablet'],
    side_effects: 'د معدې ناراحتي، اسهال.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '712',
    name: 'Garlic',
    generic: 'Allium sativum',
    category: 'Herbal',
    uses: 'د وینې د فشار او کولیسټرول لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، د بدن بوی، د وینې بهیدنه.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '713',
    name: 'Ginger',
    generic: 'Zingiber officinale',
    category: 'Herbal',
    uses: 'د زړه بدوالي او د معدې د ناراحتي لپاره.',
    forms: ['Capsule', 'Tea', 'Powder'],
    side_effects: 'د معدې ناراحتي، سینه سوزش.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '714',
    name: 'Fenugreek',
    generic: 'Trigonella foenum-graecum',
    category: 'Herbal',
    uses: 'د وینې د شکرې او کولیسټرول لپاره.',
    forms: ['Capsule', 'Powder', 'Tea'],
    side_effects: 'د معدې ناراحتي، د وینې د شکرې ټیټوالی.',
    warning: 'د وینې د شکرې درملو سره تعاملات لري.',
  },
  {
    id: '715',
    name: 'Cinnamon',
    generic: 'Cinnamomum verum',
    category: 'Herbal',
    uses: 'د وینې د شکرې او کولیسټرول لپاره.',
    forms: ['Capsule', 'Powder'],
    side_effects: 'د ځیګر زهرجنیت په لوړ مقدار کې.',
    warning: 'د وینې د شکرې درملو سره تعاملات لري.',
  },
  {
    id: '716',
    name: 'Black Cohosh',
    generic: 'Actaea racemosa',
    category: 'Herbal',
    uses: 'د Menopause د نښو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، سرخوږی، د ځیګر ستونزې.',
    warning: 'د ځیګر زهرجنیت خطر.',
  },
  {
    id: '717',
    name: 'Red Clover',
    generic: 'Trifolium pratense',
    category: 'Herbal',
    uses: 'د Menopause د نښو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، سرخوږی.',
    warning: 'د هورموني درملو سره تعاملات لري.',
  },
  {
    id: '718',
    name: 'Dong Quai',
    generic: 'Angelica sinensis',
    category: 'Herbal',
    uses: 'د نسایي ستونزو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د وینې بهیدنه، د پوستکي حساسیت.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '719',
    name: 'Evening Primrose Oil',
    generic: 'Oenothera biennis',
    category: 'Herbal',
    uses: 'د پوستکي او د نسایي ستونزو لپاره.',
    forms: ['Capsule', 'Oil'],
    side_effects: 'د معدې ناراحتي، سرخوږی.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '720',
    name: 'Borage Oil',
    generic: 'Borago officinalis',
    category: 'Herbal',
    uses: 'د پوستکي او د التهاب لپاره.',
    forms: ['Capsule', 'Oil'],
    side_effects: 'د معدې ناراحتي، سرخوږی.',
    warning: 'د ځیګر زهرجنیت خطر.',
  },
  {
    id: '721',
    name: 'Flaxseed',
    generic: 'Linum usitatissimum',
    category: 'Herbal / Nutritional',
    uses: 'د قبضیت او د کولیسټرول لپاره.',
    forms: ['Capsule', 'Oil', 'Powder'],
    side_effects: 'د معدې ناراحتي، نفخ.',
    warning: 'د اوبو ډېر مصرف مهم دی.',
  },
  {
    id: '722',
    name: 'Psyllium Husk',
    generic: 'Plantago ovata',
    category: 'Herbal Laxative',
    uses: 'د قبضیت لپاره.',
    forms: ['Powder', 'Capsule'],
    side_effects: 'نفخ، د معدې ناراحتي، الرژي.',
    warning: 'د اوبو ډېر مصرف مهم دی.',
  },
  {
    id: '723',
    name: 'Senna (Herbal)',
    generic: 'Senna alexandrina',
    category: 'Herbal Laxative',
    uses: 'د قبضیت لپاره.',
    forms: ['Tablet', 'Tea', 'Syrup'],
    side_effects: 'د معدې cramp، اسهال.',
    warning: 'د اوږدې مودې استعمال مناسب نه دی.',
  },
  {
    id: '724',
    name: 'Cascara Sagrada',
    generic: 'Frangula purshiana',
    category: 'Herbal Laxative',
    uses: 'د قبضیت لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې cramp، اسهال.',
    warning: 'د اوږدې مودې استعمال مناسب نه دی.',
  },
  {
    id: '725',
    name: 'Dandelion',
    generic: 'Taraxacum officinale',
    category: 'Herbal Diuretic',
    uses: 'د مایعاتو د زیاتوالي لپاره.',
    forms: ['Capsule', 'Tea'],
    side_effects: 'د معدې ناراحتي، الرژي.',
    warning: 'د دیورتیک درملو سره تعاملات لري.',
  },
  {
    id: '726',
    name: 'Uva Ursi',
    generic: 'Arctostaphylos uva-ursi',
    category: 'Herbal Urinary',
    uses: 'د ادرار د لارې د انتاناتو لپاره.',
    forms: ['Capsule', 'Tea'],
    side_effects: 'د معدې ناراحتي، د ادرار رنګ بدلون.',
    warning: 'د اوږدې مودې استعمال مناسب نه دی.',
  },
  {
    id: '727',
    name: 'Goldenseal',
    generic: 'Hydrastis canadensis',
    category: 'Herbal Antimicrobial',
    uses: 'د معدې او د تنفسي انتاناتو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، د وینې فشار لوړوالی.',
    warning: 'د امیندوارۍ په وخت کې مناسب نه دی.',
  },
  {
    id: '728',
    name: 'Echinacea (Topical)',
    generic: 'Echinacea purpurea',
    category: 'Herbal Topical',
    uses: 'د پوستکي د کوچنیو زخمونو لپاره.',
    forms: ['Cream', 'Ointment'],
    side_effects: 'د پوستکي خارښت، الرژي.',
    warning: 'د سترګو له تماس څخه ډډه وکړئ.',
  },
  {
    id: '729',
    name: 'Comfrey',
    generic: 'Symphytum officinale',
    category: 'Herbal Topical',
    uses: 'د پوستکي د التهاب او د کوچنیو زخمونو لپاره.',
    forms: ['Cream', 'Ointment'],
    side_effects: 'د پوستکي خارښت، الرژي.',
    warning: 'د خولې له لارې د استعمال لپاره نه دی ټاکل شوی.',
  },
  {
    id: '730',
    name: 'Chondroitin',
    generic: 'Chondroitin sulfate',
    category: 'Nutritional Supplement',
    uses: 'د Osteoarthritis لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، سرخوږی.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '731',
    name: 'Glucosamine',
    generic: 'Glucosamine sulfate',
    category: 'Nutritional Supplement',
    uses: 'د Osteoarthritis لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، سرخوږی، الرژي.',
    warning: 'د شکرې د ناروغانو لپاره د وینې د شکرې څارنه مهمه ده.',
  },
  {
    id: '732',
    name: 'MSM',
    generic: 'Methylsulfonylmethane',
    category: 'Nutritional Supplement',
    uses: 'د Osteoarthritis او د التهاب لپاره.',
    forms: ['Capsule', 'Tablet', 'Powder'],
    side_effects: 'د معدې ناراحتي، سرخوږی.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '733',
    name: 'Collagen',
    generic: 'Collagen peptides',
    category: 'Nutritional Supplement',
    uses: 'د پوستکي او د بندونو د روغتیا لپاره.',
    forms: ['Capsule', 'Powder'],
    side_effects: 'د معدې ناراحتي، الرژي.',
    warning: 'د حيواني سرچینو څخه د الرژي لرونکو کسانو کې احتیاط.',
  },
  {
    id: '734',
    name: 'Hyaluronic Acid',
    generic: 'Hyaluronic acid',
    category: 'Nutritional Supplement / Topical',
    uses: 'د پوستکي او د بندونو د روغتیا لپاره.',
    forms: ['Capsule', 'Cream', 'Serum'],
    side_effects: 'د پوستکي خارښت، الرژي.',
    warning: 'د پوستکي د محصولاتو لپاره د لارښوونو تعقیب مهم دی.',
  },
  {
    id: '735',
    name: 'Coenzyme Q10',
    generic: 'Coenzyme Q10',
    category: 'Nutritional Supplement',
    uses: 'د زړه د روغتیا او د انرژۍ لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، سرخوږی، د خوب ستونزې.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '736',
    name: 'Alpha-Lipoic Acid',
    generic: 'Alpha-lipoic acid',
    category: 'Nutritional Supplement',
    uses: 'د عصبي درد او د وینې د شکرې لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناراحتي، د وینې د شکرې ټیټوالی.',
    warning: 'د وینې د شکرې درملو سره تعاملات لري.',
  },
  {
    id: '737',
    name: 'L-Carnitine',
    generic: 'L-Carnitine',
    category: 'Nutritional Supplement',
    uses: 'د انرژۍ او د زړه د روغتیا لپاره.',
    forms: ['Capsule', 'Tablet', 'Oral solution'],
    side_effects: 'د معدې ناراحتي، سرګرداني.',
    warning: 'د thyroid درملو سره تعاملات لري.',
  },
  {
    id: '738',
    name: 'Creatine',
    generic: 'Creatine monohydrate',
    category: 'Nutritional Supplement',
    uses: 'د عضلاتو د ځواک او د ورزش لپاره.',
    forms: ['Capsule', 'Powder'],
    side_effects: 'د معدې ناراحتي، د اوبو ساتنه.',
    warning: 'د پښتورګو ناروغانو کې احتیاط.',
  },
  {
    id: '739',
    name: 'Whey Protein',
    generic: 'Whey protein',
    category: 'Nutritional Supplement',
    uses: 'د پروټین د اړتیا لپاره.',
    forms: ['Powder'],
    side_effects: 'د معدې ناراحتي، نفخ.',
    warning: 'د lactose intolerance لرونکو کسانو کې احتیاط.',
  },
  {
    id: '740',
    name: 'Probiotics',
    generic: 'Lactobacillus / Bifidobacterium',
    category: 'Nutritional Supplement',
    uses: 'د معدې او د کولمو د روغتیا لپاره.',
    forms: ['Capsule', 'Powder', 'Yogurt'],
    side_effects: 'د معدې ناراحتي، نفخ.',
    warning: 'د ضعیف معافیتي سیستم لرونکو کسانو کې احتیاط.',
  },
  {
    id: '741',
    name: 'Prebiotics',
    generic: 'Inulin / FOS',
    category: 'Nutritional Supplement',
    uses: 'د کولمو د روغتیا لپاره.',
    forms: ['Capsule', 'Powder'],
    side_effects: 'نفخ، د معدې ناراحتي.',
    warning: 'د IBS لرونکو کسانو کې احتیاط.',
  },
  {
    id: '742',
    name: 'Zinc (High Dose)',
    generic: 'Zinc sulfate / Zinc gluconate',
    category: 'Mineral Supplement',
    uses: 'د Zinc د کمښت او د زکام لپاره.',
    forms: ['Tablet', 'Capsule', 'Lozenge'],
    side_effects: 'زړه بدوالی، د معدې درد، د مسو کمښت.',
    warning: 'د اوږدې مودې لوړ مقدار استعمال مناسب نه دی.',
  },
  {
    id: '743',
    name: 'Selenium',
    generic: 'Selenium',
    category: 'Mineral Supplement',
    uses: 'د Selenium د کمښت لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې ناراحتي، د وېښتانو کمښت.',
    warning: 'د لوړ مقدار استعمال زهرجن دی.',
  },
  {
    id: '744',
    name: 'Chromium',
    generic: 'Chromium picolinate',
    category: 'Mineral Supplement',
    uses: 'د وینې د شکرې او کولیسټرول لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې ناراحتي، سرخوږی.',
    warning: 'د وینې د شکرې درملو سره تعاملات لري.',
  },
  {
    id: '745',
    name: 'Iodine',
    generic: 'Iodine / Potassium iodide',
    category: 'Mineral Supplement',
    uses: 'د Iodine د کمښت لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د تایرویډ ستونزې، الرژي.',
    warning: 'د thyroid درملو سره تعاملات لري.',
  },
  {
    id: '746',
    name: 'Copper',
    generic: 'Copper sulfate / Copper gluconate',
    category: 'Mineral Supplement',
    uses: 'د Copper د کمښت لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'زړه بدوالی، د معدې درد.',
    warning: 'د لوړ مقدار استعمال زهرجن دی.',
  },
  {
    id: '747',
    name: 'Manganese',
    generic: 'Manganese sulfate',
    category: 'Mineral Supplement',
    uses: 'د Manganese د کمښت لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې ناراحتي، سرخوږی.',
    warning: 'د لوړ مقدار استعمال زهرجن دی.',
  },
  {
    id: '748',
    name: 'Biotin',
    generic: 'Biotin (Vitamin B7)',
    category: 'Vitamin',
    uses: 'د وېښتانو او د نوکانو د روغتیا لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د پوستکي خارښت، د معدې ناراحتي.',
    warning: 'د لابراتواري ازموینو پایلې اغیزمنولی شي.',
  },
  {
    id: '749',
    name: 'Pantothenic Acid',
    generic: 'Pantothenic acid (Vitamin B5)',
    category: 'Vitamin',
    uses: 'د Vitamin B5 د کمښت لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې ناراحتي، اسهال.',
    warning: 'د اړتیا مطابق استعمال یې وټاکئ.',
  },
  {
    id: '750',
    name: 'Multivitamin',
    generic: 'Multivitamin',
    category: 'Vitamin Supplement',
    uses: 'د ویټامینونو د کموالي د مخنیوي لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې ناراحتي، د ادرار رنګ بدلون.',
    warning: 'د لوړ مقدار استعمال مناسب نه دی.',
  },
];
