// ==================== medicines7.js — اوومه برخه ====================
export const medicines7 = [
  {
    id: '301',
    name: 'Adenosine Triphosphate',
    generic: 'Adenosine Triphosphate',
    category: 'Antiarrhythmic',
    uses: 'د paroxysmal supraventricular tachycardia (PSVT) درملنه.',
    forms: ['Intravenous injection'],
    side_effects: 'د سینې تنګی، زړه بدوالی، سرخوږی، د مخ سوروالی.',
    warning: 'د زړه د دربې ورووالی او د برونکو سپاسم.',
  },
  {
    id: '302',
    name: 'Atrasentan',
    generic: 'Atrasentan',
    category: 'Endothelin receptor antagonist',
    uses: 'د IgA nephropathy (IgAN) درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، سرخوږی، د وینې ټیټ فشار.',
    warning: 'د جنین زیان، د ځیګر زهرجنیت.',
  },
  {
    id: '303',
    name: 'Bosentan',
    generic: 'Bosentan',
    category: 'Endothelin receptor antagonist',
    uses: 'د pulmonary arterial hypertension (PAH) درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د ځیګر انزایم لوړوالی، د وینې کمښت، سرخوږی.',
    warning: 'د جنین زیان او د ځیګر زهرجنیت.',
  },
  {
    id: '304',
    name: 'Ambrisentan',
    generic: 'Ambrisentan',
    category: 'Endothelin receptor antagonist',
    uses: 'د pulmonary arterial hypertension (PAH) درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، سرخوږی، د پوزې بندښت.',
    warning: 'د جنین زیان، د وینې د کمښت څارنه.',
  },
  {
    id: '305',
    name: 'Macitentan',
    generic: 'Macitentan',
    category: 'Endothelin receptor antagonist',
    uses: 'د pulmonary arterial hypertension (PAH) درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، سرخوږی، د وینې کمښت.',
    warning: 'د جنین زیان، د ځیګر زهرجنیت.',
  },
  {
    id: '306',
    name: 'Riociguat',
    generic: 'Riociguat',
    category: 'Soluble guanylate cyclase stimulator',
    uses: 'د PAH او CTEPH درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'سرخوږی، سرګرداني، زړه بدوالی، د وینې ټیټ فشار.',
    warning: 'د جنین زیان، د وینې ټیټ فشار او د وینې بهیدنه.',
  },
  {
    id: '307',
    name: 'Selexipag',
    generic: 'Selexipag',
    category: 'Prostacyclin receptor agonist',
    uses: 'د pulmonary arterial hypertension (PAH) درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'سرخوږی، اسهال، زړه بدوالی، د پښو پړسوب.',
    warning: 'د وینې ټیټ فشار.',
  },
  {
    id: '308',
    name: 'Treprostinil',
    generic: 'Treprostinil',
    category: 'Prostacyclin analog',
    uses: 'د pulmonary arterial hypertension (PAH) درملنه.',
    forms: ['Subcutaneous injection', 'Intravenous infusion', 'Inhalation', 'Oral tablet'],
    side_effects: 'د انفوزیون ځای درد، سرخوږی، اسهال، د پښو پړسوب.',
    warning: 'د وینې ټیټ فشار، د انفوزیون ځای انتانات.',
  },
  {
    id: '309',
    name: 'Iloprost',
    generic: 'Iloprost',
    category: 'Prostacyclin analog',
    uses: 'د pulmonary arterial hypertension (PAH) درملنه.',
    forms: ['Inhalation solution'],
    side_effects: 'د مخ سوروالی، سرخوږی، د خولې وچوالی.',
    warning: 'د وینې ټیټ فشار، د bronchospasm خطر.',
  },
  {
    id: '310',
    name: 'Epoprostenol',
    generic: 'Epoprostenol',
    category: 'Prostacyclin analog',
    uses: 'د pulmonary arterial hypertension (PAH) درملنه.',
    forms: ['Intravenous infusion'],
    side_effects: 'د مخ سوروالی، سرخوږی، د معدې ناروغي، د وینې ټیټ فشار.',
    warning: 'د وینې ټیټ فشار، د انفوزیون ځای انتانات.',
  },
  {
    id: '311',
    name: 'Cangrelor',
    generic: 'Cangrelor',
    category: 'P2Y12 platelet inhibitor',
    uses: 'د PCI په وخت کې د thrombotic پیښو مخنیوی.',
    forms: ['Intravenous infusion'],
    side_effects: 'د وینې بهیدنه.',
    warning: 'د وینې بهیدنه.',
  },
  {
    id: '312',
    name: 'Vorapaxar',
    generic: 'Vorapaxar',
    category: 'Protease-activated receptor-1 antagonist',
    uses: 'د thrombotic cardiovascular پیښو کمول.',
    forms: ['Oral tablet'],
    side_effects: 'د وینې بهیدنه، په شمول د ژوند لپاره خطرناکه بهیدنه.',
    warning: 'د intracranial hemorrhage خطر زیاتوالی.',
  },
  {
    id: '313',
    name: 'Prasugrel',
    generic: 'Prasugrel',
    category: 'P2Y12 platelet inhibitor',
    uses: 'د ACS ناروغانو کې د thrombotic پیښو کمول.',
    forms: ['Oral tablet'],
    side_effects: 'د وینې بهیدنه، TTP.',
    warning: 'د وینې بهیدو خطر.',
  },
  {
    id: '314',
    name: 'Anagrelide',
    generic: 'Anagrelide',
    category: 'Platelet-lowering agent',
    uses: 'د essential thrombocythemia درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'د زړه ګړندیتوب، پرنجی، د سینې درد، اسهال، سرخوږی.',
    warning: 'د QT اوږدوالی او ventricular tachycardia.',
  },
  {
    id: '315',
    name: 'Desirudin',
    generic: 'Desirudin',
    category: 'Direct thrombin inhibitor',
    uses: 'د DVT مخنیوی.',
    forms: ['Subcutaneous injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، anemia، د وینې بهیدنه.',
    warning: 'د spinal/epidural hematoma خطر.',
  },
  {
    id: '316',
    name: 'Lepirudin',
    generic: 'Lepirudin',
    category: 'Direct thrombin inhibitor',
    uses: 'د heparin-induced thrombocytopenia (HIT) درملنه.',
    forms: ['Intravenous injection'],
    side_effects: 'د وینې بهیدنه، تبه، د ځیګر د فعالیت غیر نورمال.',
    warning: 'د وینې بهیدو خطر.',
  },
  {
    id: '317',
    name: 'Eculizumab',
    generic: 'Eculizumab',
    category: 'Complement C5 inhibitor',
    uses: 'د PNH، aHUS، gMG درملنه.',
    forms: ['Intravenous infusion'],
    side_effects: 'سرخوږی، د پوزې بندښت، د ملا درد، زړه بدوالی.',
    warning: 'د جدي meningococcal انتاناتو خطر.',
  },
  {
    id: '318',
    name: 'Caplacizumab',
    generic: 'Caplacizumab',
    category: 'von Willebrand factor inhibitor',
    uses: 'د acquired TTP درملنه.',
    forms: ['Subcutaneous injection'],
    side_effects: 'د پوزې بهیدنه، سرخوږی، د غاښونو د وینې بهیدنه.',
    warning: 'د وینې بهیدو خطر.',
  },
  {
    id: '319',
    name: 'Emicizumab',
    generic: 'Emicizumab',
    category: 'Bispecific monoclonal antibody',
    uses: 'د hemophilia A درملنه.',
    forms: ['Subcutaneous injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی، د بندونو درد.',
    warning: 'د thrombosis خطر.',
  },
  {
    id: '320',
    name: 'Fitusiran',
    generic: 'Fitusiran',
    category: 'Antithrombin-directed siRNA therapeutic',
    uses: 'د hemophilia A یا B درملنه.',
    forms: ['Subcutaneous injection'],
    side_effects: 'د ویروسي انتاناتو، د زکام نښې.',
    warning: 'د thrombotic پیښو خطر.',
  },
  {
    id: '321',
    name: 'Concizumab',
    generic: 'Concizumab',
    category: 'Tissue factor pathway inhibitor antagonist',
    uses: 'د hemophilia A یا B درملنه.',
    forms: ['Subcutaneous injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د وینې بهیدنه.',
    warning: 'د څیړنې په مرحله کې دی.',
  },
  {
    id: '322',
    name: 'Reteplase',
    generic: 'Reteplase',
    category: 'Thrombolytic',
    uses: 'د myocardial infarction درملنه.',
    forms: ['Intravenous injection'],
    side_effects: 'د وینې بهیدنه، الرژي، د وینې ټیټ فشار.',
    warning: 'د وینې بهیدنه.',
  },
  {
    id: '323',
    name: 'Glucarpidase',
    generic: 'Glucarpidase',
    category: 'Enzyme',
    uses: 'د methotrexate زهرجنیت درملنه.',
    forms: ['Intravenous injection'],
    side_effects: 'د پوټکي خارښت، زړه بدوالی، سرخوږی.',
    warning: 'د انفوزیون غبرګونونه.',
  },
  {
    id: '324',
    name: 'Rasburicase',
    generic: 'Rasburicase',
    category: 'Urate-oxidase enzyme',
    uses: 'د tumor lysis syndrome (TLS) درملنه.',
    forms: ['Intravenous infusion'],
    side_effects: 'زړه بدوالی، د پښو پړسوب، اسهال، سرخوږی.',
    warning: 'د hemolysis خطر په G6PD deficiency کې.',
  },
  {
    id: '325',
    name: 'Pegloticase',
    generic: 'Pegloticase',
    category: 'Pegylated uricase enzyme',
    uses: 'د chronic gout درملنه.',
    forms: ['Intravenous infusion'],
    side_effects: 'د gout flare، د انفوزیون غبرګونونه، زړه بدوالی.',
    warning: 'د anaphylaxis خطر، د G6PD deficiency سره hemolysis.',
  },
  {
    id: '326',
    name: 'Asparaginase',
    generic: 'Asparaginase',
    category: 'Antineoplastic enzyme',
    uses: 'د acute lymphoblastic leukemia (ALL) درملنه.',
    forms: ['Intravenous or intramuscular injection'],
    side_effects: 'د hypersensitivity غبرګونونه، pancreatitis، thrombosis.',
    warning: 'د pancreatitis خطر، د thrombosis خطر.',
  },
  {
    id: '327',
    name: 'Calaspargase',
    generic: 'Calaspargase',
    category: 'Antineoplastic enzyme',
    uses: 'د acute lymphoblastic leukemia (ALL) درملنه.',
    forms: ['Intravenous infusion'],
    side_effects: 'د hypersensitivity غبرګونونه، pancreatitis، thrombosis.',
    warning: 'د pancreatitis خطر، د thrombosis خطر.',
  },
  {
    id: '328',
    name: 'Rituximab',
    generic: 'Rituximab',
    category: 'Monoclonal antibody (anti-CD20)',
    uses: 'د NHL، CLL، rheumatoid arthritis درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'د انفوزیون غبرګونونه، تبې، د وینې د حجرو کمښت.',
    warning: 'د وژونکي انفوزیون غبرګونونه، د PML خطر.',
  },
  {
    id: '329',
    name: 'Trastuzumab',
    generic: 'Trastuzumab',
    category: 'Monoclonal antibody (anti-HER2)',
    uses: 'د HER2-positive breast cancer درملنه.',
    forms: ['Intravenous powder for solution'],
    side_effects: 'د زړه ناکامي، د انفوزیون غبرګونونه، د وینې د حجرو کمښت.',
    warning: 'د زړه ناکامي، د جنین زیان.',
  },
  {
    id: '330',
    name: 'Bevacizumab',
    generic: 'Bevacizumab',
    category: 'Monoclonal antibody (anti-VEGF)',
    uses: 'د colorectal cancer، lung cancer درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې لوړ فشار، د وینې بهیدنه، د وینې د لخته کیدو خطر.',
    warning: 'د وینې بهیدنه، د وینې لوړ فشار.',
  },
  {
    id: '331',
    name: 'Cetuximab',
    generic: 'Cetuximab',
    category: 'Monoclonal antibody (anti-EGFR)',
    uses: 'د RAS wild-type metastatic colorectal cancer درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'د پوټکي خارښت، د انفوزیون غبرګونونه، اسهال.',
    warning: 'د انفوزیون غبرګونونه او د ILD خطر.',
  },
  {
    id: '332',
    name: 'Panitumumab',
    generic: 'Panitumumab',
    category: 'Monoclonal antibody (anti-EGFR)',
    uses: 'د RAS wild-type metastatic colorectal cancer درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'د پوټکي خارښت، اسهال، د وینې د مګنیزیم کمښت.',
    warning: 'د پوټکي خارښت، د وینې د مګنیزیم کمښت.',
  },
  {
    id: '333',
    name: 'Pertuzumab',
    generic: 'Pertuzumab',
    category: 'Monoclonal antibody (anti-HER2)',
    uses: 'د HER2-positive breast cancer درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'اسهال، د پوټکي خارښت، د انفوزیون غبرګونونه.',
    warning: 'د زړه ناکامي.',
  },
  {
    id: '334',
    name: 'Nivolumab',
    generic: 'Nivolumab',
    category: 'Monoclonal antibody (PD-1 inhibitor)',
    uses: 'د melanoma، lung cancer، renal cell carcinoma درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'ستړیا، د پوټکي خارښت، اسهال، د immune-mediated غبرګونونه.',
    warning: 'د immune-mediated غبرګونونه.',
  },
  {
    id: '335',
    name: 'Pembrolizumab',
    generic: 'Pembrolizumab',
    category: 'Monoclonal antibody (PD-1 inhibitor)',
    uses: 'د melanoma، NSCLC، head and neck cancer درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'ستړیا، د پوټکي خارښت، اسهال، د immune-mediated غبرګونونه.',
    warning: 'د immune-mediated غبرګونونه.',
  },
  {
    id: '336',
    name: 'Ipilimumab',
    generic: 'Ipilimumab',
    category: 'Monoclonal antibody (CTLA-4 inhibitor)',
    uses: 'د melanoma درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'ستړیا، اسهال، د پوټکي خارښت، د immune-mediated غبرګونونه.',
    warning: 'د immune-mediated غبرګونونه.',
  },
  {
    id: '337',
    name: 'Atezolizumab',
    generic: 'Atezolizumab',
    category: 'Monoclonal antibody (PD-L1 inhibitor)',
    uses: 'د lung cancer او bladder cancer درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'ستړیا، د پوټکي خارښت، اسهال، د immune-mediated غبرګونونه.',
    warning: 'د immune-mediated غبرګونونه.',
  },
  {
    id: '338',
    name: 'Durvalumab',
    generic: 'Durvalumab',
    category: 'Monoclonal antibody (PD-L1 inhibitor)',
    uses: 'د lung cancer او bladder cancer درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'ستړیا، د پوټکي خارښت، اسهال، د immune-mediated غبرګونونه.',
    warning: 'د immune-mediated غبرګونونه.',
  },
  {
    id: '339',
    name: 'Avelumab',
    generic: 'Avelumab',
    category: 'Monoclonal antibody (PD-L1 inhibitor)',
    uses: 'د Merkel cell carcinoma او bladder cancer درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'ستړیا، د پوټکي خارښت، اسهال، د immune-mediated غبرګونونه.',
    warning: 'د immune-mediated غبرګونونه.',
  },
  {
    id: '340',
    name: 'Sorafenib',
    generic: 'Sorafenib tosylate',
    category: 'Antineoplastic agent (kinase inhibitor)',
    uses: 'د hepatocellular carcinoma، renal cell carcinoma درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پوټکي خارښت، اسهال، د وینې لوړ فشار.',
    warning: 'د وینې لوړ فشار، د وینې بهیدنه.',
  },
  {
    id: '341',
    name: 'Sunitinib',
    generic: 'Sunitinib malate',
    category: 'Antineoplastic agent (kinase inhibitor)',
    uses: 'د renal cell carcinoma او GIST درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'ستړیا، اسهال، د وینې لوړ فشار، د پوټکي رنګ بدلون.',
    warning: 'د وینې لوړ فشار، د زړه ناکامي.',
  },
  {
    id: '342',
    name: 'Pazopanib',
    generic: 'Pazopanib hydrochloride',
    category: 'Antineoplastic agent (kinase inhibitor)',
    uses: 'د renal cell carcinoma او soft tissue sarcoma درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د وینې لوړ فشار، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر زهرجنیت، د وینې لوړ فشار.',
  },
  {
    id: '343',
    name: 'Axitinib',
    generic: 'Axitinib',
    category: 'Antineoplastic agent (kinase inhibitor)',
    uses: 'د renal cell carcinoma درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د وینې لوړ فشار، ستړیا، د پوټکي خارښت.',
    warning: 'د وینې لوړ فشار، د وینې بهیدنه.',
  },
  {
    id: '344',
    name: 'Lenvatinib',
    generic: 'Lenvatinib mesylate',
    category: 'Antineoplastic agent (kinase inhibitor)',
    uses: 'د thyroid cancer، hepatocellular carcinoma درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې لوړ فشار، اسهال، ستړیا، د پوټکي خارښت.',
    warning: 'د وینې لوړ فشار، د زړه ناکامي.',
  },
  {
    id: '345',
    name: 'Cabozantinib',
    generic: 'Cabozantinib s-malate',
    category: 'Antineoplastic agent (kinase inhibitor)',
    uses: 'د thyroid cancer، renal cell carcinoma درملنه.',
    forms: ['Oral tablet', 'Oral capsule'],
    side_effects: 'اسهال، د وینې لوړ فشار، ستړیا، د پوټکي خارښت.',
    warning: 'د وینې لوړ فشار، د gastrointestinal perforation خطر.',
  },
  {
    id: '346',
    name: 'Osimertinib',
    generic: 'Osimertinib mesylate',
    category: 'Antineoplastic agent (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوټکي خارښت، د نوکانو التهاب.',
    warning: 'د QT prolongation او د ILD خطر.',
  },
  {
    id: '347',
    name: 'Erlotinib',
    generic: 'Erlotinib hydrochloride',
    category: 'Antineoplastic agent (EGFR inhibitor)',
    uses: 'د NSCLC او pancreatic cancer درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پوټکي خارښت، اسهال، ستړیا، د اشتها کمښت.',
    warning: 'د ILD خطر، د ځیګر زهرجنیت.',
  },
  {
    id: '348',
    name: 'Gefitinib',
    generic: 'Gefitinib',
    category: 'Antineoplastic agent (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پوټکي خارښت، اسهال، د ځیګر انزایم لوړوالی.',
    warning: 'د ILD خطر، د ځیګر زهرجنیت.',
  },
  {
    id: '349',
    name: 'Crizotinib',
    generic: 'Crizotinib',
    category: 'Antineoplastic agent (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'د لید ستونزې، زړه بدوالی، اسهال، د پښو پړسوب.',
    warning: 'د لید ستونزې، د زړه د دربې غیر نورمال.',
  },
  {
    id: '350',
    name: 'Alectinib',
    generic: 'Alectinib hydrochloride',
    category: 'Antineoplastic agent (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'ستړیا، د پښو پړسوب، د پوټکي خارښت، د عضلاتو درد.',
    warning: 'د ځیګر زهرجنیت، د ILD خطر.',
  },
];
