// ==================== medicines6.js — شپږمه برخه ====================
export const medicines6 = [
  {
    id: '251',
    name: 'Atovaquone',
    generic: 'Atovaquone',
    category: 'Antiparasitic',
    uses: 'د Pneumocystis pneumonia او ملاریا درملنه.',
    forms: ['Oral Suspension'],
    side_effects: 'اسهال، د پوټکي خارښت، سرخوږی، زړه بدوالی.',
    warning: 'اسهال، د پوټکي خارښت.',
  },
  {
    id: '252',
    name: 'Proguanil',
    generic: 'Proguanil',
    category: 'Antimalarial',
    uses: 'د ملاریا مخنیوی او درملنه (د Atovaquone سره).',
    forms: ['Tablet'],
    side_effects: 'د معدې درد، زړه بدوالی، اسهال، سرخوږی.',
    warning: 'د معدې درد، زړه بدوالی.',
  },
  {
    id: '253',
    name: 'Artemether',
    generic: 'Artemether',
    category: 'Antimalarial',
    uses: 'د ملاریا درملنه.',
    forms: ['Injection'],
    side_effects: 'سرخوږی، د اشتها کمښت، سرګرداني، د بندونو درد.',
    warning: 'سرخوږی، د اشتها کمښت.',
  },
  {
    id: '254',
    name: 'Dihydroartemisinin',
    generic: 'Dihydroartemisinin',
    category: 'Antimalarial',
    uses: 'د ملاریا درملنه (د Piperaquine سره).',
    forms: ['Tablet'],
    side_effects: 'سرخوږی، زړه بدوالی، سرګرداني.',
    warning: 'سرخوږی، زړه بدوالی.',
  },
  {
    id: '255',
    name: 'Chloroquine',
    generic: 'Chloroquine',
    category: 'Antimalarial',
    uses: 'د ملاریا درملنه او مخنیوی.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د سترګو زیان، د معدې ناروغي، سرخوږی، د پوټکي خارښت.',
    warning: 'د سترګو زیان، د معدې ناروغي.',
  },
  {
    id: '256',
    name: 'Quinacrine',
    generic: 'Quinacrine',
    category: 'Antimalarial',
    uses: 'د Giardia درملنه.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، د معدې cramp، سرخوږی، سرګرداني.',
    warning: 'زړه بدوالی، د معدې cramp.',
  },
  {
    id: '257',
    name: 'Thiabendazole',
    generic: 'Thiabendazole',
    category: 'Anthelmintic',
    uses: 'د چینجي انتاناتو درملنه.',
    forms: ['Tablet'],
    side_effects: 'سرګرداني، زړه بدوالی، اسهال، د وېښتانو کمښت.',
    warning: 'سرګرداني، زړه بدوالی.',
  },
  {
    id: '258',
    name: 'Triclabendazole',
    generic: 'Triclabendazole',
    category: 'Anthelmintic',
    uses: 'د فاسیولیاسس (د ځیګر چینجي) درملنه.',
    forms: ['Tablet'],
    side_effects: 'د معدې درد، د پوټکي خارښت، د وینې ټیټ فشار.',
    warning: 'د معدې درد، د پوټکي خارښت.',
  },
  {
    id: '259',
    name: 'Oxamniquine',
    generic: 'Oxamniquine',
    category: 'Antiparasitic',
    uses: 'د شیتوزومیاسس (Schistosoma mansoni) درملنه.',
    forms: ['Capsule'],
    side_effects: 'خوبجن، سرګرداني، سرخوږی، زړه بدوالی.',
    warning: 'خوبجن، سرګرداني.',
  },
  {
    id: '260',
    name: 'Benznidazole',
    generic: 'Benznidazole',
    category: 'Antiparasitic',
    uses: 'د چاګاس ناروغۍ درملنه.',
    forms: ['Tablet'],
    side_effects: 'د معدې درد، د پوټکي خارښت، سرخوږی، زړه بدوالی.',
    warning: 'د معدې درد، د پوټکي خارښت.',
  },
  {
    id: '261',
    name: 'Bedaquiline',
    generic: 'Bedaquiline fumarate',
    category: 'Antitubercular',
    uses: 'د MDR-TB درملنه.',
    forms: ['Tablet'],
    side_effects: 'د QT اوږدوالی، زړه بدوالی، د بندونو درد، د ځیګر انزایم لوړوالی.',
    warning: 'د QT اوږدوالی، د ECG منظم څارنه.',
  },
  {
    id: '262',
    name: 'Delamanid',
    generic: 'Delamanid',
    category: 'Antitubercular',
    uses: 'د multidrug-resistant tuberculosis (MDR-TB) درملنه.',
    forms: ['Tablet'],
    side_effects: 'د QT interval اوږدوالی، سرخوږی، زړه بدوالی، سرګردانی.',
    warning: 'د QT اوږدوالی او د serum albumin کمښت.',
  },
  {
    id: '263',
    name: 'Pretomanid',
    generic: 'Pretomanid',
    category: 'Antitubercular',
    uses: 'د MDR-TB او XDR-TB درملنه.',
    forms: ['Tablet'],
    side_effects: 'د ځیګر زهرجنیت، د وینې د حجرو کمښت، د اعصابو درد.',
    warning: 'د ځیګر زهرجنیت، د وینې د حجرو کمښت.',
  },
  {
    id: '264',
    name: 'Ceftolozane + Tazobactam',
    generic: 'Ceftolozane + Tazobactam',
    category: 'Antibiotic',
    uses: 'د پیچلو انتاناتو درملنه (د ادرار، د معدې).',
    forms: ['Injection'],
    side_effects: 'زړه بدوالی، اسهال، سرخوږی، تبه.',
    warning: 'زړه بدوالی، اسهال.',
  },
  {
    id: '265',
    name: 'Ceftazidime + Avibactam',
    generic: 'Ceftazidime + Avibactam',
    category: 'Antibiotic',
    uses: 'د پیچلو انتاناتو درملنه.',
    forms: ['Injection'],
    side_effects: 'اسهال، زړه بدوالی، د پوټکي خارښت.',
    warning: 'اسهال، زړه بدوالی.',
  },
  {
    id: '266',
    name: 'Meropenem + Vaborbactam',
    generic: 'Meropenem + Vaborbactam',
    category: 'Antibiotic',
    uses: 'د پیچلو انتاناتو درملنه (د ادرار).',
    forms: ['Injection'],
    side_effects: 'سرخوږی، د انفوزیون ځای غبرګونونه، اسهال.',
    warning: 'سرخوږی، د انفوزیون ځای غبرګونونه.',
  },
  {
    id: '267',
    name: 'Telithromycin',
    generic: 'Telithromycin',
    category: 'Macrolide Antibiotic',
    uses: 'د سږو انتاناتو درملنه.',
    forms: ['Tablet'],
    side_effects: 'اسهال، زړه بدوالی، سرګردانی، د لید ستونزې.',
    warning: 'د ځیګر زهرجنیت، د لید ستونزې.',
  },
  {
    id: '268',
    name: 'Tedizolid',
    generic: 'Tedizolid phosphate',
    category: 'Antibiotic',
    uses: 'د پوټکي انتاناتو درملنه.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'زړه بدوالی، سرخوږی، اسهال، سرګردانی.',
    warning: 'د وینې د حجرو کمښت او د اعصابو درد.',
  },
  {
    id: '269',
    name: 'Dalbavancin',
    generic: 'Dalbavancin hydrochloride',
    category: 'Antibiotic',
    uses: 'د پوټکي انتاناتو درملنه.',
    forms: ['Injection'],
    side_effects: 'زړه بدوالی، سرخوږی، اسهال.',
    warning: 'د انفوزیون غبرګونونه او د ځیګر انزایم لوړوالی.',
  },
  {
    id: '270',
    name: 'Oritavancin',
    generic: 'Oritavancin diphosphate',
    category: 'Antibiotic',
    uses: 'د پوټکي او د پوټکي د جوړښتونو د شدیدو بکتریایي انتاناتو درملنه.',
    forms: ['Injection'],
    side_effects: 'سرخوږی، زړه بدوالی، اسهال، د انفوزیون ځای غبرګونونه.',
    warning: 'د انفوزیون غبرګونونه او د aPTT ازموینې اغیزه.',
  },
  {
    id: '271',
    name: 'Ceftaroline',
    generic: 'Ceftaroline fosamil',
    category: 'Cephalosporin Antibiotic',
    uses: 'د پوټکي او سږو انتاناتو درملنه.',
    forms: ['Injection'],
    side_effects: 'اسهال، زړه بدوالی، د پوټکي خارښت.',
    warning: 'د الرژي خطر او د Clostridium difficile اسهال.',
  },
  {
    id: '272',
    name: 'Ceftobiprole',
    generic: 'Ceftobiprole',
    category: 'Cephalosporin Antibiotic',
    uses: 'د پوټکي او سږو انتاناتو درملنه.',
    forms: ['Injection'],
    side_effects: 'زړه بدوالی، اسهال، سرخوږی، د انجیکشن ځای غبرګونونه.',
    warning: 'زړه بدوالی، اسهال.',
  },
  {
    id: '273',
    name: 'Cefiderocol',
    generic: 'Cefiderocol',
    category: 'Cephalosporin Antibiotic',
    uses: 'د پیچلو انتاناتو درملنه (د ادرار، د سږو).',
    forms: ['Injection'],
    side_effects: 'اسهال، د پوتاشیم کمښت، د پوټکي خارښت.',
    warning: 'اسهال، د پوتاشیم کمښت.',
  },
  {
    id: '274',
    name: 'Plazomicin',
    generic: 'Plazomicin sulfate',
    category: 'Aminoglycoside Antibiotic',
    uses: 'د ادرار د لارې پیچلو انتاناتو درملنه.',
    forms: ['Injection'],
    side_effects: 'د پښتورګو ستونزې، اسهال، د وینې لوړ فشار، سرخوږی.',
    warning: 'د پښتورګو او غوږونو زهرجنیت.',
  },
  {
    id: '275',
    name: 'Eravacycline',
    generic: 'Eravacycline dihydrochloride',
    category: 'Tetracycline Antibiotic',
    uses: 'د معدې د انتاناتو درملنه.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون ځای غبرګونونه، زړه بدوالی، اسهال.',
    warning: 'د tetracyclines ټولګي خبرداری.',
  },
  {
    id: '276',
    name: 'Omadacycline',
    generic: 'Omadacycline tosylate',
    category: 'Tetracycline Antibiotic',
    uses: 'د سږو او پوټکي انتاناتو درملنه.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'زړه بدوالی، اسهال، سرخوږی، د ځیګر انزایم لوړوالی.',
    warning: 'د tetracyclines ټولګي خبرداری.',
  },
  {
    id: '277',
    name: 'Delafloxacin',
    generic: 'Delafloxacin meglumine',
    category: 'Fluoroquinolone Antibiotic',
    uses: 'د پوټکي انتاناتو درملنه.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'زړه بدوالی، اسهال، سرخوږی، د ځیګر انزایم لوړوالی.',
    warning: 'د fluoroquinolones ټولګي خبرداری.',
  },
  {
    id: '278',
    name: 'Isavuconazole',
    generic: 'Isavuconazole',
    category: 'Antifungal',
    uses: 'د فنجي انتاناتو درملنه.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، اسهال، د پوټکي خارښت.',
    warning: 'زړه بدوالی، اسهال.',
  },
  {
    id: '279',
    name: 'Anidulafungin',
    generic: 'Anidulafungin',
    category: 'Antifungal',
    uses: 'د کاندیدا انتاناتو درملنه.',
    forms: ['Injection'],
    side_effects: 'د پوتاشیم کمښت، زړه بدوالی، اسهال، تبه.',
    warning: 'د پوتاشیم کمښت، زړه بدوالی.',
  },
  {
    id: '280',
    name: 'Flucytosine',
    generic: 'Flucytosine',
    category: 'Antifungal',
    uses: 'د فنجي انتاناتو درملنه (د امفوتریسین B سره).',
    forms: ['Capsule'],
    side_effects: 'د وینې د حجرو کمښت، د ځیګر زهرجنیت، زړه بدوالی.',
    warning: 'د وینې د حجرو کمښت، د ځیګر زهرجنیت.',
  },
  {
    id: '281',
    name: 'Terconazole',
    generic: 'Terconazole',
    category: 'Antifungal',
    uses: 'د اندام فنجي انتاناتو درملنه.',
    forms: ['Cream', 'Suppository'],
    side_effects: 'سرخوږی، د اندام سوځیدنه، خارښت.',
    warning: 'سرخوږی، د اندام سوځیدنه.',
  },
  {
    id: '282',
    name: 'Butoconazole',
    generic: 'Butoconazole',
    category: 'Antifungal',
    uses: 'د اندام فنجي انتاناتو درملنه.',
    forms: ['Cream'],
    side_effects: 'د اندام سوځیدنه، خارښت.',
    warning: 'د اندام سوځیدنه، خارښت.',
  },
  {
    id: '283',
    name: 'Naftifine',
    generic: 'Naftifine',
    category: 'Antifungal',
    uses: 'د پوټکي فنجي انتاناتو درملنه.',
    forms: ['Cream', 'Gel'],
    side_effects: 'خارښت، د پوټکي سوځیدنه.',
    warning: 'خارښت، د پوټکي سوځیدنه.',
  },
  {
    id: '284',
    name: 'Amorolfine',
    generic: 'Amorolfine',
    category: 'Antifungal',
    uses: 'د نوکانو فنجي انتاناتو درملنه.',
    forms: ['Nail Lacquer'],
    side_effects: 'د نوکانو شاوخوا د پوټکي خارښت، د نوکانو رنګ بدلون.',
    warning: 'د نوکانو شاوخوا د پوټکي خارښت.',
  },
  {
    id: '285',
    name: 'Luliconazole',
    generic: 'Luliconazole',
    category: 'Antifungal',
    uses: 'د پوټکي فنجي انتاناتو درملنه.',
    forms: ['Cream'],
    side_effects: 'د تطبیق ځای غبرګونونه.',
    warning: 'د تطبیق ځای غبرګونونه.',
  },
  {
    id: '286',
    name: 'Efinaconazole',
    generic: 'Efinaconazole',
    category: 'Antifungal',
    uses: 'د نوکانو فنجي انتاناتو درملنه.',
    forms: ['Topical Solution'],
    side_effects: 'د نوکانو دننه وده، د تطبیق ځای خارښت.',
    warning: 'د نوکانو دننه ودې، د تطبیق ځای خارښت.',
  },
  {
    id: '287',
    name: 'Desonide',
    generic: 'Desonide',
    category: 'Topical Corticosteroid',
    uses: 'د پوټکي التهاب او خارښت درملنه.',
    forms: ['Cream', 'Ointment', 'Lotion'],
    side_effects: 'د تطبیق ځای سوځیدنه، سرخوږی.',
    warning: 'د تطبیق ځای سوځیدنه، سرخوږی.',
  },
  {
    id: '288',
    name: 'Triamcinolone Acetonide',
    generic: 'Triamcinolone Acetonide',
    category: 'Corticosteroid',
    uses: 'د بندونو او پوټکي التهاب درملنه.',
    forms: ['Cream', 'Ointment', 'Injection'],
    side_effects: 'د انجیکشن ځای درد، د پوټکي atrophy.',
    warning: 'د انجیکشن ځای درد، د پوټکي atrophy.',
  },
  {
    id: '289',
    name: 'Fluocinolone Acetonide',
    generic: 'Fluocinolone Acetonide',
    category: 'Topical Corticosteroid',
    uses: 'د پوټکي التهاب درملنه.',
    forms: ['Cream', 'Ointment'],
    side_effects: 'د پوټکي atrophy، خارښت، د پوټکي وچوالی.',
    warning: 'د پوټکي atrophy، خارښت.',
  },
  {
    id: '290',
    name: 'Clobetasol Propionate',
    generic: 'Clobetasol Propionate',
    category: 'Topical Corticosteroid',
    uses: 'د پوټکي التهاب درملنه.',
    forms: ['Cream', 'Ointment', 'Lotion'],
    side_effects: 'د پوټکي سوځیدنه، خارښت، د پوټکي atrophy.',
    warning: 'د پوټکي atrophy، خارښت.',
  },
  {
    id: '291',
    name: 'Betamethasone',
    generic: 'Betamethasone',
    category: 'Corticosteroid',
    uses: 'د پوټکي او بندونو التهاب درملنه.',
    forms: ['Cream', 'Ointment', 'Injection'],
    side_effects: 'د پوټکي atrophy، د وینې د شکرې لوړوالی.',
    warning: 'د پوټکي atrophy، د وینې د شکرې لوړوالی.',
  },
  {
    id: '292',
    name: 'Desoximetasone',
    generic: 'Desoximetasone',
    category: 'Topical Corticosteroid',
    uses: 'د پوټکي التهاب درملنه.',
    forms: ['Cream', 'Ointment'],
    side_effects: 'د تطبیق ځای وچوالی، خارښت.',
    warning: 'د تطبیق ځای وچوالی، خارښت.',
  },
  {
    id: '293',
    name: 'Calcipotriene',
    generic: 'Calcipotriene',
    category: 'Topical Dermatologic',
    uses: 'د پسوریازیس درملنه.',
    forms: ['Cream', 'Ointment'],
    side_effects: 'د تطبیق ځای سوروالی، درد.',
    warning: 'د تطبیق ځای سوروالی، درد.',
  },
  {
    id: '294',
    name: 'Tazarotene',
    generic: 'Tazarotene',
    category: 'Topical Retinoid',
    uses: 'د پسوریازیس او د ځوانۍ داغونو درملنه.',
    forms: ['Cream', 'Gel'],
    side_effects: 'خارښت، د پوټکي سوروالی، د پوټکي وچوالی.',
    warning: 'خارښت، د پوټکي سوروالی.',
  },
  {
    id: '295',
    name: 'Adapalene',
    generic: 'Adapalene',
    category: 'Topical Retinoid',
    uses: 'د ځوانۍ داغونو درملنه.',
    forms: ['Gel', 'Cream'],
    side_effects: 'د پوټکي وچوالی، خارښت، د پوټکي سوروالی.',
    warning: 'د پوټکي وچوالی، خارښت.',
  },
  {
    id: '296',
    name: 'Azelaic Acid',
    generic: 'Azelaic Acid',
    category: 'Dermatologic',
    uses: 'د روزاسیا او د ځوانۍ داغونو درملنه.',
    forms: ['Cream', 'Gel'],
    side_effects: 'د پوټکي سوځیدنه، خارښت، د پوټکي وچوالی.',
    warning: 'د پوټکي سوځیدنه، خارښت.',
  },
  {
    id: '297',
    name: 'Ivermectin Cream',
    generic: 'Ivermectin',
    category: 'Dermatologic',
    uses: 'د روزاسیا درملنه.',
    forms: ['Cream'],
    side_effects: 'د پوټکي سوځیدنه، خارښت.',
    warning: 'د پوټکي سوځیدنه، خارښت.',
  },
  {
    id: '298',
    name: 'Permethrin Lotion',
    generic: 'Permethrin',
    category: 'Antiparasitic / Dermatologic',
    uses: 'د سرې (lice) او جرب (scabies) درملنه.',
    forms: ['Lotion'],
    side_effects: 'د پوټکي خارښت، سوروالی، د سترګو خارښت.',
    warning: 'د پوټکي خارښت، سوروالی.',
  },
  {
    id: '299',
    name: 'Vernakalant',
    generic: 'Vernakalant',
    category: 'Class III antiarrhythmic agent',
    uses: 'د atrial fibrillation درملنه چې په تیرو ۷ ورځو کې پیل شوې وي.',
    forms: ['Intravenous infusion'],
    side_effects: 'د خوند بدلون، پرنجی، د پوستکي ټکول، د وینې ټیټ فشار.',
    warning: 'د وینې ټیټ فشار او د زړه ورووالی.',
  },
  {
    id: '300',
    name: 'Ibutilide',
    generic: 'Ibutilide',
    category: 'Class III antiarrhythmic agent',
    uses: 'د atrial fibrillation او atrial flutter درملنه.',
    forms: ['Intravenous injection'],
    side_effects: 'د QT اوږدوالی، Torsades de Pointes، د زړه د دربې غیر نورمال.',
    warning: 'د QT اوږدوالی او Torsades de Pointes.',
  },
];
