// ==================== medicines4.js — څلورمه برخه ====================
export const medicines4 = [
  {
    id: '151',
    name: 'Aprepitant',
    generic: 'Aprepitant',
    category: 'Antiemetic',
    uses: 'د ځینو chemotherapy اړوند nausea او vomiting د مخنیوي لپاره.',
    forms: ['Capsule'],
    side_effects: 'ستړیا، قبضیت، هیکا.',
    warning: 'د CYP3A4 substrates کچه زیاتوي.',
  },
  {
    id: '152',
    name: 'Olopatadine',
    generic: 'Olopatadine',
    category: 'Ophthalmic',
    uses: 'د سترګو د Allergy په ځینو حالتونو کې.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو خارښت، سرخوږی.',
    warning: 'د سترګو خارښت، سرخوږی.',
  },
  {
    id: '153',
    name: 'Ketorolac Ophthalmic',
    generic: 'Ketorolac',
    category: 'Ophthalmic NSAID',
    uses: 'د سترګو د ځینو inflammatory حالتونو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو سوځیدنه.',
    warning: 'د سترګو سوځیدنه، د وینې بهیدنه.',
  },
  {
    id: '154',
    name: 'Prednisolone Ophthalmic',
    generic: 'Prednisolone',
    category: 'Ophthalmic Corticosteroid',
    uses: 'د سترګو د ځینو inflammatory حالتونو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو فشار لوړوالی، کتاراکټ.',
    warning: 'د سترګو فشار لوړوالی، کتاراکټ.',
  },
  {
    id: '155',
    name: 'Dexamethasone Ophthalmic',
    generic: 'Dexamethasone',
    category: 'Ophthalmic Corticosteroid',
    uses: 'د سترګو د ځینو inflammatory حالتونو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو فشار لوړوالی، کتاراکټ.',
    warning: 'د سترګو فشار لوړوالی، کتاراکټ.',
  },
  {
    id: '156',
    name: 'Brinzolamide',
    generic: 'Brinzolamide',
    category: 'Ophthalmic',
    uses: 'د سترګو د فشار د کمولو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د لید تیاره والی، د خوند بدلون.',
    warning: 'د لید تیاره والی، د خوند بدلون.',
  },
  {
    id: '157',
    name: 'Methazolamide',
    generic: 'Methazolamide',
    category: 'Carbonic Anhydrase Inhibitor',
    uses: 'د سترګو د فشار په ځینو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'د پوټکي ټکول، ستړیا، میټابولیک اسیدوز.',
    warning: 'د پوټکي ټکول، ستړیا، میټابولیک اسیدوز.',
  },
  {
    id: '158',
    name: 'Pilocarpine',
    generic: 'Pilocarpine',
    category: 'Ophthalmic',
    uses: 'د سترګو د ځینو ځانګړو حالتونو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د لید تیاره والی، د سرخوږی.',
    warning: 'د لید تیاره والی، د سرخوږی.',
  },
  {
    id: '159',
    name: 'Tafluprost',
    generic: 'Tafluprost',
    category: 'Ophthalmic',
    uses: 'د سترګو د فشار د کمولو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو سوروالی، د وېښتانو زیاتوالی.',
    warning: 'د سترګو سوروالی، د وېښتانو زیاتوالی.',
  },
  {
    id: '160',
    name: 'Nepafenac',
    generic: 'Nepafenac',
    category: 'Ophthalmic NSAID',
    uses: 'د سترګو د ځینو التهابي حالتونو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو خارښت، سرخوږی.',
    warning: 'د سترګو خارښت، سرخوږی.',
  },
  {
    id: '161',
    name: 'Bromfenac',
    generic: 'Bromfenac',
    category: 'Ophthalmic NSAID',
    uses: 'د سترګو د ځینو التهابي حالتونو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو سوځیدنه، خارښت.',
    warning: 'د سترګو سوځیدنه، خارښت.',
  },
  {
    id: '162',
    name: 'Loteprednol',
    generic: 'Loteprednol',
    category: 'Ophthalmic Corticosteroid',
    uses: 'د سترګو د ځینو inflammatory حالتونو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو فشار لوړوالی، کتاراکټ.',
    warning: 'د سترګو فشار لوړوالی، کتاراکټ.',
  },
  {
    id: '163',
    name: 'Fluorometholone',
    generic: 'Fluorometholone',
    category: 'Ophthalmic Corticosteroid',
    uses: 'د سترګو د ځینو inflammatory حالتونو لپاره.',
    forms: ['Eye Drops'],
    side_effects: 'د سترګو فشار لوړوالی، کتاراکټ.',
    warning: 'د سترګو فشار لوړوالی، کتاراکټ.',
  },
  {
    id: '164',
    name: 'Naratriptan',
    generic: 'Naratriptan',
    category: 'Antimigraine',
    uses: 'د Migraine د حادې حملې لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرګردانی، خوبجن، زړه بدوالی.',
    warning: 'د زړه حمله، serotonin syndrome.',
  },
  {
    id: '165',
    name: 'Almotriptan',
    generic: 'Almotriptan',
    category: 'Antimigraine',
    uses: 'د Migraine د حادې حملې لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرګردانی، زړه بدوالی، ستړیا.',
    warning: 'د زړه حمله، serotonin syndrome.',
  },
  {
    id: '166',
    name: 'Frovatriptan',
    generic: 'Frovatriptan',
    category: 'Antimigraine',
    uses: 'د Migraine د حادې حملې لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرګردانی، ستړیا، زړه بدوالی.',
    warning: 'د زړه حمله، serotonin syndrome.',
  },
  {
    id: '167',
    name: 'Galantamine',
    generic: 'Galantamine',
    category: 'Cholinesterase Inhibitor',
    uses: 'د ځینو Dementia حالتونو لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'زړه بدوالی، اسهال.',
    warning: 'زړه بدوالی، اسهال، د زړه ورووالی.',
  },
  {
    id: '168',
    name: 'Rivastigmine',
    generic: 'Rivastigmine',
    category: 'Cholinesterase Inhibitor',
    uses: 'د ځینو Dementia حالتونو لپاره.',
    forms: ['Capsule', 'Patch'],
    side_effects: 'زړه بدوالی، د وزن کمښت.',
    warning: 'زړه بدوالی، د وزن کمښت.',
  },
  {
    id: '169',
    name: 'Donepezil',
    generic: 'Donepezil',
    category: 'Cholinesterase Inhibitor',
    uses: 'د ځینو Dementia حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، اسهال، د خوب ستونزې.',
    warning: 'زړه بدوالی، اسهال، د خوب ستونزې.',
  },
  {
    id: '170',
    name: 'Memantine',
    generic: 'Memantine',
    category: 'NMDA Antagonist',
    uses: 'د ځینو Dementia حالتونو لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'سرګردانی، سرخوږی، قبضیت.',
    warning: 'سرګردانی، سرخوږی، قبضیت.',
  },
  {
    id: '171',
    name: 'Ropinirole',
    generic: 'Ropinirole',
    category: 'Dopamine Agonist',
    uses: 'د Parkinson\'s disease او ځینو نورو حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، سرګردانی، خوبجن.',
    warning: 'زړه بدوالی، سرګردانی، خوبجن.',
  },
  {
    id: '172',
    name: 'Pramipexole',
    generic: 'Pramipexole',
    category: 'Dopamine Agonist',
    uses: 'د Parkinson\'s disease او ځینو نورو حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، سرګردانی، خوبجن.',
    warning: 'زړه بدوالی، سرګردانی، خوبجن.',
  },
  {
    id: '173',
    name: 'Amantadine',
    generic: 'Amantadine',
    category: 'Antiviral / Neurologic',
    uses: 'په ځینو عصبي او ویروسي حالتونو کې.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'سرګردانی، د خوب ستونزې.',
    warning: 'سرګردانی، د خوب ستونزې.',
  },
  {
    id: '174',
    name: 'Tolterodine',
    generic: 'Tolterodine',
    category: 'Anticholinergic',
    uses: 'د Overactive Bladder د ځینو نښو لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د خولې وچوالی، قبضیت، د لید تیاره والی.',
    warning: 'د خولې وچوالی، قبضیت، د لید تیاره والی.',
  },
  {
    id: '175',
    name: 'Solifenacin',
    generic: 'Solifenacin',
    category: 'Anticholinergic',
    uses: 'د Overactive Bladder د ځینو نښو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د خولې وچوالی، قبضیت.',
    warning: 'د خولې وچوالی، قبضیت.',
  },
  {
    id: '176',
    name: 'Mirabegron',
    generic: 'Mirabegron',
    category: 'Beta-3 Agonist',
    uses: 'د Overactive Bladder د ځینو نښو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې لوړ فشار، سرخوږی، د ادرار انتانات.',
    warning: 'د وینې لوړ فشار، سرخوږی، د ادرار انتانات.',
  },
  {
    id: '177',
    name: 'Dutasteride',
    generic: 'Dutasteride',
    category: '5-alpha Reductase Inhibitor',
    uses: 'د Benign Prostatic Hyperplasia لپاره.',
    forms: ['Capsule'],
    side_effects: 'جنسي ستونزې، د سینې پړسوب.',
    warning: 'جنسي ستونزې، د سینې پړسوب.',
  },
  {
    id: '178',
    name: 'Alfuzosin',
    generic: 'Alfuzosin',
    category: 'Alpha-1 Blocker',
    uses: 'د Benign Prostatic Hyperplasia اړوند د ادرار ستونزو لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرګردانی، د وینې ټیټ فشار.',
    warning: 'سرګردانی، د وینې ټیټ فشار.',
  },
  {
    id: '179',
    name: 'Silodosin',
    generic: 'Silodosin',
    category: 'Alpha-1 Blocker',
    uses: 'د Benign Prostatic Hyperplasia اړوند د ادرار ستونزو لپاره.',
    forms: ['Capsule'],
    side_effects: 'د انزال ستونزه، سرګردانی.',
    warning: 'د انزال ستونزه، سرګردانی.',
  },
  {
    id: '180',
    name: 'Protamine Sulfate',
    generic: 'Protamine Sulfate',
    category: 'Anticoagulant Reversal',
    uses: 'په روغتون کې د Heparin اغېز د بېرته راګرځولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې ټیټ فشار، الرژي.',
    warning: 'د وینې ټیټ فشار، د الرژي خطر.',
  },
  {
    id: '181',
    name: 'Nicardipine',
    generic: 'Nicardipine',
    category: 'Calcium Channel Blocker',
    uses: 'د لوړ فشار په ځینو طبي حالتونو کې.',
    forms: ['Capsule', 'Injection'],
    side_effects: 'سرخوږی، د مخ سوروالی، سرګردانی.',
    warning: 'سرخوږی، د مخ سوروالی، سرګردانی.',
  },
  {
    id: '182',
    name: 'Labetalol',
    generic: 'Labetalol',
    category: 'Antihypertensive',
    uses: 'د لوړ فشار په ځینو حالتونو کې.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'سرګردانی، ستړیا، زړه بدوالی.',
    warning: 'سرګردانی، ستړیا، زړه بدوالی.',
  },
  {
    id: '183',
    name: 'Sodium Nitroprusside',
    generic: 'Sodium Nitroprusside',
    category: 'Vasodilator',
    uses: 'په روغتون کې د شدید لوړ فشار په ځانګړو حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'د وینې ټیټ فشار، د ساینایډ زهرجنیت.',
    warning: 'د وینې ټیټ فشار، د ساینایډ زهرجنیت.',
  },
  {
    id: '184',
    name: 'Calcium Chloride',
    generic: 'Calcium Chloride',
    category: 'Electrolyte',
    uses: 'په ځینو بیړنیو Electrolyte حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'د زړه ورووالی، د وینې ټیټ فشار.',
    warning: 'د زړه ورووالی، د وینې ټیټ فشار.',
  },
  {
    id: '185',
    name: 'Potassium Phosphate',
    generic: 'Potassium Phosphate',
    category: 'Electrolyte',
    uses: 'د Phosphate او Potassium د کموالي په ځینو حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'د پوتاشیم لوړوالی، د فاسفورس لوړوالی.',
    warning: 'د پوتاشیم لوړوالی، د فاسفورس لوړوالی.',
  },
  {
    id: '186',
    name: 'Sodium Phosphate',
    generic: 'Sodium Phosphate',
    category: 'Electrolyte',
    uses: 'د Phosphate د کموالي په ځینو حالتونو کې.',
    forms: ['Injection', 'Oral Solution'],
    side_effects: 'اسهال، د فاسفورس لوړوالی.',
    warning: 'اسهال، د فاسفورس لوړوالی.',
  },
  {
    id: '187',
    name: 'Potassium Acetate',
    generic: 'Potassium Acetate',
    category: 'Electrolyte',
    uses: 'د Potassium د کموالي په ځینو روغتيايي حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'د پوتاشیم لوړوالی، د رګونو التهاب.',
    warning: 'د پوتاشیم لوړوالی، د رګونو التهاب.',
  },
  {
    id: '188',
    name: 'Sodium Lactate',
    generic: 'Sodium Lactate',
    category: 'Electrolyte',
    uses: 'په ځینو طبي او مایعاتو اړوندو حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'الکالوز، د اوبو ساتنه.',
    warning: 'الکالوز، د اوبو ساتنه.',
  },
  {
    id: '189',
    name: 'Human Albumin',
    generic: 'Albumin Human',
    category: 'Plasma Expander',
    uses: 'په روغتون کې د ځینو ځانګړو حالتونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د اوبو ساتنه، الرژي.',
    warning: 'د اوبو ساتنه، الرژي.',
  },
  {
    id: '190',
    name: 'Glycerin Suppository',
    generic: 'Glycerol',
    category: 'Laxative',
    uses: 'د قبض د لنډمهاله درملنې لپاره.',
    forms: ['Suppository'],
    side_effects: 'د مقعد خارښت.',
    warning: 'د مقعد خارښت.',
  },
  {
    id: '191',
    name: 'Pancreatin',
    generic: 'Pancreatin',
    category: 'Digestive Enzyme',
    uses: 'د پانقراس د انزایمونو د کموالي په ځینو حالتونو کې.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې ناروغي.',
    warning: 'د معدې ناروغي.',
  },
  {
    id: '192',
    name: 'Lactase',
    generic: 'Lactase',
    category: 'Digestive Enzyme',
    uses: 'د Lactose د هضم د ستونزو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د معدې ناروغي.',
    warning: 'د معدې ناروغي.',
  },
  {
    id: '193',
    name: 'Docusate',
    generic: 'Docusate',
    category: 'Stool Softener',
    uses: 'د قبض د ځینو حالتونو لپاره.',
    forms: ['Capsule', 'Liquid'],
    side_effects: 'اسهال، cramp.',
    warning: 'اسهال، cramp.',
  },
  {
    id: '194',
    name: 'Dextran 40',
    generic: 'Dextran 40',
    category: 'Plasma Expander',
    uses: 'په روغتون کې د ځینو ځانګړو مایعاتو اړوندو حالتونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د اوبو ساتنه، الرژي.',
    warning: 'د اوبو ساتنه، الرژي.',
  },
  {
    id: '195',
    name: 'Mannitol 20%',
    generic: 'Mannitol',
    category: 'Osmotic Diuretic',
    uses: 'په روغتون کې د ځینو ځانګړو طبي حالتونو لپاره.',
    forms: ['IV Solution'],
    side_effects: 'د اوبو عدم توازن، د پښتورګو ناکامي.',
    warning: 'د اوبو عدم توازن، د پښتورګو ناکامي.',
  },
  {
    id: '196',
    name: 'Docusate Sodium',
    generic: 'Docusate Sodium',
    category: 'Stool Softener',
    uses: 'د قبض د ځینو حالتونو لپاره.',
    forms: ['Capsule', 'Liquid'],
    side_effects: 'اسهال، cramp.',
    warning: 'اسهال، cramp.',
  },
  {
    id: '197',
    name: 'Senna',
    generic: 'Sennosides',
    category: 'Laxative',
    uses: 'د قبض د لنډمهاله درملنې لپاره.',
    forms: ['Tablet'],
    side_effects: 'cramp، اسهال.',
    warning: 'cramp، اسهال.',
  },
  {
    id: '198',
    name: 'Sacubitril + Valsartan',
    generic: 'Sacubitril + Valsartan',
    category: 'Heart / Antihypertensive',
    uses: 'د زړه د ناکامۍ درملنه (د زړه د ټیټ فعالیت سره).',
    forms: ['Tablet'],
    side_effects: 'د وینې ټیټ فشار، د پوتاشیم لوړوالی، ټوخی، سرګرداني، د پښتورګو ناکامي.',
    warning: 'د وینې ټیټ فشار، د پوتاشیم لوړوالی، د پښتورګو ناکامي.',
  },
  {
    id: '199',
    name: 'Hydralazine',
    generic: 'Hydralazine',
    category: 'Antihypertensive',
    uses: 'د لوړ فشار درملنه.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د زړه ګړندیتوب، سرخوږی، زړه بدوالی، د وینې ټیټ فشار.',
    warning: 'د زړه ګړندیتوب، سرخوږی، د وینې ټیټ فشار.',
  },
  {
    id: '200',
    name: 'Guanfacine',
    generic: 'Guanfacine',
    category: 'Antihypertensive',
    uses: 'د ADHD درملنه.',
    forms: ['Tablet'],
    side_effects: 'خوبجن، ستړیا، د وینې ټیټ فشار، سرخوږی.',
    warning: 'خوبجن، ستړیا، د وینې ټیټ فشار.',
  },
];
