// ==================== medicines5.js — پنځمه برخه ====================
export const medicines5 = [
  {
    id: '201',
    name: 'Guanabenz',
    generic: 'Guanabenz',
    category: 'Antihypertensive',
    uses: 'د لوړ فشار درملنه.',
    forms: ['Tablet'],
    side_effects: 'خوبجن، د خولې وچوالی، سرګرداني، د وینې ټیټ فشار.',
    warning: 'خوبجن، د خولې وچوالی، سرګردانی.',
  },
  {
    id: '202',
    name: 'Dipyridamole',
    generic: 'Dipyridamole',
    category: 'Antiplatelet',
    uses: 'د وینې د لخته کیدو مخنیوی (د سټروک وروسته).',
    forms: ['Tablet', 'Injection'],
    side_effects: 'سرخوږی، د معدې ناروغي، سرګرداني، اسهال.',
    warning: 'سرخوږی، د معدې ناروغي، سرګرداني.',
  },
  {
    id: '203',
    name: 'Betrixaban',
    generic: 'Betrixaban',
    category: 'Anticoagulant',
    uses: 'د وینې د لخته کیدو مخنیوی (د روغتون د بستر په وخت کې).',
    forms: ['Capsule'],
    side_effects: 'د وینې بهیدنه، سرخوږی، سرګرداني، ستړیا، د معدې ناروغي.',
    warning: 'د وینې بهیدنه، سرخوږی.',
  },
  {
    id: '204',
    name: 'Argatroban',
    generic: 'Argatroban',
    category: 'Anticoagulant',
    uses: 'د وینې د لخته کیدو مخنیوی (د HIT په صورت کې).',
    forms: ['Injection'],
    side_effects: 'د وینې بهیدنه، د وینې ټیټ فشار، د تنفس ستونزه.',
    warning: 'د وینې بهیدنه، د وینې ټیټ فشار.',
  },
  {
    id: '205',
    name: 'Bivalirudin',
    generic: 'Bivalirudin',
    category: 'Anticoagulant',
    uses: 'د وینې د لخته کیدو مخنیوی (د زړه د عملیاتو په وخت کې).',
    forms: ['Injection'],
    side_effects: 'د وینې بهیدنه، سرخوږی، د پلیټلیټ کمښت، تبه.',
    warning: 'د وینې بهیدنه، د پلیټلیټ کمښت.',
  },
  {
    id: '206',
    name: 'Tenecteplase',
    generic: 'Tenecteplase',
    category: 'Thrombolytic',
    uses: 'د وینې د لخته تحلیل (د myocardial infarction).',
    forms: ['Injection'],
    side_effects: 'د وینې بهیدنه، الرژي، د وینې ټیټ فشار.',
    warning: 'د وینې بهیدنه.',
  },
  {
    id: '207',
    name: 'Streptokinase',
    generic: 'Streptokinase',
    category: 'Thrombolytic',
    uses: 'د وینې د لخته تحلیل (د زړه حملې، د سږو embolism).',
    forms: ['Injection'],
    side_effects: 'د وینې بهیدنه، تبه، الرژي، د وینې ټیټ فشار.',
    warning: 'د وینې بهیدنه، د الرژي خطر.',
  },
  {
    id: '208',
    name: 'Urokinase',
    generic: 'Urokinase',
    category: 'Thrombolytic',
    uses: 'د وینې د لخته تحلیل (د سږو embolism).',
    forms: ['Injection'],
    side_effects: 'د وینې بهیدنه، الرژي، تبه.',
    warning: 'د وینې بهیدنه، الرژي.',
  },
  {
    id: '209',
    name: 'Recombinant Factor VIII',
    generic: 'Factor VIII',
    category: 'Coagulation Factor',
    uses: 'د هیموفیلیا A درملنه.',
    forms: ['Injection'],
    side_effects: 'سرخوږی، تبه، ټوخی، د معدې درد.',
    warning: 'د الرژي خطر، د inhibitor formation خطر.',
  },
  {
    id: '210',
    name: 'Factor IX',
    generic: 'Factor IX',
    category: 'Coagulation Factor',
    uses: 'د هیموفیلیا B درملنه.',
    forms: ['Injection'],
    side_effects: 'تبه، ټوخی، زړه بدوالی، د انجیکشن ځای غبرګونونه.',
    warning: 'د الرژي خطر، د inhibitor formation خطر.',
  },
  {
    id: '211',
    name: 'Factor VII',
    generic: 'Factor VII',
    category: 'Coagulation Factor',
    uses: 'د هیموفیلیا A یا B درملنه (د انهیبیټور سره).',
    forms: ['Injection'],
    side_effects: 'سرخوږی، سرګرداني، د انفوزیون ځای درد.',
    warning: 'د الرژي خطر، د thrombosis خطر.',
  },
  {
    id: '212',
    name: 'Factor XIII',
    generic: 'Factor XIII',
    category: 'Coagulation Factor',
    uses: 'د Factor XIII کمښت درملنه.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، الرژي.',
    warning: 'د الرژي خطر.',
  },
  {
    id: '213',
    name: 'Romiplostim',
    generic: 'Romiplostim',
    category: 'Hematology',
    uses: 'د immune thrombocytopenia (ITP) درملنه.',
    forms: ['Injection'],
    side_effects: 'د بندونو درد، سرګرداني، د وینې بهیدنه.',
    warning: 'د بندونو درد، د وینې بهیدنه.',
  },
  {
    id: '214',
    name: 'Eltrombopag',
    generic: 'Eltrombopag',
    category: 'Hematology',
    uses: 'د ITP درملنه.',
    forms: ['Tablet'],
    side_effects: 'د وینې کمښت (anemia)، زړه بدوالی، تبه، سرخوږی.',
    warning: 'د وینې د کمښت، زړه بدوالی، تبې.',
  },
  {
    id: '215',
    name: 'Epoetin Beta',
    generic: 'Epoetin Beta',
    category: 'Hematology',
    uses: 'د وینې د کمښت درملنه (د پښتورګو ناروغۍ، کیموتراپي).',
    forms: ['Injection'],
    side_effects: 'د وینې لوړ فشار، د وینې د لخته کیدو خطر، تبه.',
    warning: 'د وینې لوړ فشار، د وینې د لخته خطر.',
  },
  {
    id: '216',
    name: 'Darbepoetin Alfa',
    generic: 'Darbepoetin Alfa',
    category: 'Hematology',
    uses: 'د وینې د کمښت درملنه.',
    forms: ['Injection'],
    side_effects: 'د تنفس ستونزه، د پښو پړسوب، ټوخی، د وینې لوړ فشار.',
    warning: 'د وینې لوړ فشار، د وینې د لخته خطر.',
  },
  {
    id: '217',
    name: 'Pegfilgrastim',
    generic: 'Pegfilgrastim',
    category: 'Hematology',
    uses: 'د وینې د سپینو حجرو کمښت مخنیوی (د کیموتراپي وروسته).',
    forms: ['Injection'],
    side_effects: 'د هډوکو درد، تبه، ستړیا.',
    warning: 'د هډوکو درد، تبې، ستړیا.',
  },
  {
    id: '218',
    name: 'Interferon Beta-1a',
    generic: 'Interferon Beta-1a',
    category: 'Immunomodulator',
    uses: 'د multiple sclerosis (MS) درملنه.',
    forms: ['Injection'],
    side_effects: 'د انفلوانزا په څیر نښې (تبه، د عضلاتو درد).',
    warning: 'د انفلوانزا په څیر نښې.',
  },
  {
    id: '219',
    name: 'Interferon Beta-1b',
    generic: 'Interferon Beta-1b',
    category: 'Immunomodulator',
    uses: 'د MS درملنه.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انفلوانزا په څیر نښې.',
    warning: 'د انفلوانزا په څیر نښې.',
  },
  {
    id: '220',
    name: 'Interferon Alfa-2a',
    generic: 'Interferon Alfa-2a',
    category: 'Antiviral / Immunomodulator',
    uses: 'د هیپاتیت C، د وینې د سرطان درملنه.',
    forms: ['Injection'],
    side_effects: 'د انفلوانزا په څیر نښې، د وینې د سپینو حجرو کمښت، ستړیا.',
    warning: 'د انفلوانزا په څیر نښې، د وینې د حجرو کمښت.',
  },
  {
    id: '221',
    name: 'Interferon Alfa-2b',
    generic: 'Interferon Alfa-2b',
    category: 'Antiviral / Immunomodulator',
    uses: 'د هیپاتیت C، د سرطان درملنه.',
    forms: ['Injection'],
    side_effects: 'د انفلوانزا په څیر نښې، د وینې د سپینو حجرو کمښت، ستړیا.',
    warning: 'د انفلوانزا په څیر نښې، د وینې د حجرو کمښت.',
  },
  {
    id: '222',
    name: 'Sofosbuvir',
    generic: 'Sofosbuvir',
    category: 'Antiviral',
    uses: 'د هیپاتیت C درملنه.',
    forms: ['Tablet'],
    side_effects: 'ستړیا، سرخوږی، زړه بدوالی، د خوب ستونزې.',
    warning: 'د ځیګر زهرجنیت، د وینې د حجرو کمښت.',
  },
  {
    id: '223',
    name: 'Ledipasvir',
    generic: 'Ledipasvir',
    category: 'Antiviral',
    uses: 'د هیپاتیت C درملنه (د Sofosbuvir سره یوځای).',
    forms: ['Tablet'],
    side_effects: 'ستړیا، سرخوږی، د وینې کمښت (anemia).',
    warning: 'د ځیګر زهرجنیت، د وینې د حجرو کمښت.',
  },
  {
    id: '224',
    name: 'Velpatasvir',
    generic: 'Velpatasvir',
    category: 'Antiviral',
    uses: 'د هیپاتیت C درملنه (د Sofosbuvir سره یوځای).',
    forms: ['Tablet'],
    side_effects: 'سرخوږی، ستړیا.',
    warning: 'د ځیګر زهرجنیت، د وینې د حجرو کمښت.',
  },
  {
    id: '225',
    name: 'Glecaprevir + Pibrentasvir',
    generic: 'Glecaprevir + Pibrentasvir',
    category: 'Antiviral',
    uses: 'د هیپاتیت C درملنه.',
    forms: ['Tablet'],
    side_effects: 'سرخوږی، ستړیا، زړه بدوالی.',
    warning: 'د ځیګر زهرجنیت.',
  },
  {
    id: '226',
    name: 'Dolutegravir',
    generic: 'Dolutegravir sodium',
    category: 'Antiretroviral',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Tablet'],
    side_effects: 'د خوب ستونزې، سرخوږی، زړه بدوالی، ستړیا.',
    warning: 'د امیندوارۍ په لومړۍ درې میاشتنۍ کې د neural tube defects خطر.',
  },
  {
    id: '227',
    name: 'Efavirenz',
    generic: 'Efavirenz',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه.',
    forms: ['Tablet'],
    side_effects: 'سرګرداني، د خوب عجیب خوبونه، د پوټکي خارښت، زړه بدوالی.',
    warning: 'د CNS نښې (خوبونه، سرګردانی).',
  },
  {
    id: '228',
    name: 'Nevirapine',
    generic: 'Nevirapine',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه.',
    forms: ['Tablet', 'Oral Suspension'],
    side_effects: 'د پوټکي خطرناک غبرګونونه، د ځیګر زهرجنیت.',
    warning: 'د ځیګر زهرجنیت، د پوټکي خطرناک غبرګونونه.',
  },
  {
    id: '229',
    name: 'Rilpivirine',
    generic: 'Rilpivirine hydrochloride',
    category: 'Antiretroviral',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Tablet'],
    side_effects: 'د خوب ستونزې، د مزاج بدلون، سرخوږی، زړه بدوالی.',
    warning: 'د gastric pH لوړونکي درمل یې کچه کمولی شي.',
  },
  {
    id: '230',
    name: 'Emtricitabine',
    generic: 'Emtricitabine',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'سرخوږی، اسهال، زړه بدوالی، ستړیا، سرګرداني.',
    warning: 'د وینې د حجرو کمښت، د ځیګر زهرجنیت.',
  },
  {
    id: '231',
    name: 'Zidovudine',
    generic: 'Zidovudine',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه.',
    forms: ['Capsule', 'Tablet', 'Oral Solution'],
    side_effects: 'د وینې د حجرو کمښت، سرخوږی، زړه بدوالی، د عضلاتو درد.',
    warning: 'د وینې د حجرو کمښت، د عضلاتو درد.',
  },
  {
    id: '232',
    name: 'Stavudine',
    generic: 'Stavudine',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه.',
    forms: ['Capsule'],
    side_effects: 'د اعصابو درد (neuropathy)، سرخوږی، اسهال، د پوټکي خارښت.',
    warning: 'د اعصابو درد، د pancreatitis خطر.',
  },
  {
    id: '233',
    name: 'Didanosine',
    generic: 'Didanosine',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه.',
    forms: ['Capsule'],
    side_effects: 'د اعصابو درد، د پانکراس التهاب، اسهال، سرخوږی.',
    warning: 'د pancreatitis خطر، د اعصابو درد.',
  },
  {
    id: '234',
    name: 'Abacavir',
    generic: 'Abacavir sulfate',
    category: 'Antiretroviral',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'د hypersensitivity عکس‌العمل (تب، خارښت، د معدې ناروغي، د تنفس ستونزه).',
    warning: 'د HLA-B*5701 allele لپاره مخکې له درملنې ټیسټ اړین دی.',
  },
  {
    id: '235',
    name: 'Atazanavir',
    generic: 'Atazanavir sulfate',
    category: 'Antiretroviral',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Capsule'],
    side_effects: 'د بیلیروبین لوړوالی، د پوټکي ژېړوالی، زړه بدوالی، اسهال.',
    warning: 'د QT اوږدوالی او د ځیګر زهرجنیت.',
  },
  {
    id: '236',
    name: 'Darunavir',
    generic: 'Darunavir ethanolate',
    category: 'Antiretroviral',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Tablet'],
    side_effects: 'اسهال، زړه بدوالی، سرخوږی، د پوټکي خارښت.',
    warning: 'د پوټکي خطرناک عکس‌العملونه او د ځیګر زهرجنیت.',
  },
  {
    id: '237',
    name: 'Ritonavir',
    generic: 'Ritonavir',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه (د نورو درملو سره د مرستې لپاره).',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'زړه بدوالی، اسهال، د خولې وچوالی، د معدې درد.',
    warning: 'د معدې ناروغي، د خولې وچوالی.',
  },
  {
    id: '238',
    name: 'Lopinavir',
    generic: 'Lopinavir',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'اسهال، زړه بدوالی، د وینې د شکرې لوړوالی، د کولیسټرول لوړوالی.',
    warning: 'د وینې د شکرې لوړوالی، د کولیسټرول لوړوالی.',
  },
  {
    id: '239',
    name: 'Indinavir',
    generic: 'Indinavir',
    category: 'Antiretroviral',
    uses: 'د HIV درملنه.',
    forms: ['Capsule'],
    side_effects: 'د پښتورګو تیږې، د بیلیروبین لوړوالی، زړه بدوالی.',
    warning: 'د پښتورګو تیږې، د بیلیروبین لوړوالی.',
  },
  {
    id: '240',
    name: 'Maraviroc',
    generic: 'Maraviroc',
    category: 'Antiretroviral',
    uses: 'د HIV-1 انتاناتو درملنه، یوازې د CCR5-tropic virus لپاره.',
    forms: ['Tablet'],
    side_effects: 'د ځیګر زهرجنیت، د پوټکي خطرناک عکس‌العملونه، د زړه ischemic پیښې.',
    warning: 'د ځیګر زهرجنیت، د پوټکي خطرناک عکس‌العملونه.',
  },
  {
    id: '241',
    name: 'Raltegravir',
    generic: 'Raltegravir potassium',
    category: 'Antiretroviral',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Tablet', 'Chewable Tablet'],
    side_effects: 'د خوب ستونزې، سرخوږی، زړه بدوالی، ستړیا.',
    warning: 'د rifampin سره د دوز تنظیم اړین دی.',
  },
  {
    id: '242',
    name: 'Baloxavir',
    generic: 'Baloxavir marboxil',
    category: 'Antiviral',
    uses: 'د انفلوانزا درملنه.',
    forms: ['Tablet'],
    side_effects: 'اسهال، برونشیت، زړه بدوالی، سرخوږی.',
    warning: 'د نښو له پیل څخه د ۴۸ ساعتونو دننه استعمال.',
  },
  {
    id: '243',
    name: 'Molnupiravir',
    generic: 'Molnupiravir',
    category: 'Antiviral',
    uses: 'د COVID-19 درملنه.',
    forms: ['Capsule'],
    side_effects: 'اسهال، زړه بدوالی، سرګرداني.',
    warning: 'اسهال، زړه بدوالی.',
  },
  {
    id: '244',
    name: 'Remdesivir',
    generic: 'Remdesivir',
    category: 'Antiviral',
    uses: 'د COVID-19 درملنه.',
    forms: ['Injection'],
    side_effects: 'زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر انزایم لوړوالی.',
  },
  {
    id: '245',
    name: 'Favipiravir',
    generic: 'Favipiravir',
    category: 'Antiviral',
    uses: 'د انفلوانزا او COVID-19 درملنه.',
    forms: ['Tablet'],
    side_effects: 'د یوریک اسید لوړوالی، اسهال، د ځیګر انزایم لوړوالی.',
    warning: 'د یوریک اسید لوړوالی.',
  },
  {
    id: '246',
    name: 'Nitazoxanide',
    generic: 'Nitazoxanide',
    category: 'Antiparasitic',
    uses: 'د اسهال درملنه (Giardia، Cryptosporidium).',
    forms: ['Tablet', 'Oral Suspension'],
    side_effects: 'د معدې درد، سرخوږی، د ادرار رنګ بدلون، زړه بدوالی.',
    warning: 'د معدې ناروغي او د ادرار رنګ بدلون.',
  },
  {
    id: '247',
    name: 'Miltefosine',
    generic: 'Miltefosine',
    category: 'Antiparasitic',
    uses: 'د لیشمانیاسس درملنه.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، اسهال، د پښتورګو ستونزې.',
    warning: 'زړه بدوالی، اسهال.',
  },
  {
    id: '248',
    name: 'Suramin',
    generic: 'Suramin',
    category: 'Antiparasitic',
    uses: 'د افریقایي trypanosomiasis درملنه.',
    forms: ['Injection'],
    side_effects: 'د پښتورګو ناکامي، د پوټکي خارښت، د وینې ټیټ فشار.',
    warning: 'د پښتورګو ناکامي، د وینې ټیټ فشار.',
  },
  {
    id: '249',
    name: 'Melarsoprol',
    generic: 'Melarsoprol',
    category: 'Antiparasitic',
    uses: 'د افریقایي trypanosomiasis درملنه (د مغز مرحله).',
    forms: ['Injection'],
    side_effects: 'د مغز التهاب، د زړه ستونزې، د وینې بهیدنه.',
    warning: 'د مغز التهاب، د زړه ستونزې.',
  },
  {
    id: '250',
    name: 'Pentamidine',
    generic: 'Pentamidine',
    category: 'Antiparasitic',
    uses: 'د Pneumocystis pneumonia درملنه.',
    forms: ['Injection', 'Inhalation'],
    side_effects: 'د وینې ټیټ فشار، د پښتورګو ستونزې، د وینې د شکرې ټیټوالی.',
    warning: 'د وینې ټیټ فشار، د پښتورګو ستونزې.',
  },
];
