// ==================== medicines18.js — اتلسمه برخه ====================
export const medicines18 = [
  {
    id: '851',
    name: 'Imjudo (Tremelimumab)',
    generic: 'Tremelimumab',
    category: 'Monoclonal Antibody (CTLA-4 inhibitor)',
    uses: 'د Hepatocellular Carcinoma او NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا، د پوستکي خارښت.',
    warning: 'د immune-mediated غبرګونونه څارنه مهمه ده.',
  },
  {
    id: '852',
    name: 'Imfinzi + Imjudo',
    generic: 'Durvalumab + Tremelimumab',
    category: 'Monoclonal Antibody Combination',
    uses: 'د Hepatocellular Carcinoma او NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '853',
    name: 'Opdivo + Yervoy',
    generic: 'Nivolumab + Ipilimumab',
    category: 'Monoclonal Antibody Combination',
    uses: 'د Melanoma، NSCLC او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '854',
    name: 'Keytruda + Lenvima',
    generic: 'Pembrolizumab + Lenvatinib',
    category: 'Combination Therapy',
    uses: 'د Endometrial Carcinoma او Renal Cell Carcinoma لپاره.',
    forms: ['Injection + Oral capsule'],
    side_effects: 'د immune-mediated غبرګونونه، د وینې فشار لوړوالی، ستړیا.',
    warning: 'د immune-mediated غبرګونونه او د فشار څارنه.',
  },
  {
    id: '855',
    name: 'Braftovi (Encorafenib)',
    generic: 'Encorafenib',
    category: 'Antineoplastic (BRAF inhibitor)',
    uses: 'د Melanoma او Colorectal Cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د پوستکي خارښت، ستړیا، د بندونو درد.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '856',
    name: 'Mektovi (Binimetinib)',
    generic: 'Binimetinib',
    category: 'Antineoplastic (MEK inhibitor)',
    uses: 'د Melanoma او NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'ستړیا، د پوستکي خارښت، د زړه د فعالیت بدلون.',
    warning: 'د زړه او د سترګو څارنه.',
  },
  {
    id: '857',
    name: 'Tafinlar (Dabrafenib)',
    generic: 'Dabrafenib',
    category: 'Antineoplastic (BRAF inhibitor)',
    uses: 'د Melanoma، NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule', 'Oral tablet'],
    side_effects: 'د پوستکي خارښت، ستړیا، تبه.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '858',
    name: 'Mekinist (Trametinib)',
    generic: 'Trametinib',
    category: 'Antineoplastic (MEK inhibitor)',
    uses: 'د Melanoma، NSCLC او thyroid cancer لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، ستړیا، د زړه د فعالیت بدلون.',
    warning: 'د زړه او د سترګو څارنه.',
  },
  {
    id: '859',
    name: 'Zelboraf (Vemurafenib)',
    generic: 'Vemurafenib',
    category: 'Antineoplastic (BRAF inhibitor)',
    uses: 'د Melanoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، د بندونو درد، ستړیا.',
    warning: 'د پوستکي او د زړه څارنه.',
  },
  {
    id: '860',
    name: 'Cotellic (Cobimetinib)',
    generic: 'Cobimetinib',
    category: 'Antineoplastic (MEK inhibitor)',
    uses: 'د Melanoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د زړه د فعالیت بدلون.',
    warning: 'د زړه او د سترګو څارنه.',
  },
  {
    id: '861',
    name: 'Xalkori (Crizotinib)',
    generic: 'Crizotinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د لید ستونزې، زړه بدوالی، د پښو پړسوب.',
    warning: 'د لید او د زړه څارنه.',
  },
  {
    id: '862',
    name: 'Zykadia (Ceritinib)',
    generic: 'Ceritinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral capsule', 'Oral tablet'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر او د زړه څارنه.',
  },
  {
    id: '863',
    name: 'Alecensa (Alectinib)',
    generic: 'Alectinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'ستړیا، د پښو پړسوب، د پوټکي خارښت.',
    warning: 'د ځیګر او د ILD څارنه.',
  },
  {
    id: '864',
    name: 'Alunbrig (Brigatinib)',
    generic: 'Brigatinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د وینې لوړ فشار.',
    warning: 'د ILD او د فشار څارنه.',
  },
  {
    id: '865',
    name: 'Lorbrena (Lorlatinib)',
    generic: 'Lorlatinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د کولیسټرول لوړوالی، د پښو پړسوب، د مزاج بدلونونه.',
    warning: 'د CNS او د کولیسټرول څارنه.',
  },
  {
    id: '866',
    name: 'Rozlytrek (Entrectinib)',
    generic: 'Entrectinib',
    category: 'Antineoplastic (NTRK/ROS1 inhibitor)',
    uses: 'د NTRK-fusion tumors او ROS1-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'ستړیا، د وزن زیاتوالی، د مزاج بدلونونه.',
    warning: 'د CNS او د زړه څارنه.',
  },
  {
    id: '867',
    name: 'Vitrakvi (Larotrectinib)',
    generic: 'Larotrectinib',
    category: 'Antineoplastic (NTRK inhibitor)',
    uses: 'د NTRK-fusion tumors لپاره.',
    forms: ['Oral capsule', 'Oral solution'],
    side_effects: 'ستړیا، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر او د CNS څارنه.',
  },
  {
    id: '868',
    name: 'Retevmo (Selpercatinib)',
    generic: 'Selpercatinib',
    category: 'Antineoplastic (RET inhibitor)',
    uses: 'د RET-fusion NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې فشار لوړوالی، د QT اوږدوالی، ستړیا.',
    warning: 'د فشار او QT څارنه.',
  },
  {
    id: '869',
    name: 'Gavreto (Pralsetinib)',
    generic: 'Pralsetinib',
    category: 'Antineoplastic (RET inhibitor)',
    uses: 'د RET-fusion NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې فشار لوړوالی، ستړیا، د ځیګر انزایم لوړوالی.',
    warning: 'د فشار او د ځیګر څارنه.',
  },
  {
    id: '870',
    name: 'Tepmetko (Tepotinib)',
    generic: 'Tepotinib',
    category: 'Antineoplastic (MET inhibitor)',
    uses: 'د MET-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر څارنه.',
  },
  {
    id: '871',
    name: 'Tabrecta (Capmatinib)',
    generic: 'Capmatinib',
    category: 'Antineoplastic (MET inhibitor)',
    uses: 'د MET-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، زړه بدوالی، ستړیا.',
    warning: 'د ILD او د ځیګر څارنه.',
  },
  {
    id: '872',
    name: 'Exkivity (Mobocertinib)',
    generic: 'Mobocertinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR exon 20 insertion-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'اسهال، د پوستکي خارښت، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی څارنه.',
  },
  {
    id: '873',
    name: 'Rybrevant (Amivantamab)',
    generic: 'Amivantamab',
    category: 'Monoclonal Antibody (anti-EGFR/MET)',
    uses: 'د EGFR exon 20 insertion-positive NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د پوستکي خارښت، د وینې د لخته خطر.',
    warning: 'د انفوزیون غبرګونونه څارنه.',
  },
  {
    id: '874',
    name: 'Lazcluze (Lazertinib)',
    generic: 'Lazertinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، د وینې د لخته خطر، ستړیا.',
    warning: 'د وینې د لخته څارنه.',
  },
  {
    id: '875',
    name: 'Tagrisso (Osimertinib)',
    generic: 'Osimertinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی څارنه.',
  },
  {
    id: '876',
    name: 'Iressa (Gefitinib)',
    generic: 'Gefitinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، اسهال، د ځیګر انزایم لوړوالی.',
    warning: 'د ILD او د ځیګر څارنه.',
  },
  {
    id: '877',
    name: 'Tarceva (Erlotinib)',
    generic: 'Erlotinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د NSCLC او pancreatic cancer لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، اسهال، ستړیا.',
    warning: 'د ILD او د ځیګر څارنه.',
  },
  {
    id: '878',
    name: 'Gilotrif (Afatinib)',
    generic: 'Afatinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د خولې زخمونه.',
    warning: 'د اسهال او د پوستکي څارنه.',
  },
  {
    id: '879',
    name: 'Vizimpro (Dacomitinib)',
    generic: 'Dacomitinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د خولې زخمونه.',
    warning: 'د اسهال او د پوستکي څارنه.',
  },
  {
    id: '880',
    name: 'Nerlynx (Neratinib)',
    generic: 'Neratinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د اسهال څارنه مهمه ده.',
  },
  {
    id: '881',
    name: 'Tykerb (Lapatinib)',
    generic: 'Lapatinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د زړه د فعالیت بدلون.',
    warning: 'د زړه د فعالیت څارنه.',
  },
  {
    id: '882',
    name: 'Tukysa (Tucatinib)',
    generic: 'Tucatinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د لاسونو او پښو سندروم، د ځیګر انزایم لوړوالی.',
    warning: 'د اسهال او د ځیګر څارنه.',
  },
  {
    id: '883',
    name: 'Ibrance (Palbociclib)',
    generic: 'Palbociclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Oral capsule', 'Oral tablet'],
    side_effects: 'د وینې د حجرو کمښت، ستړیا، زړه بدوالی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '884',
    name: 'Kisqali (Ribociclib)',
    generic: 'Ribociclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د وینې د حجرو کمښت، د QT اوږدوالی، ستړیا.',
    warning: 'د QT اوږدوالی او د وینې د حجرو څارنه.',
  },
  {
    id: '885',
    name: 'Verzenio (Abemaciclib)',
    generic: 'Abemaciclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د اسهال او د وینې د حجرو څارنه.',
  },
  {
    id: '886',
    name: 'Lynparza (Olaparib)',
    generic: 'Olaparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer، سینې د سرطان او prostate cancer لپاره.',
    forms: ['Oral tablet', 'Oral capsule'],
    side_effects: 'زړه بدوالی، ستړیا، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '887',
    name: 'Rubraca (Rucaparib)',
    generic: 'Rucaparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer او prostate cancer لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، ستړیا، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '888',
    name: 'Zejula (Niraparib)',
    generic: 'Niraparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، ستړیا.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '889',
    name: 'Talzenna (Talazoparib)',
    generic: 'Talazoparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې د حجرو کمښت، ستړیا، سرخوږی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '890',
    name: 'Idhifa (Enasidenib)',
    generic: 'Enasidenib',
    category: 'Antineoplastic (IDH2 inhibitor)',
    uses: 'د AML لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د differentiation syndrome.',
    warning: 'د differentiation syndrome څارنه.',
  },
  {
    id: '891',
    name: 'Tibsovo (Ivosidenib)',
    generic: 'Ivosidenib',
    category: 'Antineoplastic (IDH1 inhibitor)',
    uses: 'د AML او cholangiocarcinoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د differentiation syndrome.',
    warning: 'د differentiation syndrome څارنه.',
  },
  {
    id: '892',
    name: 'Xospata (Gilteritinib)',
    generic: 'Gilteritinib',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-mutated AML لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د وینې د حجرو کمښت، اسهال، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی او د وینې د حجرو څارنه.',
  },
  {
    id: '893',
    name: 'Rydapt (Midostaurin)',
    generic: 'Midostaurin',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-mutated AML او Systemic Mastocytosis لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'زړه بدوالی، د وینې د حجرو کمښت، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی څارنه.',
  },
  {
    id: '894',
    name: 'Vanflyta (Quizartinib)',
    generic: 'Quizartinib',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-ITD positive AML لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د QT اوږدوالی، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د QT اوږدوالی څارنه مهمه ده.',
  },
  {
    id: '895',
    name: 'Turalio (Pexidartinib)',
    generic: 'Pexidartinib',
    category: 'Antineoplastic (CSF1R inhibitor)',
    uses: 'د Tenosynovial Giant Cell Tumor لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د ځیګر زهرجنیت، ستړیا، د پوستکي خارښت.',
    warning: 'د ځیګر زهرجنیت څارنه.',
  },
  {
    id: '896',
    name: 'Trodelvy (Sacituzumab Govitecan)',
    generic: 'Sacituzumab Govitecan',
    category: 'Antibody-Drug Conjugate',
    uses: 'د triple-negative سینې د سرطان او bladder cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د اسهال او د وینې د حجرو څارنه.',
  },
  {
    id: '897',
    name: 'Enhertu (Fam-Trastuzumab Deruxtecan)',
    generic: 'Fam-Trastuzumab Deruxtecan',
    category: 'Antibody-Drug Conjugate',
    uses: 'د HER2-positive سینې د سرطان، gastric cancer او NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د ILD خطر، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د ILD خطر څارنه مهمه ده.',
  },
  {
    id: '898',
    name: 'Padcev (Enfortumab Vedotin)',
    generic: 'Enfortumab Vedotin',
    category: 'Antibody-Drug Conjugate',
    uses: 'د Urothelial cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د پوستکي خارښت، د اعصابو درد، ستړیا.',
    warning: 'د پوستکي او د اعصابو څارنه.',
  },
  {
    id: '899',
    name: 'Tivdak (Tisotumab Vedotin)',
    generic: 'Tisotumab Vedotin',
    category: 'Antibody-Drug Conjugate',
    uses: 'د Cervical cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د سترګو ستونزې، د اعصابو درد، د وینې بهیدنه.',
    warning: 'د سترګو او د اعصابو څارنه.',
  },
  {
    id: '900',
    name: 'Blenrep (Belantamab Mafodotin)',
    generic: 'Belantamab Mafodotin',
    category: 'Antibody-Drug Conjugate',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Injection'],
    side_effects: 'د سترګو ستونزې، د وینې د حجرو کمښت.',
    warning: 'د سترګو څارنه مهمه ده.',
  },
];
