// ==================== medicines2.js — دوهمه برخه ====================
export const medicines2 = [
  {
    id: '51',
    name: 'Candesartan',
    generic: 'Candesartan',
    category: 'ARB',
    uses: 'د لوړ فشار لپاره کارېږي.',
    forms: ['Tablet'],
    side_effects: 'سرخوږی، سرګرداني او د تنفسي انتاناتو خطر.',
    warning: 'د پښتورګو فعالیت څارنه مهمه ده.',
  },
  {
    id: '52',
    name: 'Irbesartan',
    generic: 'Irbesartan',
    category: 'ARB',
    uses: 'د لوړ فشار او د شکرې ناروغۍ اړوند د پښتورګو ستونزو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې پوتاشیم لوړوالی، سرګرداني.',
    warning: 'د پوتاشیم کچه باید وڅارل شي.',
  },
  {
    id: '53',
    name: 'Telmisartan',
    generic: 'Telmisartan',
    category: 'ARB',
    uses: 'د لوړ فشار لپاره کارېږي.',
    forms: ['Tablet'],
    side_effects: 'د ملا درد، سینوسیت او اسهال.',
    warning: 'د فشار څارنه مهمه ده.',
  },
  {
    id: '54',
    name: 'Ramipril',
    generic: 'Ramipril',
    category: 'ACE inhibitor',
    uses: 'د لوړ فشار او د زړه د ځینو ستونزو لپاره.',
    forms: ['Capsule'],
    side_effects: 'سرخوږی، سرګرداني، ستړیا او ټوخی.',
    warning: 'د پښتورګو فعالیت څارنه مهمه ده.',
  },
  {
    id: '55',
    name: 'Torsemide',
    generic: 'Torsemide',
    category: 'Loop diuretic',
    uses: 'د پړسوب او د زړه ناکامۍ لپاره کارېږي.',
    forms: ['Tablet'],
    side_effects: 'ډېر ادرار، د اورېدو کمښت او د غوږونو زنګ.',
    warning: 'د الکترولایتونو څارنه اړینه ده.',
  },
  {
    id: '56',
    name: 'Amiloride',
    generic: 'Amiloride',
    category: 'Potassium-sparing diuretic',
    uses: 'د اضافي مایعاتو د کمولو او د پوتاشیم ساتلو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د پوتاشیم لوړوالی.',
    warning: 'د پوتاشیم څارنه ضروري ده.',
  },
  {
    id: '57',
    name: 'Nebivolol',
    generic: 'Nebivolol',
    category: 'Beta blocker',
    uses: 'د لوړ فشار او د زړه د دربې د ځینو حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرخوږی او ستړیا.',
    warning: 'د ناڅاپي بندولو څخه ډډه وکړئ.',
  },
  {
    id: '58',
    name: 'Dapagliflozin',
    generic: 'Dapagliflozin',
    category: 'SGLT2 inhibitor',
    uses: 'د ټایپ ۲ شکرې ناروغۍ او د زړه ناکامۍ لپاره.',
    forms: ['Tablet'],
    side_effects: 'د تناسلي سیمې انتانات، د ادرار انتانات.',
    warning: 'د ادرار څارنه اړینه ده.',
  },
  {
    id: '59',
    name: 'Cefotaxime',
    generic: 'Cefotaxime',
    category: 'Cephalosporin antibiotic',
    uses: 'د ځینو باکتریايي انتاناتو لپاره کارېږي.',
    forms: ['Injection'],
    side_effects: 'د وینې د سپینو حجرو کمښت او د انجیکشن ځای درد.',
    warning: 'د الرژي خطر.',
  },
  {
    id: '60',
    name: 'Minocycline',
    generic: 'Minocycline',
    category: 'Tetracycline antibiotic',
    uses: 'د اکې او ځینو باکتریايي انتاناتو لپاره.',
    forms: ['Capsule'],
    side_effects: 'سرخوږی، ستړیا، سرګرداني او د پوستکي توروالی.',
    warning: 'د لمر حساسیت مهم دی.',
  },
  {
    id: '61',
    name: 'Itraconazole',
    generic: 'Itraconazole',
    category: 'Antifungal',
    uses: 'د ځینو فنګسي انتاناتو لپاره کارېږي.',
    forms: ['Capsule', 'Oral Solution'],
    side_effects: 'زړه بدوالی، د پوستکي خارښت، د پښو پړسوب.',
    warning: 'د نورو درملو سره تعاملات لري.',
  },
  {
    id: '62',
    name: 'Diphenhydramine',
    generic: 'Diphenhydramine',
    category: 'Antihistamine',
    uses: 'د ځینو الرژیکو نښو او د خوب د ستونزو لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'خوبجنوالی، د خولې وچوالی، سرګرداني.',
    warning: 'د خوبولو له امله احتیاط مهم دی.',
  },
  {
    id: '63',
    name: 'Rabeprazole',
    generic: 'Rabeprazole',
    category: 'Proton pump inhibitor',
    uses: 'د معدې د تېزابیت د کمولو لپاره کارېږي.',
    forms: ['Tablet'],
    side_effects: 'د معدې درد، سرخوږی، اسهال او زړه بدوالی.',
    warning: 'د اوږدې مودې استعمال باید د څارنې لاندې وي.',
  },
  {
    id: '64',
    name: 'Ferrous Fumarate',
    generic: 'Ferrous Fumarate',
    category: 'Iron supplement',
    uses: 'د اوسپنې د کمښت او کمخونۍ لپاره کارېږي.',
    forms: ['Tablet'],
    side_effects: 'د معدې ستونزې، زړه بدوالی، قبضیت.',
    warning: 'له ماشومانو څخه یې لرې وساتئ.',
  },
  {
    id: '65',
    name: 'Ascorbic Acid',
    generic: 'Vitamin C',
    category: 'Vitamin',
    uses: 'د ویټامین C د کمښت لپاره کارېږي.',
    forms: ['Tablet', 'Powder'],
    side_effects: 'په لوړو مقدارونو کې اسهال او د پښتورګو د تیږو خطر.',
    warning: 'د اړتیا مطابق استعمال یې وټاکئ.',
  },
  {
    id: '66',
    name: 'Vitamin A',
    generic: 'Vitamin A',
    category: 'Vitamin',
    uses: 'د ویټامین A د کمښت لپاره کارېږي.',
    forms: ['Capsule'],
    side_effects: 'په لوړو مقدارونو کې سرخوږی، د پوستکي وچوالی.',
    warning: 'لوړ مقدارونه د امیندوارۍ په وخت کې خطرناک دي.',
  },
  {
    id: '67',
    name: 'Vitamin E',
    generic: 'Vitamin E',
    category: 'Vitamin',
    uses: 'د ویټامین E د کمښت لپاره کارېږي.',
    forms: ['Capsule'],
    side_effects: 'د معدې ستونزې، سرخوږی او د لید ستونزې.',
    warning: 'د دوز اندازه مهمه ده.',
  },
  {
    id: '68',
    name: 'Magnesium Oxide',
    generic: 'Magnesium Oxide',
    category: 'Mineral supplement',
    uses: 'د معدې د تېزابیت او قبضیت لپاره کارېږي.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د معدې درد، پړسوب او زړه بدوالی.',
    warning: 'د پښتورګو ناروغان دې له طبي مسلکي سره مشوره وکړي.',
  },
  {
    id: '69',
    name: 'Febuxostat',
    generic: 'Febuxostat',
    category: 'Antigout',
    uses: 'د Uric Acid د لوړوالي د ځینو حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د ځیګر د فعالیت ستونزې، زړه بدوالی.',
    warning: 'د ځیګر فعالیت څارنه مهمه ده.',
  },
  {
    id: '70',
    name: 'Promethazine',
    generic: 'Promethazine',
    category: 'Antihistamine',
    uses: 'د Allergic conditions او زړه بدوالي لپاره.',
    forms: ['Tablet', 'Syrup'],
    side_effects: 'خوبجنوالی، سرګرداني، د خولې وچوالی.',
    warning: 'د خوبولو له امله احتیاط مهم دی.',
  },
  {
    id: '71',
    name: 'Dicyclomine',
    generic: 'Dicyclomine',
    category: 'Antispasmodic',
    uses: 'د کولمو د Spasm او درد لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'سرګرداني، د خولې وچوالی، د لید ستونزې.',
    warning: 'د ځینو طبي حالتونو کې احتیاط.',
  },
  {
    id: '72',
    name: 'Hyoscine Butylbromide',
    generic: 'Hyoscine Butylbromide',
    category: 'Antispasmodic',
    uses: 'د معدې او کولمو د Spasm لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د خولې وچوالی، د زړه د دربې چټکتیا.',
    warning: 'د ادرار ستونزه کې احتیاط.',
  },
  {
    id: '73',
    name: 'Aluminium Hydroxide',
    generic: 'Aluminium Hydroxide',
    category: 'Antacid',
    uses: 'د معدې د تېزابیت او Heartburn لپاره.',
    forms: ['Suspension', 'Tablet'],
    side_effects: 'قبضیت، د معدې درد او د فاسفورس کمښت.',
    warning: 'د اوږدې مودې استعمال باید د څارنې لاندې وي.',
  },
  {
    id: '74',
    name: 'Calcium Gluconate',
    generic: 'Calcium Gluconate',
    category: 'Electrolyte',
    uses: 'د Calcium د کموالي په ځینو حالاتو کې.',
    forms: ['Injection', 'Tablet'],
    side_effects: 'د زړه د دربې ستونزې، د وینې ټیټ فشار.',
    warning: 'د روغتیايي مسلکي تر څارنې لاندې.',
  },
  {
    id: '75',
    name: 'Sodium Bicarbonate',
    generic: 'Sodium Bicarbonate',
    category: 'Antacid / Electrolyte',
    uses: 'د ځانګړو طبي حالاتو او Antacid استعمالونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د معدې درد، پړسوب، د وینې د فشار لوړوالی.',
    warning: 'د سودیم څارنه مهمه ده.',
  },
  {
    id: '76',
    name: 'Desmopressin',
    generic: 'Desmopressin',
    category: 'Hormone / Antidiuretic',
    uses: 'د ځینو ځانګړو هورموني او د ادرار اړوندو حالتونو لپاره.',
    forms: ['Tablet', 'Nasal Preparation'],
    side_effects: 'سرخوږی، زړه بدوالی او د اوبو د توازن ستونزې.',
    warning: 'د اوبو د توازن څارنه مهمه ده.',
  },
  {
    id: '77',
    name: 'Carbimazole',
    generic: 'Carbimazole',
    category: 'Antithyroid',
    uses: 'د Hyperthyroidism لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د سپینو حجرو کمښت، د پوستکي خارښت.',
    warning: 'د وینې معاینه اړینه ده.',
  },
  {
    id: '78',
    name: 'Desloratadine',
    generic: 'Desloratadine',
    category: 'Antihistamine',
    uses: 'د Allergic Rhinitis او Urticaria لپاره.',
    forms: ['Tablet', 'Syrup'],
    side_effects: 'ستړیا، د خولې وچوالی، سرخوږی.',
    warning: 'خوبجنوالی رامنځته کولی شي.',
  },
  {
    id: '79',
    name: 'Ketotifen',
    generic: 'Ketotifen',
    category: 'Antihistamine',
    uses: 'د Allergy او ځینو تنفسي حالتونو لپاره.',
    forms: ['Tablet', 'Syrup'],
    side_effects: 'خوبجنوالی، د خولې وچوالی او سرګرداني.',
    warning: 'د خوبولو له امله احتیاط.',
  },
  {
    id: '80',
    name: 'Tiotropium',
    generic: 'Tiotropium',
    category: 'Bronchodilator',
    uses: 'د COPD د ساتنې درملنې لپاره.',
    forms: ['Inhalation'],
    side_effects: 'د ادرار ستونزې، د سترګو د فشار ستونزې.',
    warning: 'د تنفسي ستونزې په صورت کې طبي مرسته.',
  },
  {
    id: '81',
    name: 'Formoterol',
    generic: 'Formoterol',
    category: 'Bronchodilator',
    uses: 'د Asthma او COPD په ځینو درملنیزو رژیمونو کې.',
    forms: ['Inhaler'],
    side_effects: 'د زړه د دربې چټکتیا، د لاسونو رعشه.',
    warning: 'د دوز اندازه مهمه ده.',
  },
  {
    id: '82',
    name: 'Salmeterol',
    generic: 'Salmeterol',
    category: 'Bronchodilator',
    uses: 'د Asthma او COPD د ساتنې لپاره.',
    forms: ['Inhaler'],
    side_effects: 'سرخوږی، د پوزې بندښت، د ستوني خارښت.',
    warning: 'د ساتنې درمل دی، د حاد حملې لپاره نه.',
  },
  {
    id: '83',
    name: 'Ampicillin',
    generic: 'Ampicillin',
    category: 'Antibiotic',
    uses: 'د ځینو باکتریايي انتاناتو لپاره.',
    forms: ['Capsule', 'Injection'],
    side_effects: 'د پوستکي خارښت، زړه بدوالی، اسهال.',
    warning: 'د الرژي خطر.',
  },
  {
    id: '84',
    name: 'Phenoxymethylpenicillin',
    generic: 'Penicillin V',
    category: 'Penicillin Antibiotic',
    uses: 'د ځینو باکتریايي انتاناتو لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'زړه بدوالی، اسهال، د معدې ستونزې.',
    warning: 'د penicillin حساسیت کې احتیاط.',
  },
  {
    id: '85',
    name: 'Imipenem/Cilastatin',
    generic: 'Imipenem + Cilastatin',
    category: 'Carbapenem Antibiotic',
    uses: 'د ځینو شدیدو باکتریايي انتاناتو لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای التهاب، زړه بدوالی، اسهال.',
    warning: 'د تشنج خطر.',
  },
  {
    id: '86',
    name: 'Griseofulvin',
    generic: 'Griseofulvin',
    category: 'Antifungal',
    uses: 'د ځینو پوستکي او نوکانو فنګسي انتاناتو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د معدې ستونزې، سرخوږی او د پوستکي خارښت.',
    warning: 'د اوږدې مودې استعمال ته اړتیا لري.',
  },
  {
    id: '87',
    name: 'Fusidic Acid',
    generic: 'Fusidic Acid',
    category: 'Topical Antibiotic',
    uses: 'د پوستکي د ځینو باکتریايي انتاناتو لپاره.',
    forms: ['Cream', 'Ointment'],
    side_effects: 'د معدې ستونزې، اسهال، د پوستکي خارښت.',
    warning: 'د پوستکي د انتاناتو لپاره.',
  },
  {
    id: '88',
    name: 'Nifuroxazide',
    generic: 'Nifuroxazide',
    category: 'Gastrointestinal',
    uses: 'د ځینو حادې نس ناستې حالتونو کې کارول کېږي.',
    forms: ['Capsule', 'Suspension'],
    side_effects: 'د معدې درد، زړه بدوالی، سرګرداني.',
    warning: 'د نس ناستې لپاره.',
  },
  {
    id: '89',
    name: 'Racecadotril',
    generic: 'Racecadotril',
    category: 'Antidiarrheal',
    uses: 'د حادې نس ناستې په ځینو حالتونو کې.',
    forms: ['Capsule', 'Sachet'],
    side_effects: 'د پوستکي جدي تعاملات او الرژي.',
    warning: 'د ماشومانو لپاره ځانګړی احتیاط.',
  },
  {
    id: '90',
    name: 'Ursodeoxycholic Acid',
    generic: 'Ursodeoxycholic Acid',
    category: 'Hepatobiliary',
    uses: 'د ځینو صفراوي او ځیګر اړوندو حالتونو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې درد، اسهال، زړه بدوالی.',
    warning: 'د ځیګر فعالیت څارنه مهمه ده.',
  },
  {
    id: '91',
    name: 'Silymarin',
    generic: 'Silymarin',
    category: 'Hepatoprotective',
    uses: 'د ځینو ځیګر اړوندو محصولاتو کې کارول کېږي.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې ستونزې، زړه بدوالی او اسهال.',
    warning: 'د ځیګر لپاره مرستیال.',
  },
  {
    id: '92',
    name: 'Phenazopyridine',
    generic: 'Phenazopyridine',
    category: 'Urinary Analgesic',
    uses: 'د ادرار د لارې د درد نښو د لنډمهاله کمولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د ادرار رنګ بدلېدل، د معدې ناراحتي.',
    warning: 'د اوږدې مودې لپاره نه.',
  },
  {
    id: '93',
    name: 'Sildenafil',
    generic: 'Sildenafil',
    category: 'PDE5 Inhibitor',
    uses: 'د ځینو طبي حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرخوږی، د مخ سوروالی، د معدې ناراحتي.',
    warning: 'د نیترات درملو سره مه استعمالوئ.',
  },
  {
    id: '94',
    name: 'Doxazosin',
    generic: 'Doxazosin',
    category: 'Antihypertensive / Urological',
    uses: 'د لوړ فشار او BPH په ځینو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'سرګرداني، سرخوږی، د وینې ټیټ فشار.',
    warning: 'د لومړنیو doses پر مهال سر ګرځېدل.',
  },
  {
    id: '95',
    name: 'Terazosin',
    generic: 'Terazosin',
    category: 'Antihypertensive / Urological',
    uses: 'د لوړ فشار او BPH په ځینو حالتونو کې.',
    forms: ['Capsule'],
    side_effects: 'سرګرداني، ستړیا، د پوزې بندښت.',
    warning: 'د لومړنیو doses پر مهال احتیاط.',
  },
  {
    id: '96',
    name: 'Methotrexate',
    generic: 'Methotrexate',
    category: 'Antimetabolite',
    uses: 'د ځینو Autoimmune ناروغیو او ځانګړو سرطانونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د خولې زخمونه، زړه بدوالی، د ځیګر زیان.',
    warning: 'د متخصص تر څارنې لاندې.',
  },
  {
    id: '97',
    name: 'Azathioprine',
    generic: 'Azathioprine',
    category: 'Immunosuppressant',
    uses: 'د ځینو Autoimmune حالتونو او د Organ Transplant په ځانګړو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'د وینې د حجرو کمښت، د انتاناتو خطر.',
    warning: 'د وینې معاینه اړینه ده.',
  },
  {
    id: '98',
    name: 'Cyclosporine',
    generic: 'Cyclosporine',
    category: 'Immunosuppressant',
    uses: 'د Organ Transplant او ځینو ځانګړو معافیتي ناروغیو لپاره.',
    forms: ['Capsule', 'Oral Solution'],
    side_effects: 'د وینې لوړ فشار، د پښتورګو ستونزې.',
    warning: 'د پښتورګو څارنه ضروري ده.',
  },
  {
    id: '99',
    name: 'Tacrolimus',
    generic: 'Tacrolimus',
    category: 'Immunosuppressant',
    uses: 'د Organ Transplant او ځینو ځانګړو پوستکي حالتونو لپاره.',
    forms: ['Capsule', 'Ointment'],
    side_effects: 'د پښتورګو د فعالیت بدلون، د وینې لوړ فشار.',
    warning: 'د پښتورګو څارنه مهمه ده.',
  },
  {
    id: '100',
    name: 'Hydroxychloroquine',
    generic: 'Hydroxychloroquine',
    category: 'Antimalarial / Immunomodulator',
    uses: 'د Malaria او ځینو Autoimmune ناروغیو لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، اسهال، د سترګو ستونزې.',
    warning: 'د سترګو معاینه اړینه ده.',
  },
];
