// ==================== medicines3.js — دریمه برخه ====================
export const medicines3 = [
  {
    id: '101',
    name: 'Sulfasalazine',
    generic: 'Sulfasalazine',
    category: 'Anti-inflammatory',
    uses: 'د ځینو کولمو التهابي ناروغیو او Rheumatoid Arthritis لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، د معدې ناراحتي، د پوستکي خارښت.',
    warning: 'د وینې د حجرو معاینه اړینه ده.',
  },
  {
    id: '102',
    name: 'Mesalamine',
    generic: 'Mesalamine',
    category: 'Aminosalicylate',
    uses: 'د Ulcerative Colitis د ځینو حالتونو لپاره.',
    forms: ['Tablet', 'Rectal Preparation'],
    side_effects: 'اسهال، زړه بدوالی، د معدې درد.',
    warning: 'د پښتورګو فعالیت څارنه مهمه ده.',
  },
  {
    id: '103',
    name: 'Filgrastim',
    generic: 'Filgrastim',
    category: 'Hematologic',
    uses: 'د Neutrophil د کموالي په ځینو حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'د هډوکو درد، تبه، ستړیا.',
    warning: 'د روغتیايي مسلکي تر څارنې لاندې.',
  },
  {
    id: '104',
    name: 'Epoetin Alfa',
    generic: 'Epoetin Alfa',
    category: 'Hematologic',
    uses: 'د ځینو ډولونو انیمیا لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې لوړ فشار، د وینې د لخته کېدو خطر.',
    warning: 'د وینې فشار څارنه مهمه ده.',
  },
  {
    id: '105',
    name: 'Pregabalin',
    generic: 'Pregabalin',
    category: 'Neuropathic Pain',
    uses: 'د ځینو عصبي دردونو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'خوبجن، سرګردانی، د وزن زیاتوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '106',
    name: 'Gabapentin',
    generic: 'Gabapentin',
    category: 'Antiepileptic / Neuropathic Pain',
    uses: 'د ځینو Seizures او عصبي دردونو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'خوبولي، سرګرځېدل، ستړیا.',
    warning: 'د ناڅاپي بندولو په اړه طبي مشوره.',
  },
  {
    id: '107',
    name: 'Escitalopram',
    generic: 'Escitalopram',
    category: 'Antidepressant',
    uses: 'د Depression او Anxiety لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، د خوب ستونزې، جنسي ستونزې.',
    warning: 'د ځان وژنې فکر خطر په ځوانانو کې.',
  },
  {
    id: '108',
    name: 'Paroxetine',
    generic: 'Paroxetine',
    category: 'Antidepressant',
    uses: 'د Depression او ځینو اضطرابي اختلالاتو لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، خوبجن، جنسي ستونزې.',
    warning: 'د امیندوارۍ په لومړۍ درې میاشتو کې احتیاط.',
  },
  {
    id: '109',
    name: 'Venlafaxine',
    generic: 'Venlafaxine',
    category: 'Antidepressant',
    uses: 'د Depression او ځینو اضطرابي اختلالاتو لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'زړه بدوالی، د خولې وچوالی، سرګردانی.',
    warning: 'د وینې فشار څارنه مهمه ده.',
  },
  {
    id: '110',
    name: 'Duloxetine',
    generic: 'Duloxetine',
    category: 'Antidepressant',
    uses: 'د Depression او ځینو عصبي دردونو لپاره.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، د خولې وچوالی، ستړیا.',
    warning: 'د ځیګر زیان د الکول سره.',
  },
  {
    id: '111',
    name: 'Mirtazapine',
    generic: 'Mirtazapine',
    category: 'Antidepressant',
    uses: 'د Depression لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبجن، د وزن زیاتوالی، د خولې وچوالی.',
    warning: 'د ځان وژنې فکر خطر.',
  },
  {
    id: '112',
    name: 'Trazodone',
    generic: 'Trazodone',
    category: 'Antidepressant',
    uses: 'د Depression لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبجن، سرګردانی، د خولې وچوالی.',
    warning: 'د زړه د دربې ستونزې.',
  },
  {
    id: '113',
    name: 'Clonazepam',
    generic: 'Clonazepam',
    category: 'Antiepileptic',
    uses: 'د ځینو Seizure او اضطرابي حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبجن، سرګردانی، روږديتوب.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '114',
    name: 'Lorazepam',
    generic: 'Lorazepam',
    category: 'Benzodiazepine',
    uses: 'د ځینو اضطرابي او بیړنیو Seizure حالتونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبجن، سرګردانی، روږديتوب.',
    warning: 'د روږديتوب خطر.',
  },
  {
    id: '115',
    name: 'Midazolam',
    generic: 'Midazolam',
    category: 'Benzodiazepine',
    uses: 'په روغتون کې د Sedation او ځینو بیړنیو حالتونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د تنفس ټیټوالی، د وینې ټیټ فشار.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '116',
    name: 'Risperidone',
    generic: 'Risperidone',
    category: 'Antipsychotic',
    uses: 'د ځینو رواني اختلالاتو لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'د وزن زیاتوالی، خوبجن، د وینې د شکرې لوړوالی.',
    warning: 'د ځوانانو په صورت کې احتیاط.',
  },
  {
    id: '117',
    name: 'Olanzapine',
    generic: 'Olanzapine',
    category: 'Antipsychotic',
    uses: 'د ځینو رواني اختلالاتو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وزن زیاتوالی، خوبجن، د شکرې لوړوالی.',
    warning: 'د وزن او شکرې څارنه مهمه ده.',
  },
  {
    id: '118',
    name: 'Quetiapine',
    generic: 'Quetiapine',
    category: 'Antipsychotic',
    uses: 'د ځینو رواني اختلالاتو لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبجن، سرګردانی، د خولې وچوالی.',
    warning: 'د وزن زیاتوالی او د شکرې څارنه.',
  },
  {
    id: '119',
    name: 'Aripiprazole',
    generic: 'Aripiprazole',
    category: 'Antipsychotic',
    uses: 'د ځینو رواني اختلالاتو لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'اضطراب، د خوب ستونزې، سرخوږی.',
    warning: 'د ځوانانو په صورت کې احتیاط.',
  },
  {
    id: '120',
    name: 'Chlorpromazine',
    generic: 'Chlorpromazine',
    category: 'Antipsychotic',
    uses: 'د ځینو رواني اختلالاتو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبجن، د وینې ټیټ فشار، د خولې وچوالی.',
    warning: 'د NMS خطر.',
  },
  {
    id: '121',
    name: 'Buspirone',
    generic: 'Buspirone',
    category: 'Anxiolytic',
    uses: 'د ځینو اضطرابي اختلالاتو لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرګردانی، سرخوږی، زړه بدوالی.',
    warning: 'د serotonin syndrome خطر.',
  },
  {
    id: '122',
    name: 'Propranolol',
    generic: 'Propranolol',
    category: 'Beta Blocker',
    uses: 'د لوړ فشار او ځینو قلبي حالتونو لپاره.',
    forms: ['Tablet', 'Capsule', 'Oral Solution'],
    side_effects: 'د زړه ضربان کمېدل، ستړیا، سرګرځېدل.',
    warning: 'د ناڅاپي بندولو څخه ډډه وکړئ.',
  },
  {
    id: '123',
    name: 'Metoprolol',
    generic: 'Metoprolol',
    category: 'Beta blocker',
    uses: 'د لوړ فشار، انجینا او د زړه ناکامۍ په ځینو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'ستړیا، سرګرځېدل، د زړه ورووالی.',
    warning: 'د ناڅاپي بندولو څخه ډډه وکړئ.',
  },
  {
    id: '124',
    name: 'Carvedilol',
    generic: 'Carvedilol',
    category: 'Beta blocker',
    uses: 'د لوړ فشار او د زړه ناکامۍ د درملنې لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرګرځېدل، ستړیا، د وینې فشار ټیټوالی.',
    warning: 'د فشار او د زړه ضربان څارنه.',
  },
  {
    id: '125',
    name: 'Eplerenone',
    generic: 'Eplerenone',
    category: 'Diuretic',
    uses: 'د لوړ فشار او د زړه د ځینو حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د پوتاشیم لوړوالی، سرګرداني.',
    warning: 'د پوتاشیم څارنه مهمه ده.',
  },
  {
    id: '126',
    name: 'Ticagrelor',
    generic: 'Ticagrelor',
    category: 'Antiplatelet',
    uses: 'د وینې د لخته کېدو د مخنیوي لپاره په ځانګړو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'د وینې بهېدنه، د تنفس ستونزه، سرخوږی.',
    warning: 'د وینې بهېدلو په صورت کې طبي ارزونه.',
  },
  {
    id: '127',
    name: 'Enoxaparin',
    generic: 'Enoxaparin',
    category: 'Anticoagulant',
    uses: 'د وینې د ټوټو د مخنیوي او درملنې په ځینو حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'د وینې بهېدنه، د انجیکشن ځای درد.',
    warning: 'د پښتورګو فعالیت څارنه.',
  },
  {
    id: '128',
    name: 'Dabigatran',
    generic: 'Dabigatran',
    category: 'Anticoagulant',
    uses: 'د وینې د ټوټې کېدو د مخنیوي لپاره په ځینو حالتونو کې.',
    forms: ['Capsule'],
    side_effects: 'د وینې بهېدنه، زړه بدوالی.',
    warning: 'د bleeding خطر له امله څارنه.',
  },
  {
    id: '129',
    name: 'Apixaban',
    generic: 'Apixaban',
    category: 'Anticoagulant',
    uses: 'د وینې د لخته کېدو د مخنیوي لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې بهېدنه، زړه بدوالی، د پوستکي خارښت.',
    warning: 'د وینې بهېدنې نښې باید جدي ونیول شي.',
  },
  {
    id: '130',
    name: 'Rivaroxaban',
    generic: 'Rivaroxaban',
    category: 'Anticoagulant',
    uses: 'د وینې د لخته کېدو د مخنیوي او درملنې لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې بهېدنه، سرخوږی.',
    warning: 'د bleeding خطر له امله څارنه.',
  },
  {
    id: '131',
    name: 'Pravastatin',
    generic: 'Pravastatin',
    category: 'Statin',
    uses: 'د وینې د لوړ Cholesterol لپاره.',
    forms: ['Tablet'],
    side_effects: 'د عضلاتو درد، سرخوږی، د معدې نارامي.',
    warning: 'د عضلاتي نښو څارنه.',
  },
  {
    id: '132',
    name: 'Fluvastatin',
    generic: 'Fluvastatin',
    category: 'Statin',
    uses: 'د وینې د لوړ Cholesterol لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د عضلاتو درد، سرخوږی، زړه بدوالی.',
    warning: 'د ځیګر څارنه مهمه ده.',
  },
  {
    id: '133',
    name: 'Fenofibrate',
    generic: 'Fenofibrate',
    category: 'Lipid Lowering',
    uses: 'د لوړ Triglycerides لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د معدې نارامي، د عضلاتو درد.',
    warning: 'د ځیګر او پښتورګو څارنه.',
  },
  {
    id: '134',
    name: 'Ezetimibe',
    generic: 'Ezetimibe',
    category: 'Lipid Lowering',
    uses: 'د وینې د Cholesterol د کمولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د معدې نارامي، سرخوږی، ستړیا.',
    warning: 'د ځیګر څارنه.',
  },
  {
    id: '135',
    name: 'Levocetirizine',
    generic: 'Levocetirizine',
    category: 'Antihistamine',
    uses: 'د Allergy نښو لپاره.',
    forms: ['Tablet', 'Syrup'],
    side_effects: 'خوبولي، د خولې وچوالی، سرخوږی.',
    warning: 'خوبولي رامنځته کولی شي.',
  },
  {
    id: '136',
    name: 'Fexofenadine',
    generic: 'Fexofenadine',
    category: 'Antihistamine',
    uses: 'د الرژۍ د ځینو نښو لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرخوږی، زړه بدوالی، ستړیا.',
    warning: 'د antacids سره واټن مهم دی.',
  },
  {
    id: '137',
    name: 'Budesonide',
    generic: 'Budesonide',
    category: 'Corticosteroid',
    uses: 'د Asthma او ځینو التهابي کولمي ناروغیو لپاره.',
    forms: ['Inhaler', 'Capsule'],
    side_effects: 'د خولې وچوالی، د غږ بدلون.',
    warning: 'د اوږدې مودې استعمال څارنه.',
  },
  {
    id: '138',
    name: 'Fluticasone',
    generic: 'Fluticasone',
    category: 'Corticosteroid',
    uses: 'د Allergic Rhinitis او ځینو تنفسي حالتونو لپاره.',
    forms: ['Nasal Spray', 'Inhaler'],
    side_effects: 'د خولې وچوالی، د غږ بدلون، سرخوږی.',
    warning: 'د استعمال لارښوونې توپیر لري.',
  },
  {
    id: '139',
    name: 'Ipratropium',
    generic: 'Ipratropium',
    category: 'Bronchodilator',
    uses: 'د COPD او د تنفسي لارو د ځینو حالتونو لپاره.',
    forms: ['Inhaler', 'Nebulizer Solution'],
    side_effects: 'د خولې وچوالی، د سترګو د فشار ستونزې.',
    warning: 'د تنفس د شدیدې ستونزې په صورت کې بیړنۍ مرسته.',
  },
  {
    id: '140',
    name: 'Theophylline',
    generic: 'Theophylline',
    category: 'Bronchodilator',
    uses: 'د آسم او COPD په ځینو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، سرخوږی، د زړه چټک درزا.',
    warning: 'د درملو کچه څارنه.',
  },
  {
    id: '141',
    name: 'Ambroxol',
    generic: 'Ambroxol',
    category: 'Mucolytic',
    uses: 'د غلیظ بلغم د کمولو لپاره.',
    forms: ['Syrup', 'Tablet'],
    side_effects: 'زړه بدوالی، د معدې نارامي.',
    warning: 'د تنفس دوامداره ستونزې طبي ارزونې ته اړتیا لري.',
  },
  {
    id: '142',
    name: 'Acetylcysteine',
    generic: 'Acetylcysteine',
    category: 'Mucolytic',
    uses: 'د غلیظ بلغم په ځینو تنفسي حالتونو کې.',
    forms: ['Tablet', 'Solution'],
    side_effects: 'زړه بدوالی، اسهال، الرژیک غبرګون.',
    warning: 'د poisoning په حالت کې عاجله مرسته.',
  },
  {
    id: '143',
    name: 'Bromhexine',
    generic: 'Bromhexine',
    category: 'Mucolytic',
    uses: 'د غلیظ بلغم د کمولو لپاره.',
    forms: ['Syrup', 'Tablet'],
    side_effects: 'nausea، abdominal discomfort، rash.',
    warning: 'د اوږدې مودې cough لپاره طبي ارزونه.',
  },
  {
    id: '144',
    name: 'Xylometazoline',
    generic: 'Xylometazoline',
    category: 'Nasal Decongestant',
    uses: 'د پزې بندښت د لنډمهاله کمولو لپاره.',
    forms: ['Nasal Spray', 'Nasal Drops'],
    side_effects: 'د پزې وچوالی، irritation، rebound congestion.',
    warning: 'د اوږدې مودې استعمال مناسب نه دی.',
  },
  {
    id: '145',
    name: 'Oxymetazoline',
    generic: 'Oxymetazoline',
    category: 'Nasal Decongestant',
    uses: 'د پزې د بندښت د لنډمهاله کمولو لپاره.',
    forms: ['Nasal Spray', 'Nasal Drops'],
    side_effects: 'د پزې dryness، irritation او rebound congestion.',
    warning: 'د اوږدې مودې استعمال د rebound congestion سبب.',
  },
  {
    id: '146',
    name: 'Ketorolac',
    generic: 'Ketorolac',
    category: 'NSAID',
    uses: 'د لنډمهاله متوسط تر شدید درد لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د معدې irritation، bleeding او kidney-related عوارض.',
    warning: 'د استعمال موده محدودېږي.',
  },
  {
    id: '147',
    name: 'Meloxicam',
    generic: 'Meloxicam',
    category: 'NSAID',
    uses: 'د ځینو musculoskeletal او inflammatory دردونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د معدې نارامي، bleeding او kidney-related عوارض.',
    warning: 'د NSAID خطرونو له امله طبي مشوره.',
  },
  {
    id: '148',
    name: 'Naproxen',
    generic: 'Naproxen',
    category: 'NSAID',
    uses: 'د درد او التهاب د ځینو حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د معدې نارامي، heartburn او bleeding خطر.',
    warning: 'د اوږدې مودې استعمال طبي ارزونې ته اړتیا.',
  },
  {
    id: '149',
    name: 'Celecoxib',
    generic: 'Celecoxib',
    category: 'NSAID',
    uses: 'د ځینو دردناکو او inflammatory joint حالتونو لپاره.',
    forms: ['Capsule'],
    side_effects: 'د معدې نارامي، edema او cardiovascular خطرونه.',
    warning: 'د cardiovascular خطرونو ارزونه مهمه ده.',
  },
  {
    id: '150',
    name: 'Mefenamic Acid',
    generic: 'Mefenamic Acid',
    category: 'NSAID',
    uses: 'د درد د ځینو حالتونو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې نارامي، diarrhea او bleeding.',
    warning: 'د استعمال موده باید محدوده وي.',
  },
];
