// ==================== medicines1.js — لومړی برخه ====================
export const medicines1 = [
  {
    id: '1',
    name: 'Paracetamol',
    generic: 'Acetaminophen',
    category: 'Analgesic / Antipyretic',
    uses: 'د درد او تبې د کمولو لپاره.',
    forms: ['Tablet', 'Syrup', 'Suppository', 'Injection'],
    side_effects: 'عموماً لږ عوارض؛ د ډېر استعمال له امله د ځیګر جدي زیان رامنځته کېدای شي.',
    warning: 'د څو داسې محصولاتو یوځای استعمال مه کوئ چې Paracetamol پکې شامل وي.',
  },
  {
    id: '2',
    name: 'Amoxicillin',
    generic: 'Amoxicillin',
    category: 'Antibiotic',
    uses: 'د ځینو باکتریايي انتاناتو د درملنې لپاره کارېږي.',
    forms: ['Capsule', 'Tablet', 'Oral Suspension'],
    side_effects: 'نس ناستی، زړه بدوالی او د پوستکي حساسیت رامنځته کولی شي.',
    warning: 'د ویروسي ناروغیو لپاره نه کارېږي.',
  },
  {
    id: '3',
    name: 'Ibuprofen',
    generic: 'Ibuprofen',
    category: 'NSAID',
    uses: 'د درد، التهاب او تبې د کمولو لپاره.',
    forms: ['Tablet', 'Capsule', 'Suspension', 'Gel'],
    side_effects: 'د معدې درد، زړه بدوالی، د معدې وینه بهېدل.',
    warning: 'د اوږدې مودې استعمال باید د طبي مشورې له مخې وي.',
  },
  {
    id: '4',
    name: 'Aspirin',
    generic: 'Acetylsalicylic Acid',
    category: 'Antiplatelet / NSAID',
    uses: 'په ځانګړو قلبي حالتونو کې د Antiplatelet په توګه او د درد لپاره.',
    forms: ['Tablet', 'Chewable Tablet'],
    side_effects: 'د معدې irritation، وینه بهېدل، زړه بدوالی.',
    warning: 'په ماشومانو او تنکیو ځوانانو کې باید یوازې د روغتیايي مسلکي په مشوره وي.',
  },
  {
    id: '5',
    name: 'Metformin',
    generic: 'Metformin',
    category: 'Antidiabetic',
    uses: 'د Type 2 diabetes د درملنې په پروګرام کې کارېږي.',
    forms: ['Tablet'],
    side_effects: 'د معدې ناارامي، زړه بدوالی او نس ناستی.',
    warning: 'د استعمال اندازه باید د روغتیايي مسلکي له سپارښتنې سره وي.',
  },
  {
    id: '6',
    name: 'Cetirizine',
    generic: 'Cetirizine',
    category: 'Antihistamine',
    uses: 'د Allergies، Allergic rhinitis او Urticaria لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'خوبولي، ستړیا، د خولې وچوالی.',
    warning: 'که خوبولي رامنځته کوي، احتیاط مهم دی.',
  },
  {
    id: '7',
    name: 'Omeprazole',
    generic: 'Omeprazole',
    category: 'Proton Pump Inhibitor',
    uses: 'د GERD، Heartburn او ځینو Ulcer حالتونو لپاره.',
    forms: ['Capsule', 'Tablet', 'Oral Suspension'],
    side_effects: 'سرخوږی، نس ناستی، د معدې ستونزې.',
    warning: 'د اوږدې مودې استعمال باید د طبي مشورې له مخې وي.',
  },
  {
    id: '8',
    name: 'Salbutamol',
    generic: 'Salbutamol',
    category: 'Bronchodilator',
    uses: 'د ساه لنډۍ او د هوايي لارو د تنګوالي د نښو د کمولو لپاره.',
    forms: ['Inhaler', 'Nebulizer Solution'],
    side_effects: 'رېږدېدل، د زړه چټک درزا او سر درد.',
    warning: 'د تنفسي ستونزې د شدیدېدو په صورت کې عاجله طبي پاملرنه ضروري ده.',
  },
  {
    id: '9',
    name: 'Amlodipine',
    generic: 'Amlodipine',
    category: 'Calcium channel blocker',
    uses: 'د لوړ فشار او ځینو زړه‌يي حالتونو لپاره کارېږي.',
    forms: ['Tablet'],
    side_effects: 'د پښو پړسوب، سر درد او سر ګرځېدل.',
    warning: 'له خپل سر استعمال څخه ډډه وکړئ.',
  },
  {
    id: '10',
    name: 'Azithromycin',
    generic: 'Azithromycin',
    category: 'Macrolide antibiotic',
    uses: 'د ځینو باکتریايي انتاناتو لپاره کارېږي.',
    forms: ['Tablet', 'Suspension'],
    side_effects: 'زړه بدوالی، نس ناستی او د معدې ناارامي.',
    warning: 'د انټي‌بیوټیک استعمال باید د روغتیايي مسلکي د سپارښتنې مطابق وي.',
  },
  {
    id: '11',
    name: 'Warfarin',
    generic: 'Warfarin',
    category: 'Anticoagulant',
    uses: 'په ځانګړو حالتونو کې د وینې د لخته کېدو د مخنیوي لپاره.',
    forms: ['Tablet'],
    side_effects: 'وینه بهېدل، کبودي.',
    warning: 'د INR او وینې د لخته کېدو څارنه ضروري ده.',
  },
  {
    id: '12',
    name: 'Clopidogrel',
    generic: 'Clopidogrel',
    category: 'Antiplatelet',
    uses: 'د وینې د ټوټې کېدو د خطر د کمولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې بهېدنې خطر زیاتولی شي.',
    warning: 'د ډاکټر له مشورې پرته یې مه بندوئ.',
  },
  {
    id: '13',
    name: 'Atorvastatin',
    generic: 'Atorvastatin',
    category: 'Statin',
    uses: 'د وینې د کولېسټرول د کمولو لپاره کارېږي.',
    forms: ['Tablet'],
    side_effects: 'د عضلاتو درد او د معدې ځینې ستونزې.',
    warning: 'د روغتیايي مسلکي لارښوونې ته پام وکړئ.',
  },
  {
    id: '14',
    name: 'Simvastatin',
    generic: 'Simvastatin',
    category: 'Statin',
    uses: 'د Cholesterol د کمولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'عضلاتي درد، د ځیګر انزایمونو بدلون.',
    warning: 'د شدید عضلاتي درد په صورت کې طبي مشوره مهمه ده.',
  },
  {
    id: '15',
    name: 'Lisinopril',
    generic: 'Lisinopril',
    category: 'ACE Inhibitor',
    uses: 'د لوړ فشار او ځینو قلبي حالتونو لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'ټوخی، سرګرځېدل، د Potassium زیاتوالی.',
    warning: 'د پښتورګو فعالیت او Potassium څارنه مهمه ده.',
  },
  {
    id: '16',
    name: 'Spironolactone',
    generic: 'Spironolactone',
    category: 'Potassium-sparing Diuretic',
    uses: 'د ځینو قلبي، فشار او اضافي مایعاتو حالتونو لپاره.',
    forms: ['Tablet', 'Oral Suspension'],
    side_effects: 'د Potassium زیاتوالی، سرګرځېدل.',
    warning: 'د Potassium او پښتورګو فعالیت څارنه ضروري ده.',
  },
  {
    id: '17',
    name: 'Diclofenac',
    generic: 'Diclofenac',
    category: 'NSAID',
    uses: 'د درد او التهاب د کمولو لپاره.',
    forms: ['Tablet', 'Gel', 'Injection', 'Suppository'],
    side_effects: 'د معدې درد، زړه بدوالی، د معدې وینې بهېدل.',
    warning: 'د اوږدې مودې استعمال باید د طبي مشورې له مخې وي.',
  },
  {
    id: '18',
    name: 'Ciprofloxacin',
    generic: 'Ciprofloxacin',
    category: 'Fluoroquinolone antibiotic',
    uses: 'د ځینو باکتریايي انتاناتو لپاره کارېږي.',
    forms: ['Tablet', 'Eye Drops'],
    side_effects: 'زړه بدوالی، نس ناستی او نور جانبي عوارض.',
    warning: 'یوازې د روغتیايي مسلکي د سپارښتنې له مخې استعمالېږي.',
  },
  {
    id: '19',
    name: 'Ferrous Sulfate',
    generic: 'Ferrous Sulfate',
    category: 'Iron supplement',
    uses: 'د اوسپنې د کمښت او د وینې د کمښت په درملنه کې کارېږي.',
    forms: ['Tablet', 'Syrup'],
    side_effects: 'قبض، زړه بدوالی او د معدې ناارامي.',
    warning: 'له ماشومانو څخه یې لرې وساتئ.',
  },
  {
    id: '20',
    name: 'Doxycycline',
    generic: 'Doxycycline',
    category: 'Tetracycline antibiotic',
    uses: 'د ځینو باکتریايي انتاناتو لپاره کارېږي.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'زړه بدوالی، نس ناستی، د لمر حساسیت.',
    warning: 'د انټي‌بیوټیک استعمال باید د مسلکي سپارښتنې مطابق وي.',
  },
  {
    id: '21',
    name: 'Fluconazole',
    generic: 'Fluconazole',
    category: 'Antifungal',
    uses: 'د ځینو فنګسي انتاناتو د درملنې لپاره کارېږي.',
    forms: ['Capsule', 'Suspension'],
    side_effects: 'زړه بدوالی، د معدې ناارامي او سر درد.',
    warning: 'د نورو درملو په اړه روغتیايي مسلکي خبر کړئ.',
  },
  {
    id: '22',
    name: 'Metronidazole',
    generic: 'Metronidazole',
    category: 'Antimicrobial',
    uses: 'د ځینو باکتریايي او پرازیتي انتاناتو لپاره کارېږي.',
    forms: ['Tablet', 'Suspension', 'Injection'],
    side_effects: 'زړه بدوالی، د معدې ناارامي.',
    warning: 'د الکولو سره مه استعمالوئ.',
  },
  {
    id: '23',
    name: 'Diazepam',
    generic: 'Diazepam',
    category: 'Benzodiazepine',
    uses: 'د ځینو اضطرابي، عضلاتي او Seizure حالتونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبولي، سر ګرځېدل، د غبرګون د سرعت کمېدل.',
    warning: 'یوازې د روغتیايي مسلکي د لارښوونې له مخې وي.',
  },
  {
    id: '24',
    name: 'Morphine',
    generic: 'Morphine',
    category: 'Opioid analgesic',
    uses: 'په روغتیايي مرکزونو کې د شدید درد لپاره کارېږي.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبولي، قبض، زړه بدوالی، د تنفس کمېدل.',
    warning: 'قوي opioid دی؛ یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '25',
    name: 'Tramadol',
    generic: 'Tramadol',
    category: 'Opioid analgesic',
    uses: 'د ځینو متوسطو تر شدیدو دردونو لپاره کارېږي.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'خوبولي، سر ګرځېدل، زړه بدوالی، قبض.',
    warning: 'د dependence او overdose خطر لري.',
  },
  {
    id: '26',
    name: 'Fluoxetine',
    generic: 'Fluoxetine',
    category: 'Antidepressant',
    uses: 'د Depression او ځینو نورو رواني اختلالاتو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'زړه بدوالی، سر درد او د خوب بدلون.',
    warning: 'یوازې د روغتیايي مسلکي د لارښوونې مطابق.',
  },
  {
    id: '27',
    name: 'Sertraline',
    generic: 'Sertraline',
    category: 'Antidepressant',
    uses: 'د Depression او ځینو اضطرابي اختلالاتو لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، سر درد، خوب یا بې خوبي.',
    warning: 'په تنکیو ځوانانو کې باید د متخصص تر څارنې لاندې وي.',
  },
  {
    id: '28',
    name: 'Digoxin',
    generic: 'Digoxin',
    category: 'Cardiac Glycoside',
    uses: 'د زړه د ځینو ځانګړو حالتونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'زړه بدوالی، سر ګرځېدل او د لید بدلونونه.',
    warning: 'د درملو کچه او kidney function څارل کېږي.',
  },
  {
    id: '29',
    name: 'Furosemide',
    generic: 'Furosemide',
    category: 'Loop diuretic',
    uses: 'د بدن د اضافي مایعاتو د کمولو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د مایعاتو او مالګو بدلون، سر ګرځېدل.',
    warning: 'د استعمال پر مهال طبي څارنه مهمه ده.',
  },
  {
    id: '30',
    name: 'Carbamazepine',
    generic: 'Carbamazepine',
    category: 'Antiepileptic',
    uses: 'د Epilepsy او ځینو عصبي دردونو لپاره.',
    forms: ['Tablet', 'Oral Suspension'],
    side_effects: 'سر ګرځېدل، خوبولي، زړه بدوالی.',
    warning: 'د پوستکي جدي rash په صورت کې طبي ارزونه ضروري ده.',
  },
  {
    id: '31',
    name: 'Phenytoin',
    generic: 'Phenytoin',
    category: 'Antiepileptic',
    uses: 'د ځینو Seizures لپاره.',
    forms: ['Capsule', 'Injection'],
    side_effects: 'سر ګرځېدل، د لثو پړسوب، د پوستکي دانې.',
    warning: 'د وینې د درمل کچه څارنه مهمه ده.',
  },
  {
    id: '32',
    name: 'Rifampicin',
    generic: 'Rifampicin',
    category: 'Antitubercular',
    uses: 'د Tuberculosis د درملنې په ځانګړو رژیمونو کې.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د معدې ناارامي، د بدن د مایعاتو رنګ بدلېدل.',
    warning: 'د TB درملنه باید بشپړ طبي regimen وي.',
  },
  {
    id: '33',
    name: 'Isoniazid',
    generic: 'Isoniazid',
    category: 'Antitubercular',
    uses: 'د Tuberculosis د درملنې او مخنیوي په رژیمونو کې.',
    forms: ['Tablet'],
    side_effects: 'nausea، د liver ستونزې، peripheral neuropathy.',
    warning: 'د TB متخصصې درملنې ته اړتیا لري.',
  },
  {
    id: '34',
    name: 'Amiodarone',
    generic: 'Amiodarone',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ځینو بې نظم ضربانونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'سر ګرځېدل، د thyroid او liver ستونزې.',
    warning: 'د طبي څارنې او مناسبې معاینې اړتیا لري.',
  },
  {
    id: '35',
    name: 'Haloperidol',
    generic: 'Haloperidol',
    category: 'Antipsychotic',
    uses: 'د ځینو رواني او شدیدو اضطرابي حالتونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د عضلاتو سختوالی، رعشه، خوبجن.',
    warning: 'د QT اوږدوالی او NMS خطر.',
  },
  {
    id: '36',
    name: 'Lithium Carbonate',
    generic: 'Lithium Carbonate',
    category: 'Mood Stabilizer',
    uses: 'د Bipolar Disorder په درملنه کې.',
    forms: ['Tablet'],
    side_effects: 'رعشه، ډیر ادرار، د وزن زیاتوالی.',
    warning: 'د وینې د لیټیم کچه باید وڅارل شي.',
  },
  {
    id: '37',
    name: 'Prednisolone',
    generic: 'Prednisolone',
    category: 'Corticosteroid',
    uses: 'د ځینو التهابي او حساسیتي حالتونو لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'د استعمال له مودې سره سم مختلف عوارض.',
    warning: 'د اوږدې مودې استعمال باید د څارنې لاندې وي.',
  },
  {
    id: '38',
    name: 'Clarithromycin',
    generic: 'Clarithromycin',
    category: 'Macrolide antibiotic',
    uses: 'د ځینو bacterial infections او H. pylori لپاره.',
    forms: ['Tablet', 'Suspension'],
    side_effects: 'nausea، diarrhea، د خولې بد خوند.',
    warning: 'د درملو بشپړ لېست باید وکتل شي.',
  },
  {
    id: '39',
    name: 'Calcium Carbonate',
    generic: 'Calcium Carbonate',
    category: 'Mineral supplement',
    uses: 'د کلسیم د اړتیا او د معدې د تېزابو د کمولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'قبض او د معدې ناارامي.',
    warning: 'د نورو درملو د استعمال په اړه مسلکي خبر کړئ.',
  },
  {
    id: '40',
    name: 'Phenobarbital',
    generic: 'Phenobarbital',
    category: 'Antiepileptic',
    uses: 'د ځینو Seizure حالتونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبجن، سرګردانی، د روږديتوب خطر.',
    warning: 'د تنفس ټیټوالی او د روږديتوب خطر.',
  },
  {
    id: '41',
    name: 'Loratadine',
    generic: 'Loratadine',
    category: 'Antihistamine',
    uses: 'د الرژۍ د ځینو نښو د کمولو لپاره.',
    forms: ['Tablet', 'Syrup'],
    side_effects: 'سر درد، ستړیا یا د خوب احساس.',
    warning: 'د استعمال پر مهال د خپل بدن غبرګون ته پام وکړئ.',
  },
  {
    id: '42',
    name: 'Pantoprazole',
    generic: 'Pantoprazole',
    category: 'Proton pump inhibitor',
    uses: 'د معدې د تېزابو د کمولو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'سر درد، زړه بدوالی او د معدې ناارامي.',
    warning: 'د اوږدې مودې استعمال باید د څارنې لاندې وي.',
  },
  {
    id: '43',
    name: 'Ondansetron',
    generic: 'Ondansetron',
    category: 'Antiemetic',
    uses: 'د زړه بدوالي او کانګې د مخنیوي لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'سر درد او قبض.',
    warning: 'د روغتیايي مسلکي لارښوونې مطابق استعمال یې مهم دی.',
  },
  {
    id: '44',
    name: 'Amitriptyline',
    generic: 'Amitriptyline',
    category: 'Antidepressant',
    uses: 'د Depression او ځینو عصبي دردونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبولي، د خولې وچوالی او سر ګرځېدل.',
    warning: 'له خپل سر استعمال څخه ډډه وکړئ.',
  },
  {
    id: '45',
    name: 'Hydrochlorothiazide',
    generic: 'Hydrochlorothiazide',
    category: 'Diuretic',
    uses: 'د لوړ فشار او د مایعاتو د زیاتوالي په ځینو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'سر ګرځېدل او د بدن د مایعاتو بدلونونه.',
    warning: 'د استعمال پر مهال طبي څارنه ممکنه ده.',
  },
  {
    id: '46',
    name: 'Enalapril',
    generic: 'Enalapril',
    category: 'ACE Inhibitor',
    uses: 'د لوړ فشار او ځینو قلبي حالتونو لپاره.',
    forms: ['Tablet', 'Oral Solution'],
    side_effects: 'ټوخی، سرګرځېدل، د Potassium زیاتوالی.',
    warning: 'د پښتورګو فعالیت څارنه مهمه ده.',
  },
  {
    id: '47',
    name: 'Valsartan',
    generic: 'Valsartan',
    category: 'ARB',
    uses: 'د لوړ فشار او ځینو قلبي حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرګرځېدل، د Potassium زیاتوالی.',
    warning: 'د فشار او پښتورګو څارنه مهمه ده.',
  },
  {
    id: '48',
    name: 'Bisoprolol',
    generic: 'Bisoprolol',
    category: 'Beta Blocker',
    uses: 'د لوړ فشار او ځینو قلبي حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'ستړیا، سرګرځېدل، د زړه ضربان کمېدل.',
    warning: 'د ناڅاپي بندولو څخه باید ډډه وشي.',
  },
  {
    id: '49',
    name: 'Rosuvastatin',
    generic: 'Rosuvastatin',
    category: 'Statin',
    uses: 'د وینې د کولیسټرول د کمولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرخوږی، د عضلاتو درد، د معدې درد.',
    warning: 'د liver او عضلاتو اړوند نښې باید جدي ونیول شي.',
  },
  {
    id: '50',
    name: 'Heparin',
    generic: 'Heparin',
    category: 'Anticoagulant',
    uses: 'د وینې د ټوټې کېدو د مخنیوي لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې بهېدنه، د پلیټلیټ کمښت.',
    warning: 'یوازې د روغتیايي مسلکي تر څارنې لاندې کارول کېږي.',
  },
];
