// ==================== medicines13.js — دیارلسمه برخه ====================
export const medicines13 = [
  {
    id: '601',
    name: 'Lutetium Lu 177 Dotatate',
    generic: 'Lutetium Lu 177 Dotatate',
    category: 'Antineoplastic (Radioactive)',
    uses: 'د Gastroenteropancreatic Neuroendocrine Tumors (GEP-NETs) لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د پښتورګو ستونزې، زړه بدوالی.',
    warning: 'د وینې د حجرو او د پښتورګو څارنه مهمه ده.',
  },
  {
    id: '602',
    name: 'Iobenguane I 131',
    generic: 'Iobenguane I 131',
    category: 'Antineoplastic (Radioactive)',
    uses: 'د Pheochromocytoma او Paraganglioma لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د وینې فشار لوړوالی، زړه بدوالی.',
    warning: 'د وینې د حجرو او د فشار څارنه.',
  },
  {
    id: '603',
    name: 'Radium Ra 223 Dichloride',
    generic: 'Radium Ra 223 Dichloride',
    category: 'Antineoplastic (Radioactive)',
    uses: 'د Prostate cancer د هډوکو metastasis لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، اسهال، زړه بدوالی.',
    warning: 'د وینې د حجرو څارنه مهمه ده.',
  },
  {
    id: '604',
    name: 'Samarium Sm 153 Lexidronam',
    generic: 'Samarium Sm 153 Lexidronam',
    category: 'Antineoplastic (Radioactive)',
    uses: 'د هډوکو درد لپاره د سرطان په ناروغانو کې.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د هډوکو درد، زړه بدوالی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '605',
    name: 'Strontium Sr 89 Chloride',
    generic: 'Strontium Sr 89 Chloride',
    category: 'Antineoplastic (Radioactive)',
    uses: 'د هډوکو درد لپاره د سرطان په ناروغانو کې.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د هډوکو درد، زړه بدوالی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '606',
    name: 'Yttrium Y 90 Ibritumomab Tiuxetan',
    generic: 'Yttrium Y 90 Ibritumomab Tiuxetan',
    category: 'Antineoplastic (Radioactive)',
    uses: 'د Non-Hodgkin Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د انتاناتو خطر، زړه بدوالی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '607',
    name: 'Iodine I 131 Tositumomab',
    generic: 'Iodine I 131 Tositumomab',
    category: 'Antineoplastic (Radioactive)',
    uses: 'د Non-Hodgkin Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د تایرویډ ستونزې، زړه بدوالی.',
    warning: 'د وینې د حجرو او د تایرویډ څارنه.',
  },
  {
    id: '608',
    name: 'Fluorodopa F 18',
    generic: 'Fluorodopa F 18',
    category: 'Diagnostic (Radioactive)',
    uses: 'د PET سکن لپاره د پارکینسن او نورو حالتونو تشخیص.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د وینې فشار بدلونونه.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '609',
    name: 'Fludeoxyglucose F 18',
    generic: 'Fludeoxyglucose F 18 (FDG)',
    category: 'Diagnostic (Radioactive)',
    uses: 'د PET سکن لپاره د سرطان او نورو حالتونو تشخیص.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د وینې شکرې بدلونونه.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '610',
    name: 'Technetium Tc 99m Sestamibi',
    generic: 'Technetium Tc 99m Sestamibi',
    category: 'Diagnostic (Radioactive)',
    uses: 'د زړه او د پارا‌تایرایډ سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د وینې فشار بدلونونه.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '611',
    name: 'Iodine I 123',
    generic: 'Iodine I 123',
    category: 'Diagnostic (Radioactive)',
    uses: 'د تایرویډ سکن او د نورو حالتونو تشخیص.',
    forms: ['Capsule', 'Oral solution'],
    side_effects: 'د معدې ناروغي، د پوستکي خارښت.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '612',
    name: 'Indium In 111 Pentetreotide',
    generic: 'Indium In 111 Pentetreotide',
    category: 'Diagnostic (Radioactive)',
    uses: 'د Neuroendocrine tumors سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، زړه بدوالی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '613',
    name: 'Gallium Ga 68 Dotatate',
    generic: 'Gallium Ga 68 Dotatate',
    category: 'Diagnostic (Radioactive)',
    uses: 'د Neuroendocrine tumors PET سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، زړه بدوالی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '614',
    name: 'Copper Cu 64 Dotatate',
    generic: 'Copper Cu 64 Dotatate',
    category: 'Diagnostic (Radioactive)',
    uses: 'د Neuroendocrine tumors PET سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، زړه بدوالی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '615',
    name: 'Flortaucipir F 18',
    generic: 'Flortaucipir F 18',
    category: 'Diagnostic (Radioactive)',
    uses: 'د Alzheimer disease PET سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '616',
    name: 'Florbetapir F 18',
    generic: 'Florbetapir F 18',
    category: 'Diagnostic (Radioactive)',
    uses: 'د Alzheimer disease PET سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '617',
    name: 'Florbetaben F 18',
    generic: 'Florbetaben F 18',
    category: 'Diagnostic (Radioactive)',
    uses: 'د Alzheimer disease PET سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '618',
    name: 'Piflufolastat F 18',
    generic: 'Piflufolastat F 18',
    category: 'Diagnostic (Radioactive)',
    uses: 'د Prostate cancer PET سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '619',
    name: 'Gallium Ga 68 PSMA-11',
    generic: 'Gallium Ga 68 PSMA-11',
    category: 'Diagnostic (Radioactive)',
    uses: 'د Prostate cancer PET سکن لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، زړه بدوالی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '620',
    name: 'Amino Acid Injection',
    generic: 'Amino Acid Injection',
    category: 'Nutritional / Intravenous',
    uses: 'د تغذیې لپاره د روغتون په ناروغانو کې.',
    forms: ['Intravenous solution'],
    side_effects: 'د انفوزیون ځای غبرګونونه، د الکترولایتونو عدم توازن.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '621',
    name: 'Lipid Emulsion',
    generic: 'Lipid Emulsion',
    category: 'Nutritional / Intravenous',
    uses: 'د تغذیې لپاره د روغتون په ناروغانو کې.',
    forms: ['Intravenous emulsion'],
    side_effects: 'د انفوزیون ځای غبرګونونه، د وینې د شکرې بدلونونه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '622',
    name: 'Dextrose Injection',
    generic: 'Dextrose',
    category: 'Electrolyte / Energy',
    uses: 'د وینې د شکرې د ټیټوالي او د مایعاتو د بدیل لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې د شکرې لوړوالی، د انفوزیون ځای غبرګونونه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '623',
    name: 'Lactated Ringer Injection',
    generic: 'Lactated Ringer',
    category: 'Intravenous Fluid',
    uses: 'د مایعاتو او الکترولایتونو د بدیل لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د مایعاتو او الکترولایتونو بدلونونه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '624',
    name: 'Plasma-Lyte',
    generic: 'Plasma-Lyte',
    category: 'Intravenous Fluid',
    uses: 'د مایعاتو او الکترولایتونو د بدیل لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د مایعاتو او الکترولایتونو بدلونونه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '625',
    name: 'Albumin 5%',
    generic: 'Albumin 5%',
    category: 'Plasma Expander',
    uses: 'د مایعاتو د بدیل لپاره په ځینو حالتونو کې.',
    forms: ['Intravenous solution'],
    side_effects: 'د اوبو ساتنه، الرژي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '626',
    name: 'Albumin 25%',
    generic: 'Albumin 25%',
    category: 'Plasma Expander',
    uses: 'د مایعاتو د بدیل لپاره په ځینو حالتونو کې.',
    forms: ['Intravenous solution'],
    side_effects: 'د اوبو ساتنه، الرژي، د وینې فشار لوړوالی.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '627',
    name: 'Hespan',
    generic: 'Hetastarch',
    category: 'Plasma Expander',
    uses: 'د مایعاتو د بدیل لپاره په ځینو حالتونو کې.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې د لخته کیدو ستونزې، الرژي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '628',
    name: 'Dextran 70',
    generic: 'Dextran 70',
    category: 'Plasma Expander',
    uses: 'د مایعاتو د بدیل لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د اوبو ساتنه، الرژي، د وینې د لخته کیدو ستونزې.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '629',
    name: 'Pentastarch',
    generic: 'Pentastarch',
    category: 'Plasma Expander',
    uses: 'د مایعاتو د بدیل لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې د لخته کیدو ستونزې، الرژي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '630',
    name: 'Gelatin Plasma Substitute',
    generic: 'Gelatin (Succinylated)',
    category: 'Plasma Expander',
    uses: 'د مایعاتو د بدیل لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'الرژي، د وینې د لخته کیدو ستونزې.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '631',
    name: 'Sodium Chloride 3%',
    generic: 'Hypertonic Saline 3%',
    category: 'Electrolyte',
    uses: 'د هایپوناترمیا او د ICP د لوړوالي لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د سودیم لوړوالی، د اوبو ساتنه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '632',
    name: 'Sodium Chloride 0.45%',
    generic: 'Half Normal Saline',
    category: 'Electrolyte',
    uses: 'د مایعاتو د بدیل لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د هایپوناترمیا خطر، د اوبو ساتنه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '633',
    name: 'Dextrose 5% in Water',
    generic: 'D5W',
    category: 'Intravenous Fluid',
    uses: 'د مایعاتو د بدیل او د وینې د شکرې لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې د شکرې لوړوالی، د اوبو ساتنه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '634',
    name: 'Dextrose 10% in Water',
    generic: 'D10W',
    category: 'Intravenous Fluid',
    uses: 'د وینې د شکرې او د مایعاتو لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې د شکرې لوړوالی، د اوبو ساتنه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '635',
    name: 'Dextrose 50%',
    generic: 'D50W',
    category: 'Electrolyte / Energy',
    uses: 'د شدید هایپوګلایسیمیا لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې د شکرې لوړوالی، د انفوزیون ځای غبرګونونه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '636',
    name: 'Potassium Chloride IV',
    generic: 'Potassium Chloride (IV)',
    category: 'Electrolyte',
    uses: 'د پوتاشیم د کموالي لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د پوتاشیم لوړوالی، د زړه د ریتم ستونزې.',
    warning: 'یوازې د روغتون په څارنه کې او د ECG سره.',
  },
  {
    id: '637',
    name: 'Magnesium Sulfate IV',
    generic: 'Magnesium Sulfate (IV)',
    category: 'Electrolyte',
    uses: 'د Magnesium د کموالي او د Pre-eclampsia لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې فشار ټیټوالی، د عضلاتو ضعف، د تنفس ټیټوالی.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '638',
    name: 'Calcium Gluconate IV',
    generic: 'Calcium Gluconate (IV)',
    category: 'Electrolyte',
    uses: 'د هایپرکالیمیا، د هایپوکالسمیا او د Magnesium زهرجنیت لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د زړه د ریتم ستونزې، د وینې فشار ټیټوالی.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '639',
    name: 'Sodium Bicarbonate IV',
    generic: 'Sodium Bicarbonate (IV)',
    category: 'Electrolyte',
    uses: 'د میټابولیک اسیدوز او د ځینو زهرجنیتونو لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د سودیم لوړوالی، الکالوز، د پوتاشیم کمښت.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '640',
    name: 'Sodium Acetate IV',
    generic: 'Sodium Acetate (IV)',
    category: 'Electrolyte',
    uses: 'د میټابولیک اسیدوز لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د سودیم لوړوالی، الکالوز.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '641',
    name: 'Ammonium Chloride',
    generic: 'Ammonium Chloride',
    category: 'Electrolyte',
    uses: 'د میټابولیک الکالوز لپاره.',
    forms: ['Intravenous solution', 'Oral tablet'],
    side_effects: 'د معدې ناروغي، د اسیدوز خطر.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '642',
    name: 'Potassium Phosphate IV',
    generic: 'Potassium Phosphate (IV)',
    category: 'Electrolyte',
    uses: 'د هایپوفسفاټیمیا لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د پوتاشیم لوړوالی، د فاسفورس لوړوالی، د وینې ټیټ فشار.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '643',
    name: 'Sodium Phosphate IV',
    generic: 'Sodium Phosphate (IV)',
    category: 'Electrolyte',
    uses: 'د هایپوفسفاټیمیا لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د فاسفورس لوړوالی، د کلسیم کمښت.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '644',
    name: 'Trace Elements Injection',
    generic: 'Trace Elements',
    category: 'Nutritional / Intravenous',
    uses: 'د تغذیې لپاره د روغتون په ناروغانو کې.',
    forms: ['Intravenous solution'],
    side_effects: 'د انفوزیون ځای غبرګونونه، د الکترولایتونو عدم توازن.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '645',
    name: 'Multivitamin Injection',
    generic: 'Multivitamin (IV)',
    category: 'Nutritional / Intravenous',
    uses: 'د تغذیې لپاره د روغتون په ناروغانو کې.',
    forms: ['Intravenous solution'],
    side_effects: 'د انفوزیون ځای غبرګونونه، الرژي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '646',
    name: 'Thiamine IV',
    generic: 'Thiamine (IV)',
    category: 'Vitamin',
    uses: 'د Thiamine د کموالي او د Wernicke encephalopathy لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د انفوزیون ځای غبرګونونه، الرژي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '647',
    name: 'Folic Acid IV',
    generic: 'Folic Acid (IV)',
    category: 'Vitamin',
    uses: 'د Folate د کموالي لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د انفوزیون ځای غبرګونونه، الرژي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '648',
    name: 'Cyanocobalamin IV',
    generic: 'Cyanocobalamin (IV)',
    category: 'Vitamin',
    uses: 'د Vitamin B12 د کموالي لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د انفوزیون ځای غبرګونونه، الرژي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '649',
    name: 'Phytonadione IV',
    generic: 'Phytonadione (Vitamin K1 IV)',
    category: 'Vitamin',
    uses: 'د Vitamin K د کموالي او د وینې د بهیدو لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د انفوزیون ځای غبرګونونه، الرژي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '650',
    name: 'Dexmedetomidine',
    generic: 'Dexmedetomidine',
    category: 'Sedative',
    uses: 'په روغتون کې د Sedation لپاره.',
    forms: ['Intravenous solution'],
    side_effects: 'د وینې فشار ټیټوالی، د زړه ورووالی، د خولې وچوالی.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
];
