// ==================== medicines8.js — اتمه برخه ====================
export const medicines8 = [
  {
    id: '351',
    name: 'Brigatinib',
    generic: 'Brigatinib',
    category: 'Antineoplastic agent (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، ستړیا، د وینې لوړ فشار.',
    warning: 'د ILD خطر، د وینې لوړ فشار.',
  },
  {
    id: '352',
    name: 'Lorlatinib',
    generic: 'Lorlatinib',
    category: 'Antineoplastic agent (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، د وزن زیاتوالی، د کولیسټرول لوړوالی، د مزاج بدلون.',
    warning: 'د CNS غبرګونونه او د کولیسټرول لوړوالی.',
  },
  {
    id: '353',
    name: 'Furazolidone',
    generic: 'Furazolidone',
    category: 'Antibacterial agent (nitrofuran)',
    uses: 'د اسهال او د کولمو د انتاناتو درملنه (cholera، giardiasis).',
    forms: ['Oral tablet', 'Oral suspension'],
    side_effects: 'زړه بدوالی، اسهال، د پوټکي خارښت، د ادرار رنګ بدلون.',
    warning: 'د MAOIs سره د تعامل خطر او د الکول سره د غبرګون خطر.',
  },
  {
    id: '354',
    name: 'Furazidin',
    generic: 'Furazidin',
    category: 'Antibacterial agent (nitrofuran)',
    uses: 'د ادرار د لارې انتاناتو درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'زړه بدوالی، اسهال، د پوټکي خارښت.',
    warning: 'د ادرار رنګ بدلون، د پښتورګو ناروغي.',
  },
  {
    id: '355',
    name: 'Methenamine',
    generic: 'Methenamine hippurate',
    category: 'Urinary anti-infective agent',
    uses: 'د ادرار د لارې د انتاناتو مخنیوی.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د معدې ناروغي، د ادرار رنګ بدلون.',
    warning: 'د پښتورګو ناروغي او د ځیګر ناروغي.',
  },
  {
    id: '356',
    name: 'Pivmecillinam',
    generic: 'Pivmecillinam hydrochloride',
    category: 'Antibacterial agent (penicillin)',
    uses: 'د ادرار د لارې انتاناتو درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د پوټکي خارښت.',
    warning: 'د الرژي خطر، د Clostridium difficile اسهال.',
  },
  {
    id: '357',
    name: 'Rifamycin',
    generic: 'Rifamycin SV',
    category: 'Antibacterial agent (rifamycin)',
    uses: 'د اسهال درملنه چې د E. coli لخوا رامینځته شوی وي.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د معدې ناروغي.',
    warning: 'د ادرار رنګ بدلون، د معدې ناروغي.',
  },
  {
    id: '358',
    name: 'Rifalazil',
    generic: 'Rifalazil',
    category: 'Antibacterial agent (rifamycin)',
    uses: 'د Mycobacterium avium complex (MAC) درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د پوټکي خارښت.',
    warning: 'د ځیګر زهرجنیت، د وینې د حجرو کمښت.',
  },
  {
    id: '359',
    name: 'Rifamexil',
    generic: 'Rifamexil',
    category: 'Antibacterial agent (rifamycin)',
    uses: 'د Mycobacterium avium complex (MAC) درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د پوټکي خارښت.',
    warning: 'د ځیګر زهرجنیت.',
  },
  {
    id: '360',
    name: 'Spectinomycin',
    generic: 'Spectinomycin hydrochloride',
    category: 'Antibacterial agent (aminocyclitol)',
    uses: 'د gonorrhea درملنه، د penicillin حساسیت لرونکو ناروغانو لپاره.',
    forms: ['Powder for injection'],
    side_effects: 'د انجیکشن ځای درد، زړه بدوالی، سرګرداني، تبه.',
    warning: 'د lithium زهرجنیت خطر، د انجیکشن ځای درد.',
  },
  {
    id: '361',
    name: 'Quinupristin/Dalfopristin',
    generic: 'Quinupristin and dalfopristin',
    category: 'Antibacterial agent (streptogramin)',
    uses: 'د vancomycin-resistant Enterococcus faecium (VRE) درملنه.',
    forms: ['Intravenous powder for solution'],
    side_effects: 'د انجیکشن ځای درد، د بندونو درد، زړه بدوالی، اسهال.',
    warning: 'د CYP3A4 substrates کچه زیاتوي، د انجیکشن ځای درد.',
  },
  {
    id: '362',
    name: 'Telavancin',
    generic: 'Telavancin hydrochloride',
    category: 'Antibacterial agent (lipoglycopeptide)',
    uses: 'د پیچلو پوټکي انتاناتو درملنه، لکه MRSA.',
    forms: ['Intravenous powder for solution'],
    side_effects: 'زړه بدوالی، اسهال، د پوټکي خارښت، د پښتورګو ستونزې.',
    warning: 'د پښتورګو زهرجنیت، د QT اوږدوالی، د جنین زیان.',
  },
  {
    id: '363',
    name: 'Ramoplanin',
    generic: 'Ramoplanin',
    category: 'Glycolipodepsipeptide antibiotic',
    uses: 'د Clostridium difficile د انتاناتو درملنه (د اسهال لامل)، د VRE د مخنیوي لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'زړه بدوالی، اسهال، د معدې درد، د معدې پړسوب.',
    warning: 'دا درمل د سیسټمیک جذب لپاره نه دی ټاکل شوی؛ یوازې د کولمو دننه عمل کوي.',
  },
  {
    id: '364',
    name: 'Teixobactin',
    generic: 'Teixobactin',
    category: 'Novel antibiotic (depsipeptide)',
    uses: 'د ګرام مثبتو بکتریاګانو په وړاندې فعال دی (لکه MRSA، VRE).',
    forms: ['Investigational'],
    side_effects: 'لا تر اوسه د انسانانو په کلینیکي ازموینو کې نه دي تایید شوي.',
    warning: 'دا درمل لاهم د څیړنې په مرحله کې دی او د کلینیکي کارونې لپاره نه دی تایید شوی.',
  },
  {
    id: '365',
    name: 'Azimilide',
    generic: 'Azimilide',
    category: 'Class III antiarrhythmic agent',
    uses: 'د atrial fibrillation او atrial flutter درملنه.',
    forms: ['Oral capsule', 'Oral solution', 'Intravenous infusion'],
    side_effects: 'سرخوږی، سرګردانی، زړه بدوالی، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی خطر، Torsades de Pointes.',
  },
  {
    id: '366',
    name: 'Adefovir',
    generic: 'Adefovir dipivoxil',
    category: 'Antiviral agent (nucleoside analog)',
    uses: 'د مزمن hepatitis B درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پښتورګو زهرجنیت، د وینې د فاسفورس کمښت، د معدې ناروغي.',
    warning: 'د پښتورګو فعالیت باید منظم وڅارل شي.',
  },
  {
    id: '367',
    name: 'Enfuvirtide',
    generic: 'Enfuvirtide',
    category: 'Antiviral agent (fusion inhibitor)',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Lyophilized powder for subcutaneous injection'],
    side_effects: 'د انجیکشن ځای عکس‌العملونه، د pneumonia خطر زیاتوالی.',
    warning: 'د pneumonia خطر زیاتوالی او د انجیکشن ځای عکس‌العملونه.',
  },
  {
    id: '368',
    name: 'Bictegravir',
    generic: 'Bictegravir',
    category: 'Antiviral agent (integrase inhibitor)',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Coformulated oral tablet'],
    side_effects: 'اسهال، زړه بدوالی، سرخوږی.',
    warning: 'د hepatitis B د درملنې وروسته acute exacerbation.',
  },
  {
    id: '369',
    name: 'Cabotegravir',
    generic: 'Cabotegravir',
    category: 'Antiviral agent (integrase inhibitor)',
    uses: 'د HIV-1 انتاناتو درملنه او PrEP.',
    forms: ['Oral tablet', 'Extended-release injectable suspension'],
    side_effects: 'د انجیکشن ځای عکس‌العملونه، سرخوږی، تبې، ستړیا.',
    warning: 'د انجیکشن ځای عکس‌العملونه او immune reconstitution syndrome.',
  },
  {
    id: '370',
    name: 'Doravirine',
    generic: 'Doravirine',
    category: 'Antiviral agent (NNRTI)',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Oral film-coated tablet'],
    side_effects: 'سرخوږی، ستړیا، زړه بدوالی، اسهال.',
    warning: 'immune reconstitution syndrome رامنځته کېدای شي.',
  },
  {
    id: '371',
    name: 'Etravirine',
    generic: 'Etravirine',
    category: 'Antiviral agent (NNRTI)',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د پوټکي خارښت، زړه بدوالی، اسهال.',
    warning: 'د پوټکي خطرناک عکس‌العملونه.',
  },
  {
    id: '372',
    name: 'Fosamprenavir',
    generic: 'Fosamprenavir',
    category: 'Antiviral agent (protease inhibitor)',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Oral tablet', 'Oral suspension'],
    side_effects: 'اسهال، زړه بدوالی، د پوټکي خارښت.',
    warning: 'د پوټکي خطرناک عکس‌العملونه او د ځیګر زهرجنیت.',
  },
  {
    id: '373',
    name: 'Saquinavir',
    generic: 'Saquinavir',
    category: 'Antiviral agent (protease inhibitor)',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Film-coated oral tablet'],
    side_effects: 'اسهال، زړه بدوالی، د معدې ناروغي.',
    warning: 'د QT اوږدوالی او د ځیګر زهرجنیت.',
  },
  {
    id: '374',
    name: 'Tipranavir',
    generic: 'Tipranavir',
    category: 'Antiviral agent (protease inhibitor)',
    uses: 'د HIV-1 انتاناتو درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر زهرجنیت او د intracranial hemorrhage خطر.',
  },
  {
    id: '375',
    name: 'Peramivir',
    generic: 'Peramivir',
    category: 'Antiviral agent (neuraminidase inhibitor)',
    uses: 'د انفلوانزا درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'اسهال، زړه بدوالی، سرخوږی، د وینې ټیټ فشار.',
    warning: 'د نښو له پیل څخه د ۴۸ ساعتونو دننه استعمال.',
  },
  {
    id: '376',
    name: 'Cidofovir',
    generic: 'Cidofovir',
    category: 'Antiviral agent (nucleotide analog)',
    uses: 'د cytomegalovirus (CMV) retinitis درملنه.',
    forms: ['Intravenous solution'],
    side_effects: 'د پښتورګو زهرجنیت، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د پښتورګو زهرجنیت؛ د پښتورګو فعالیت باید منظم وڅارل شي.',
  },
  {
    id: '377',
    name: 'Foscarnet',
    generic: 'Foscarnet',
    category: 'Antiviral agent (pyrophosphate analog)',
    uses: 'د CMV retinitis او acyclovir-resistant HSV درملنه.',
    forms: ['Intravenous infusion'],
    side_effects: 'د پښتورګو زهرجنیت، د کلسیم او مګنیزیم کمښت.',
    warning: 'د پښتورګو زهرجنیت او د الکترولیتونو عدم توازن.',
  },
  {
    id: '378',
    name: 'Letermovir',
    generic: 'Letermovir',
    category: 'Antiviral agent (CMV terminase inhibitor)',
    uses: 'د CMV انتاناتو مخنیوی.',
    forms: ['Oral tablet', 'Oral pellets', 'Intravenous solution'],
    side_effects: 'زړه بدوالی، اسهال، د پښو پړسوب، سرخوږی.',
    warning: 'د cyclosporine کچه لوړولی شي.',
  },
  {
    id: '379',
    name: 'Brincidofovir',
    generic: 'Brincidofovir',
    category: 'Antiviral agent (lipid conjugate of cidofovir)',
    uses: 'د smallpox درملنه.',
    forms: ['Oral tablet', 'Oral suspension'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر زهرجنیت.',
  },
  {
    id: '380',
    name: 'Fidaxomicin',
    generic: 'Fidaxomicin',
    category: 'Antibacterial agent (macrocyclic antibiotic)',
    uses: 'د Clostridium difficile انتاناتو درملنه.',
    forms: ['Oral film-coated tablet', 'Oral suspension'],
    side_effects: 'زړه بدوالی، اسهال، د معدې درد، د پوټکي خارښت.',
    warning: 'د Clostridium difficile انتاناتو درملنه.',
  },
  {
    id: '381',
    name: 'Bezlotoxumab',
    generic: 'Bezlotoxumab',
    category: 'Monoclonal antibody',
    uses: 'د C. difficile انتاناتو د بیا پیښیدو مخنیوی.',
    forms: ['Intravenous solution'],
    side_effects: 'زړه بدوالی، اسهال، تبې، سر درد.',
    warning: 'د زړه ناکامي خطر او د انفوزیون غبرګونونه.',
  },
  {
    id: '382',
    name: 'Lefamulin',
    generic: 'Lefamulin',
    category: 'Antibacterial agent (pleuromutilin)',
    uses: 'د سږو انتاناتو درملنه.',
    forms: ['Oral coated tablet', 'Intravenous solution'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د QT اوږدوالی او د ځیګر زهرجنیت.',
  },
  {
    id: '383',
    name: 'Ceftolozane',
    generic: 'Ceftolozane',
    category: 'Antibacterial agent (cephalosporin)',
    uses: 'د پیچلو انتاناتو درملنه، د tazobactam سره یوځای.',
    forms: ['Intravenous powder for solution'],
    side_effects: 'زړه بدوالی، اسهال، سرخوږی، تبې.',
    warning: 'د الرژي خطر او د Clostridium difficile اسهال.',
  },
  {
    id: '384',
    name: 'Avibactam',
    generic: 'Avibactam',
    category: 'Beta-lactamase inhibitor',
    uses: 'د ceftazidime سره یوځای د پیچلو انتاناتو درملنه.',
    forms: ['Intravenous powder for solution'],
    side_effects: 'اسهال، زړه بدوالی، د پوټکي خارښت.',
    warning: 'د الرژي خطر او د Clostridium difficile اسهال.',
  },
  {
    id: '385',
    name: 'Doripenem',
    generic: 'Doripenem',
    category: 'Antibacterial agent (carbapenem)',
    uses: 'د پیچلو انتاناتو درملنه.',
    forms: ['Intravenous powder for solution'],
    side_effects: 'اسهال، زړه بدوالی، د پوټکي خارښت.',
    warning: 'د تشنج خطر او د Clostridium difficile اسهال.',
  },
  {
    id: '386',
    name: 'Suzetrigine',
    generic: 'Suzetrigine',
    category: 'Analgesic (NaV1.8 inhibitor)',
    uses: 'د لویانو د منځني څخه تر شدید حاد درد درملنه.',
    forms: ['Oral film-coated tablet'],
    side_effects: 'د خارښت، د عضلاتو سپاسم، د وینې د کریټین فاسفوکایناز لوړوالی.',
    warning: 'د ۱۴ ورځو څخه زیات د حاد درد لپاره نه دی مطالعه شوی.',
  },
  {
    id: '387',
    name: 'Mirdametinib',
    generic: 'Mirdametinib',
    category: 'Antineoplastic agent (MEK inhibitor)',
    uses: 'د NF1 سره د سمپټوماتیک پلکسیفورم نیوروفایبروما درملنه.',
    forms: ['Oral capsule', 'Dispersible tablet'],
    side_effects: 'د پوټکي خارښت، اسهال، زړه بدوالی، د عضلاتو درد.',
    warning: 'د کیڼ وینټریکل dysfunction او د سترګو زهرجنیت.',
  },
  {
    id: '388',
    name: 'Vimseltinib',
    generic: 'Vimseltinib',
    category: 'Antineoplastic agent (CSF1R inhibitor)',
    uses: 'د tenosynovial giant cell tumor (TGCT) درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'د ځیګر زهرجنیت، د AST/ALT او بیلیروبین لوړوالی.',
    warning: 'د ځیګر زهرجنیت، د Hy\'s law په شمول.',
  },
  {
    id: '389',
    name: 'Diazoxide Choline',
    generic: 'Diazoxide choline',
    category: 'Anorexigenic agent',
    uses: 'د پرادر-ویلي سنډروم (PWS) سره د هایپرفاژیا درملنه.',
    forms: ['Extended-release oral tablet'],
    side_effects: 'د وینې د شکرې لوړوالی، د یوریک اسید لوړوالی، د وینې د فشار لوړوالی.',
    warning: 'د وینې د شکرې لوړوالی، د پوتاشیم کمښت او د اوبو ساتنه.',
  },
  {
    id: '390',
    name: 'Palopegteriparatide',
    generic: 'Palopegteriparatide',
    category: 'Parathyroid hormone analog',
    uses: 'د لویانو د هایپوپاراتایرویډیزم درملنه.',
    forms: ['Subcutaneous injection'],
    side_effects: 'د وینې د کلسیم عدم توازن، د انجیکشن ځای غبرګونونه.',
    warning: 'د وینې د کلسیم کچه باید وڅارل شي.',
  },
  {
    id: '391',
    name: 'Sulopenem etzadroxil / Probenecid',
    generic: 'Sulopenem etzadroxil and probenecid',
    category: 'Antibacterial agent (penem + renal inhibitor)',
    uses: 'د غیر پیچلو ادراري لارې انتاناتو (uUTI) درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، زړه بدوالی، د اندام د خمیر انتان، سرخوږی.',
    warning: 'د حساسیت غبرګونونه، د C. difficile اسهال او د gout د خرابېدو خطر.',
  },
  {
    id: '392',
    name: 'Vamorolone',
    generic: 'Vamorolone',
    category: 'Corticosteroid (dissociative steroid)',
    uses: 'د دوچین عضلاتي ډیسټروفي (DMD) درملنه.',
    forms: ['Oral suspension'],
    side_effects: 'د اشتها زیاتوالی، د وزن زیاتوالی، د adrenal suppression.',
    warning: 'د adrenal insufficiency خطر. د درملنې ناڅاپي بندول جدي ستونزې.',
  },
  {
    id: '393',
    name: 'Nemolizumab',
    generic: 'Nemolizumab',
    category: 'Monoclonal antibody (IL-31 receptor antagonist)',
    uses: 'د اټوپیک ډرماتایټس او prurigo nodularis درملنه.',
    forms: ['Subcutaneous injection'],
    side_effects: 'د پوټکي خارښت، د پوزې بندښت، د پښو پړسوب.',
    warning: 'د معافیتي سیستم اغیزه کوي او د انتاناتو خطر.',
  },
  {
    id: '394',
    name: 'Treosulfan',
    generic: 'Treosulfan',
    category: 'Alkylating agent',
    uses: 'د alloHSCT دمخه د conditioning رژیم برخه.',
    forms: ['Intravenous powder for solution'],
    side_effects: 'د وینې د حجرو کمښت، د انتاناتو خطر، د ځیګر زهرجنیت.',
    warning: 'د وینې د حجرو کمښت او د انتاناتو خطر.',
  },
  {
    id: '395',
    name: 'Epinephrine',
    generic: 'Epinephrine',
    category: 'Emergency Medicine',
    uses: 'د severe allergic reaction او ځینو بیړنیو حالتونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه چټک ضربان، رعشه، سرګرداني، د وینې فشار لوړوالی.',
    warning: 'بیړنی درمل دی او باید د مناسب طبي پروتوکول له مخې استعمال شي.',
  },
  {
    id: '396',
    name: 'Norepinephrine',
    generic: 'Norepinephrine',
    category: 'Vasopressor',
    uses: 'په روغتون کې د شدید ټیټ فشار په ځینو حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'د وینې جریان کمېدل، د زړه د ضربان بدلونونه.',
    warning: 'د تطبیق ځای د نسج زیان.',
  },
  {
    id: '397',
    name: 'Dopamine',
    generic: 'Dopamine',
    category: 'Vasopressor',
    uses: 'په روغتون کې د ځینو شدیدو دورانې ستونزو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه چټک ضربان، د وینې فشار لوړوالی.',
    warning: 'د تطبیق ځای د نسج زیان.',
  },
  {
    id: '398',
    name: 'Dobutamine',
    generic: 'Dobutamine',
    category: 'Cardiac Agent',
    uses: 'په روغتون کې د زړه د فعالیت د ملاتړ لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه چټک ضربان، د وینې فشار بدلون، سرخوږی.',
    warning: 'د روغتیايي مسلکي تر څارنې لاندې.',
  },
  {
    id: '399',
    name: 'Milrinone',
    generic: 'Milrinone',
    category: 'Cardiac Medicine',
    uses: 'په روغتون کې د ځینو شدیدو قلبي حالتونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه د ضربان غیرنورمال حالتونه، د وینې ټیټ فشار.',
    warning: 'د روغتیايي مسلکي تر څارنې لاندې.',
  },
  {
    id: '400',
    name: 'Vasopressin',
    generic: 'Vasopressin',
    category: 'Vasopressor / Hormone',
    uses: 'په روغتون کې د ځینو بیړنیو حالتونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې ټیټ فشار، د زړه د ضربان بدلونونه، د معدې ناروغي.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
];
