// ==================== medicines16.js — شپاړلسمه برخه ====================
export const medicines16 = [
  {
    id: '751',
    name: 'Cyanocobalamin (Nasal)',
    generic: 'Cyanocobalamin',
    category: 'Vitamin',
    uses: 'د Vitamin B12 د کموالي لپاره.',
    forms: ['Nasal spray', 'Nasal gel'],
    side_effects: 'د پوزې irritation، سرخوږی، زړه بدوالی.',
    warning: 'د B12 کمښت اصلي علت باید د طبي ارزونې له لارې معلوم شي.',
  },
  {
    id: '752',
    name: 'Calcitriol (Topical)',
    generic: 'Calcitriol',
    category: 'Topical Dermatologic',
    uses: 'د Psoriasis لپاره.',
    forms: ['Ointment', 'Cream'],
    side_effects: 'د تطبیق ځای خارښت، سوروالی، د پوستکي وچوالی.',
    warning: 'د کلسیم کچه باید د طبي لارښوونې له مخې وڅارل شي.',
  },
  {
    id: '753',
    name: 'Tacalcitol',
    generic: 'Tacalcitol',
    category: 'Topical Dermatologic',
    uses: 'د Psoriasis لپاره.',
    forms: ['Ointment', 'Cream'],
    side_effects: 'د تطبیق ځای خارښت، سوروالی.',
    warning: 'د کلسیم کچه باید وڅارل شي.',
  },
  {
    id: '754',
    name: 'Calcipotriol + Betamethasone',
    generic: 'Calcipotriol + Betamethasone',
    category: 'Topical Dermatologic',
    uses: 'د Psoriasis لپاره.',
    forms: ['Ointment', 'Gel'],
    side_effects: 'د تطبیق ځای خارښت، سوروالی، د پوستکي atrophy.',
    warning: 'د اوږدې مودې استعمال باید د طبي لارښوونې له مخې وي.',
  },
  {
    id: '755',
    name: 'Pimecrolimus',
    generic: 'Pimecrolimus',
    category: 'Topical Calcineurin Inhibitor',
    uses: 'د Atopic Dermatitis لپاره.',
    forms: ['Cream'],
    side_effects: 'د تطبیق ځای سوځیدنه، خارښت، سوروالی.',
    warning: 'د ۲ کلونو څخه کم عمر ماشومانو لپاره نه دی ټاکل شوی.',
  },
  {
    id: '756',
    name: 'Tacrolimus (Topical)',
    generic: 'Tacrolimus',
    category: 'Topical Calcineurin Inhibitor',
    uses: 'د Atopic Dermatitis لپاره.',
    forms: ['Ointment'],
    side_effects: 'د تطبیق ځای سوځیدنه، خارښت، سوروالی.',
    warning: 'د ۲ کلونو څخه کم عمر ماشومانو لپاره نه دی ټاکل شوی.',
  },
  {
    id: '757',
    name: 'Crisaborole',
    generic: 'Crisaborole',
    category: 'Topical PDE4 Inhibitor',
    uses: 'د Atopic Dermatitis لپاره.',
    forms: ['Ointment'],
    side_effects: 'د تطبیق ځای سوځیدنه، خارښت.',
    warning: 'د ۲ کلونو څخه کم عمر ماشومانو لپاره نه دی ټاکل شوی.',
  },
  {
    id: '758',
    name: 'Ruxolitinib (Topical)',
    generic: 'Ruxolitinib',
    category: 'Topical JAK Inhibitor',
    uses: 'د Atopic Dermatitis او Vitiligo لپاره.',
    forms: ['Cream'],
    side_effects: 'د تطبیق ځای سوځیدنه، خارښت، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '759',
    name: 'Dupilumab',
    generic: 'Dupilumab',
    category: 'Monoclonal Antibody (IL-4/IL-13 inhibitor)',
    uses: 'د Atopic Dermatitis، Asthma او Nasal Polyps لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د سترګو التهاب، د مخ سوروالی.',
    warning: 'د انتاناتو او د سترګو څارنه مهمه ده.',
  },
  {
    id: '760',
    name: 'Omalizumab',
    generic: 'Omalizumab',
    category: 'Monoclonal Antibody (anti-IgE)',
    uses: 'د Asthma او Chronic Urticaria لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، الرژي، د انتاناتو خطر.',
    warning: 'د anaphylaxis خطر.',
  },
  {
    id: '761',
    name: 'Mepolizumab',
    generic: 'Mepolizumab',
    category: 'Monoclonal Antibody (anti-IL-5)',
    uses: 'د Severe Eosinophilic Asthma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '762',
    name: 'Benralizumab',
    generic: 'Benralizumab',
    category: 'Monoclonal Antibody (anti-IL-5R)',
    uses: 'د Severe Eosinophilic Asthma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '763',
    name: 'Reslizumab',
    generic: 'Reslizumab',
    category: 'Monoclonal Antibody (anti-IL-5)',
    uses: 'د Severe Eosinophilic Asthma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د عضلاتو درد، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '764',
    name: 'Tezepelumab',
    generic: 'Tezepelumab',
    category: 'Monoclonal Antibody (anti-TSLP)',
    uses: 'د Severe Asthma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '765',
    name: 'Lebrikizumab',
    generic: 'Lebrikizumab',
    category: 'Monoclonal Antibody (anti-IL-13)',
    uses: 'د Atopic Dermatitis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د سترګو التهاب.',
    warning: 'د سترګو څارنه مهمه ده.',
  },
  {
    id: '766',
    name: 'Tralokinumab',
    generic: 'Tralokinumab',
    category: 'Monoclonal Antibody (anti-IL-13)',
    uses: 'د Atopic Dermatitis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د سترګو التهاب.',
    warning: 'د سترګو څارنه مهمه ده.',
  },
  {
    id: '767',
    name: 'Secukinumab',
    generic: 'Secukinumab',
    category: 'Monoclonal Antibody (anti-IL-17A)',
    uses: 'د Psoriasis، Psoriatic Arthritis او Ankylosing Spondylitis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '768',
    name: 'Ixekizumab',
    generic: 'Ixekizumab',
    category: 'Monoclonal Antibody (anti-IL-17A)',
    uses: 'د Psoriasis، Psoriatic Arthritis او Ankylosing Spondylitis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '769',
    name: 'Brodalumab',
    generic: 'Brodalumab',
    category: 'Monoclonal Antibody (anti-IL-17RA)',
    uses: 'د Psoriasis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د ځان وژنې فکر.',
    warning: 'د ځان وژنې فکر څارنه مهمه ده.',
  },
  {
    id: '770',
    name: 'Bimekizumab',
    generic: 'Bimekizumab',
    category: 'Monoclonal Antibody (anti-IL-17A/F)',
    uses: 'د Psoriasis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '771',
    name: 'Guselkumab',
    generic: 'Guselkumab',
    category: 'Monoclonal Antibody (anti-IL-23)',
    uses: 'د Psoriasis او Psoriatic Arthritis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '772',
    name: 'Risankizumab',
    generic: 'Risankizumab',
    category: 'Monoclonal Antibody (anti-IL-23)',
    uses: 'د Psoriasis، Psoriatic Arthritis او Crohn Disease لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '773',
    name: 'Tildrakizumab',
    generic: 'Tildrakizumab',
    category: 'Monoclonal Antibody (anti-IL-23)',
    uses: 'د Psoriasis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '774',
    name: 'Ustekinumab',
    generic: 'Ustekinumab',
    category: 'Monoclonal Antibody (anti-IL-12/23)',
    uses: 'د Psoriasis، Psoriatic Arthritis، Crohn Disease او Ulcerative Colitis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '775',
    name: 'Vedolizumab',
    generic: 'Vedolizumab',
    category: 'Monoclonal Antibody (anti-α4β7 integrin)',
    uses: 'د Ulcerative Colitis او Crohn Disease لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر، سرخوږی.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '776',
    name: 'Natalizumab',
    generic: 'Natalizumab',
    category: 'Monoclonal Antibody (anti-α4 integrin)',
    uses: 'د Multiple Sclerosis او Crohn Disease لپاره.',
    forms: ['Injection'],
    side_effects: 'د PML خطر، د انتاناتو خطر، سرخوږی.',
    warning: 'د PML خطر څارنه مهمه ده.',
  },
  {
    id: '777',
    name: 'Ocrelizumab',
    generic: 'Ocrelizumab',
    category: 'Monoclonal Antibody (anti-CD20)',
    uses: 'د Multiple Sclerosis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '778',
    name: 'Ofatumumab',
    generic: 'Ofatumumab',
    category: 'Monoclonal Antibody (anti-CD20)',
    uses: 'د Multiple Sclerosis او CLL لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '779',
    name: 'Alemtuzumab',
    generic: 'Alemtuzumab',
    category: 'Monoclonal Antibody (anti-CD52)',
    uses: 'د Multiple Sclerosis او CLL لپاره.',
    forms: ['Injection'],
    side_effects: 'د انتاناتو خطر، د autoimmune ناروغیو خطر، د وینې د حجرو کمښت.',
    warning: 'د انتاناتو او د autoimmune څارنه مهمه ده.',
  },
  {
    id: '780',
    name: 'Daclizumab',
    generic: 'Daclizumab',
    category: 'Monoclonal Antibody (anti-CD25)',
    uses: 'د Multiple Sclerosis لپاره (له بازار څخه ایستل شوی).',
    forms: ['Injection'],
    side_effects: 'د ځیګر زهرجنیت، د انتاناتو خطر، د پوستکي خارښت.',
    warning: 'د ځیګر زهرجنیت او د انتاناتو څارنه.',
  },
  {
    id: '781',
    name: 'Abatacept',
    generic: 'Abatacept',
    category: 'Biologic (CTLA-4-Ig)',
    uses: 'د Rheumatoid Arthritis، Psoriatic Arthritis او Juvenile Idiopathic Arthritis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر، سرخوږی.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '782',
    name: 'Anakinra',
    generic: 'Anakinra',
    category: 'Biologic (IL-1 receptor antagonist)',
    uses: 'د Rheumatoid Arthritis او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '783',
    name: 'Canakinumab',
    generic: 'Canakinumab',
    category: 'Monoclonal Antibody (anti-IL-1β)',
    uses: 'د Periodic Fever Syndromes او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '784',
    name: 'Rilonacept',
    generic: 'Rilonacept',
    category: 'Biologic (IL-1 trap)',
    uses: 'د Cryopyrin-Associated Periodic Syndromes لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '785',
    name: 'Tocilizumab',
    generic: 'Tocilizumab',
    category: 'Monoclonal Antibody (anti-IL-6R)',
    uses: 'د Rheumatoid Arthritis، Giant Cell Arteritis او CRS لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر، د ځیګر انزایم لوړوالی.',
    warning: 'د انتاناتو او د ځیګر څارنه مهمه ده.',
  },
  {
    id: '786',
    name: 'Sarilumab',
    generic: 'Sarilumab',
    category: 'Monoclonal Antibody (anti-IL-6R)',
    uses: 'د Rheumatoid Arthritis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر، د وینې د حجرو کمښت.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '787',
    name: 'Siltuximab',
    generic: 'Siltuximab',
    category: 'Monoclonal Antibody (anti-IL-6)',
    uses: 'د Multicentric Castleman Disease لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر، د وینې د حجرو کمښت.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '788',
    name: 'Golimumab',
    generic: 'Golimumab',
    category: 'Monoclonal Antibody (anti-TNF)',
    uses: 'د Rheumatoid Arthritis، Psoriatic Arthritis، Ankylosing Spondylitis او Ulcerative Colitis لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '789',
    name: 'Certolizumab Pegol',
    generic: 'Certolizumab Pegol',
    category: 'Biologic (anti-TNF)',
    uses: 'د Crohn Disease، Rheumatoid Arthritis او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '790',
    name: 'Etanercept',
    generic: 'Etanercept',
    category: 'Biologic (TNF receptor fusion protein)',
    uses: 'د Rheumatoid Arthritis، Psoriasis او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '791',
    name: 'Rituximab (SC)',
    generic: 'Rituximab',
    category: 'Monoclonal Antibody (anti-CD20)',
    uses: 'د NHL، CLL او Rheumatoid Arthritis لپاره.',
    forms: ['Subcutaneous injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د انتاناتو خطر.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '792',
    name: 'Obinutuzumab',
    generic: 'Obinutuzumab',
    category: 'Monoclonal Antibody (anti-CD20)',
    uses: 'د CLL او Follicular Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر، د وینې د حجرو کمښت.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '793',
    name: 'Blinatumomab',
    generic: 'Blinatumomab',
    category: 'Biologic (BiTE)',
    uses: 'د ALL لپاره.',
    forms: ['Injection'],
    side_effects: 'د CRS خطر، د اعصابو عوارض، د انتاناتو خطر.',
    warning: 'د CRS او د اعصابو څارنه مهمه ده.',
  },
  {
    id: '794',
    name: 'Elotuzumab',
    generic: 'Elotuzumab',
    category: 'Monoclonal Antibody (anti-SLAMF7)',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر، ستړیا.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '795',
    name: 'Daratumumab',
    generic: 'Daratumumab',
    category: 'Monoclonal Antibody (anti-CD38)',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر، د وینې د حجرو کمښت.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '796',
    name: 'Isatuximab',
    generic: 'Isatuximab',
    category: 'Monoclonal Antibody (anti-CD38)',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د انتاناتو خطر، د وینې د حجرو کمښت.',
    warning: 'د انتاناتو څارنه مهمه ده.',
  },
  {
    id: '797',
    name: 'Dinutuximab',
    generic: 'Dinutuximab',
    category: 'Monoclonal Antibody (anti-GD2)',
    uses: 'د Neuroblastoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د درد، د الرژي غبرګونونه، د وینې فشار ټیټوالی.',
    warning: 'د درد او د الرژي څارنه مهمه ده.',
  },
  {
    id: '798',
    name: 'Naxitamab',
    generic: 'Naxitamab',
    category: 'Monoclonal Antibody (anti-GD2)',
    uses: 'د Neuroblastoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د درد، د الرژي غبرګونونه، د وینې فشار ټیټوالی.',
    warning: 'د درد او د الرژي څارنه مهمه ده.',
  },
  {
    id: '799',
    name: 'Margetuximab',
    generic: 'Margetuximab',
    category: 'Monoclonal Antibody (anti-HER2)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د زړه زهرجنیت، ستړیا.',
    warning: 'د زړه څارنه مهمه ده.',
  },
  {
    id: '800',
    name: 'Fam-Trastuzumab Deruxtecan',
    generic: 'Fam-Trastuzumab Deruxtecan',
    category: 'Antibody-Drug Conjugate',
    uses: 'د HER2-positive NSCLC او سینې د سرطان لپاره.',
    forms: ['Injection'],
    side_effects: 'د ILD خطر، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د ILD خطر څارنه مهمه ده.',
  },
];
