// ==================== medicines10.js — لسمه برخه ====================
export const medicines10 = [
  {
    id: '451',
    name: 'Tranylcypromine',
    generic: 'Tranylcypromine',
    category: 'MAOI Antidepressant',
    uses: 'د Depression لپاره چې د نورو درملو سره یې ځواب نه وي ورکړی.',
    forms: ['Tablet'],
    side_effects: 'د وینې فشار لوړوالی، سرخوږی، د خوب ستونزې، د مزاج بدلونونه.',
    warning: 'د خوړو او درملو سره جدي تعاملات لري.',
  },
  {
    id: '452',
    name: 'Phenelzine',
    generic: 'Phenelzine',
    category: 'MAOI Antidepressant',
    uses: 'د Depression لپاره چې د نورو درملو سره یې ځواب نه وي ورکړی.',
    forms: ['Tablet'],
    side_effects: 'د وینې فشار لوړوالی، سرګرداني، د خوب ستونزې.',
    warning: 'د خوړو او درملو سره جدي تعاملات لري.',
  },
  {
    id: '453',
    name: 'Isocarboxazid',
    generic: 'Isocarboxazid',
    category: 'MAOI Antidepressant',
    uses: 'د Depression لپاره چې د نورو درملو سره یې ځواب نه وي ورکړی.',
    forms: ['Tablet'],
    side_effects: 'د وینې فشار لوړوالی، سرګرداني، د خوب ستونزې.',
    warning: 'د خوړو او درملو سره جدي تعاملات لري.',
  },
  {
    id: '454',
    name: 'Selegiline',
    generic: 'Selegiline',
    category: 'MAOI / Dopamine Agent',
    uses: 'د Parkinson disease لپاره.',
    forms: ['Tablet', 'Capsule', 'Transdermal patch'],
    side_effects: 'زړه بدوالی، سرګرداني، د خوب ستونزې.',
    warning: 'د خوړو او درملو سره جدي تعاملات لري.',
  },
  {
    id: '455',
    name: 'Rasagiline',
    generic: 'Rasagiline',
    category: 'MAOI / Dopamine Agent',
    uses: 'د Parkinson disease لپاره.',
    forms: ['Tablet'],
    side_effects: 'سرخوږی، زړه بدوالی، د بندونو درد.',
    warning: 'د خوړو او درملو سره تعاملات لري.',
  },
  {
    id: '456',
    name: 'Safinamide',
    generic: 'Safinamide',
    category: 'MAOI / Dopamine Agent',
    uses: 'د Parkinson disease لپاره.',
    forms: ['Tablet'],
    side_effects: 'د خوب ستونزې، زړه بدوالی، د وینې فشار لوړوالی.',
    warning: 'د خوړو او درملو سره تعاملات لري.',
  },
  {
    id: '457',
    name: 'Entacapone',
    generic: 'Entacapone',
    category: 'COMT Inhibitor',
    uses: 'د Parkinson disease لپاره (د Levodopa سره یوځای).',
    forms: ['Tablet'],
    side_effects: 'اسهال، د ادرار رنګ بدلون، د عضلاتو ناروغي.',
    warning: 'د Levodopa سره یوځای استعمالېږي.',
  },
  {
    id: '458',
    name: 'Tolcapone',
    generic: 'Tolcapone',
    category: 'COMT Inhibitor',
    uses: 'د Parkinson disease لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د ځیګر زهرجنیت، د وینې فشار ټیټوالی.',
    warning: 'د ځیګر زهرجنیت خطر.',
  },
  {
    id: '459',
    name: 'Trihexyphenidyl',
    generic: 'Trihexyphenidyl',
    category: 'Anticholinergic',
    uses: 'د Parkinson disease او ځینو نورو حالتونو لپاره.',
    forms: ['Tablet', 'Oral solution'],
    side_effects: 'د خولې وچوالی، قبضیت، د لید تیاره والی.',
    warning: 'په ګرمه هوا کې د بدن د تودوخې تنظیم اغېزمنولی شي.',
  },
  {
    id: '460',
    name: 'Benztropine',
    generic: 'Benztropine',
    category: 'Anticholinergic',
    uses: 'د Parkinson disease او د ځینو درملو د عوارضو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د خولې وچوالی، قبضیت، د لید تیاره والی.',
    warning: 'په ګرمه هوا کې احتیاط مهم دی.',
  },
  {
    id: '461',
    name: 'Procyclidine',
    generic: 'Procyclidine',
    category: 'Anticholinergic',
    uses: 'د Parkinson disease لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د خولې وچوالی، قبضیت، د لید تیاره والی.',
    warning: 'په ګرمه هوا کې احتیاط مهم دی.',
  },
  {
    id: '462',
    name: 'Orphenadrine',
    generic: 'Orphenadrine',
    category: 'Anticholinergic / Muscle Relaxant',
    uses: 'د Parkinson disease او د عضلاتو د Spasm لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبولي، د خولې وچوالی، سرګرداني.',
    warning: 'په ګرمه هوا کې احتیاط مهم دی.',
  },
  {
    id: '463',
    name: 'Chlorzoxazone',
    generic: 'Chlorzoxazone',
    category: 'Muscle Relaxant',
    uses: 'د عضلاتو د Spasm او درد لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبولي، سرګرداني، د معدې ناروغي.',
    warning: 'د ځیګر زهرجنیت نادره خو جدي.',
  },
  {
    id: '464',
    name: 'Metaxalone',
    generic: 'Metaxalone',
    category: 'Muscle Relaxant',
    uses: 'د عضلاتو د Spasm لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبولي، سرګرداني، زړه بدوالی.',
    warning: 'د ځیګر او د وینې څارنه مهمه ده.',
  },
  {
    id: '465',
    name: 'Carisoprodol',
    generic: 'Carisoprodol',
    category: 'Muscle Relaxant',
    uses: 'د عضلاتو د Spasm لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبولي، سرګرداني، د روږديتوب خطر.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '466',
    name: 'Methocarbamol',
    generic: 'Methocarbamol',
    category: 'Muscle Relaxant',
    uses: 'د عضلاتو د Spasm لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبولي، سرګرداني، زړه بدوالی.',
    warning: 'د موټر چلولو پر مهال احتیاط.',
  },
  {
    id: '467',
    name: 'Dantrolene',
    generic: 'Dantrolene',
    category: 'Muscle Relaxant',
    uses: 'د Malignant hyperthermia او ځینو عضلاتي Spasm حالتونو لپاره.',
    forms: ['Capsule', 'Injection'],
    side_effects: 'د عضلاتو ضعف، د ځیګر زهرجنیت، زړه بدوالی.',
    warning: 'د ځیګر زهرجنیت خطر.',
  },
  {
    id: '468',
    name: 'Quinine Sulfate',
    generic: 'Quinine Sulfate',
    category: 'Antimalarial / Muscle Agent',
    uses: 'د Malaria او ځینو عضلاتي Spasm حالتونو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د غوږونو زنګ، سرخوږی، د وینې د شکرې ټیټوالی.',
    warning: 'د جدي عوارضو له امله باید یوازې د طبي مسلکي له لارښوونې سره استعمال شي.',
  },
  {
    id: '469',
    name: 'Mexiletine',
    generic: 'Mexiletine',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ریتم په ځینو اختلالاتو کې.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، سرګرداني، د لړزې احساس.',
    warning: 'د زړه د ریتم څارنه مهمه ده.',
  },
  {
    id: '470',
    name: 'Propafenone',
    generic: 'Propafenone',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ریتم په ځینو اختلالاتو کې.',
    forms: ['Tablet'],
    side_effects: 'سرګرداني، د خولې وچوالی، د زړه د ریتم بدلونونه.',
    warning: 'د زړه د ریتم څارنه مهمه ده.',
  },
  {
    id: '471',
    name: 'Disopyramide',
    generic: 'Disopyramide',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ریتم په ځینو اختلالاتو کې.',
    forms: ['Capsule'],
    side_effects: 'د خولې وچوالی، قبضیت، د ادرار ستونزه.',
    warning: 'د زړه د ریتم څارنه مهمه ده.',
  },
  {
    id: '472',
    name: 'Procainamide',
    generic: 'Procainamide',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ریتم په ځینو اختلالاتو کې.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وینې د حجرو کمښت، د وینې فشار ټیټوالی، د پوستکي خارښت.',
    warning: 'د وینې د حجرو څارنه مهمه ده.',
  },
  {
    id: '473',
    name: 'Bretylium',
    generic: 'Bretylium',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ریتم په ځینو جدی حالتونو کې.',
    forms: ['Injection'],
    side_effects: 'د وینې فشار ټیټوالی، زړه بدوالی، سرګرداني.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '474',
    name: 'Adenosine',
    generic: 'Adenosine',
    category: 'Antiarrhythmic',
    uses: 'د paroxysmal supraventricular tachycardia (PSVT) درملنه.',
    forms: ['Injection'],
    side_effects: 'د سینې تنګی، د مخ سوروالی، د تنفس ستونزه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '475',
    name: 'Magnesium Sulfate (Cardiac)',
    generic: 'Magnesium Sulfate',
    category: 'Antiarrhythmic / Electrolyte',
    uses: 'د Torsades de Pointes او د Magnesium د کموالي لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې فشار ټیټوالی، د عضلاتو ضعف، د تنفس ټیټوالی.',
    warning: 'یوځای د طبي څارنې لاندې.',
  },
  {
    id: '476',
    name: 'Tocainide',
    generic: 'Tocainide',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ریتم په ځینو اختلالاتو کې.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، سرګرداني، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه مهمه ده.',
  },
  {
    id: '477',
    name: 'Moracizine',
    generic: 'Moracizine',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ریتم په ځینو اختلالاتو کې.',
    forms: ['Tablet'],
    side_effects: 'سرګرداني، زړه بدوالی، د زړه د ریتم بدلونونه.',
    warning: 'د زړه د ریتم څارنه مهمه ده.',
  },
  {
    id: '478',
    name: 'Amiodarone (Oral)',
    generic: 'Amiodarone',
    category: 'Antiarrhythmic',
    uses: 'د زړه د ځینو بې نظم ضربانونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د thyroid، د سترګو او د پوستکي عوارض.',
    warning: 'د طبي څارنې او مناسبې معاینې اړتیا لري.',
  },
  {
    id: '479',
    name: 'Dronedarone',
    generic: 'Dronedarone',
    category: 'Antiarrhythmic',
    uses: 'د atrial fibrillation درملنه.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، اسهال، د زړه د ریتم بدلونونه.',
    warning: 'د زړه د ریتم څارنه مهمه ده.',
  },
  {
    id: '480',
    name: 'Vernakalant (Oral)',
    generic: 'Vernakalant',
    category: 'Antiarrhythmic',
    uses: 'د atrial fibrillation درملنه.',
    forms: ['Oral tablet'],
    side_effects: 'د خوند بدلون، پرنجی، د پوستکي ټکول.',
    warning: 'د وینې ټیټ فشار او د زړه ورووالی.',
  },
  {
    id: '481',
    name: 'Bosutinib',
    generic: 'Bosutinib',
    category: 'Antineoplastic (BCR-ABL inhibitor)',
    uses: 'د Chronic Myeloid Leukemia (CML) لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر زهرجنیت او د اوبو ساتنه.',
  },
  {
    id: '482',
    name: 'Dasatinib',
    generic: 'Dasatinib',
    category: 'Antineoplastic (BCR-ABL inhibitor)',
    uses: 'د Chronic Myeloid Leukemia (CML) او ALL لپاره.',
    forms: ['Tablet'],
    side_effects: 'د اوبو ساتنه، د وینې د حجرو کمښت، د سږو ستونزې.',
    warning: 'د pulmonary arterial hypertension خطر.',
  },
  {
    id: '483',
    name: 'Nilotinib',
    generic: 'Nilotinib',
    category: 'Antineoplastic (BCR-ABL inhibitor)',
    uses: 'د Chronic Myeloid Leukemia (CML) لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې د شکرې لوړوالی، د QT اوږدوالی، د پوستکي خارښت.',
    warning: 'د QT اوږدوالی او د وینې د شکرې څارنه.',
  },
  {
    id: '484',
    name: 'Ponatinib',
    generic: 'Ponatinib',
    category: 'Antineoplastic (BCR-ABL inhibitor)',
    uses: 'د Chronic Myeloid Leukemia (CML) او ALL لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د لخته خطر، د وینې فشار لوړوالی، د پوستکي خارښت.',
    warning: 'د وینې د لخته خطر او د فشار څارنه.',
  },
  {
    id: '485',
    name: 'Imatinib',
    generic: 'Imatinib Mesylate',
    category: 'Antineoplastic (BCR-ABL inhibitor)',
    uses: 'د CML، GIST او ځینو نورو سرطانونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د اوبو ساتنه، د معدې ناروغي، د عضلاتو درد.',
    warning: 'د اوبو ساتنه او د ځیګر څارنه مهمه ده.',
  },
  {
    id: '486',
    name: 'Ruxolitinib',
    generic: 'Ruxolitinib',
    category: 'Antineoplastic (JAK inhibitor)',
    uses: 'د Myelofibrosis او Polycythemia Vera لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د حجرو کمښت، د انتاناتو خطر، د وزن زیاتوالی.',
    warning: 'د وینې د حجرو څارنه مهمه ده.',
  },
  {
    id: '487',
    name: 'Fedratinib',
    generic: 'Fedratinib',
    category: 'Antineoplastic (JAK inhibitor)',
    uses: 'د Myelofibrosis لپاره.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، اسهال، د وینې د حجرو کمښت.',
    warning: 'د Wernicke encephalopathy خطر.',
  },
  {
    id: '488',
    name: 'Ibrutinib',
    generic: 'Ibrutinib',
    category: 'Antineoplastic (BTK inhibitor)',
    uses: 'د CLL، Mantle Cell Lymphoma او نورو لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'اسهال، د وینې بهیدنه، د انتاناتو خطر.',
    warning: 'د وینې بهیدنه او د زړه د ریتم څارنه.',
  },
  {
    id: '489',
    name: 'Acalabrutinib',
    generic: 'Acalabrutinib',
    category: 'Antineoplastic (BTK inhibitor)',
    uses: 'د CLL او Mantle Cell Lymphoma لپاره.',
    forms: ['Capsule'],
    side_effects: 'سرخوږی، اسهال، د وینې بهیدنه.',
    warning: 'د وینې بهیدنه او د انتاناتو څارنه.',
  },
  {
    id: '490',
    name: 'Zanubrutinib',
    generic: 'Zanubrutinib',
    category: 'Antineoplastic (BTK inhibitor)',
    uses: 'د Mantle Cell Lymphoma او نورو لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې د حجرو کمښت، د وینې بهیدنه، د انتاناتو خطر.',
    warning: 'د وینې بهیدنه او د انتاناتو څارنه.',
  },
  {
    id: '491',
    name: 'Venetoclax',
    generic: 'Venetoclax',
    category: 'Antineoplastic (BCL-2 inhibitor)',
    uses: 'د CLL او AML لپاره.',
    forms: ['Tablet'],
    side_effects: 'د tumor lysis syndrome خطر، د وینې د حجرو کمښت.',
    warning: 'د tumor lysis syndrome خطر.',
  },
  {
    id: '492',
    name: 'Idelalisib',
    generic: 'Idelalisib',
    category: 'Antineoplastic (PI3K inhibitor)',
    uses: 'د CLL او Follicular Lymphoma لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د ځیګر زهرجنیت، د انتاناتو خطر.',
    warning: 'د ځیګر زهرجنیت او د انتاناتو څارنه.',
  },
  {
    id: '493',
    name: 'Copanlisib',
    generic: 'Copanlisib',
    category: 'Antineoplastic (PI3K inhibitor)',
    uses: 'د Follicular Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د شکرې لوړوالی، د وینې فشار لوړوالی، اسهال.',
    warning: 'د وینې د شکرې او فشار څارنه مهمه ده.',
  },
  {
    id: '494',
    name: 'Duvelisib',
    generic: 'Duvelisib',
    category: 'Antineoplastic (PI3K inhibitor)',
    uses: 'د CLL او Follicular Lymphoma لپاره.',
    forms: ['Capsule'],
    side_effects: 'اسهال، د انتاناتو خطر، د وینې د حجرو کمښت.',
    warning: 'د انتاناتو او د ځیګر څارنه.',
  },
  {
    id: '495',
    name: 'Bortezomib',
    generic: 'Bortezomib',
    category: 'Antineoplastic (Proteasome inhibitor)',
    uses: 'د Multiple Myeloma او Mantle Cell Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د اعصابو درد، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د اعصابو درد څارنه مهمه ده.',
  },
  {
    id: '496',
    name: 'Carfilzomib',
    generic: 'Carfilzomib',
    category: 'Antineoplastic (Proteasome inhibitor)',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه ستونزې، د وینې فشار لوړوالی، ستړیا.',
    warning: 'د زړه او د فشار څارنه مهمه ده.',
  },
  {
    id: '497',
    name: 'Ixazomib',
    generic: 'Ixazomib',
    category: 'Antineoplastic (Proteasome inhibitor)',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Capsule'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، د اعصابو درد.',
    warning: 'د وینې د حجرو او د اعصابو څارنه.',
  },
  {
    id: '498',
    name: 'Thalidomide',
    generic: 'Thalidomide',
    category: 'Antineoplastic / Immunomodulator',
    uses: 'د Multiple Myeloma او ځینو نورو حالتونو لپاره.',
    forms: ['Capsule'],
    side_effects: 'خوبولي، د اعصابو درد، د وینې د لخته خطر.',
    warning: 'د جنین زیان؛ امیندوارۍ کې منع دی.',
  },
  {
    id: '499',
    name: 'Lenalidomide',
    generic: 'Lenalidomide',
    category: 'Antineoplastic / Immunomodulator',
    uses: 'د Multiple Myeloma او Myelodysplastic Syndrome لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې د حجرو کمښت، د وینې د لخته خطر، اسهال.',
    warning: 'د جنین زیان؛ امیندوزۍ کې منع دی.',
  },
  {
    id: '500',
    name: 'Pomalidomide',
    generic: 'Pomalidomide',
    category: 'Antineoplastic / Immunomodulator',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې د حجرو کمښت، د وینې د لخته خطر، ستړیا.',
    warning: 'د جنین زیان؛ امیندوارۍ کې منع دی.',
  },
];
