// ==================== medicines14.js — څوارلسمه برخه ====================
export const medicines14 = [
  {
    id: '651',
    name: 'Propofol',
    generic: 'Propofol',
    category: 'Anesthetic',
    uses: 'په روغتون کې د anesthesia او sedation لپاره.',
    forms: ['Intravenous emulsion'],
    side_effects: 'د وینې فشار ټیټوالی، د تنفس ټیټوالی، د انجیکشن ځای درد.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '652',
    name: 'Etomidate',
    generic: 'Etomidate',
    category: 'Anesthetic',
    uses: 'په روغتون کې د anesthesia لپاره.',
    forms: ['Injection'],
    side_effects: 'د adrenal suppression، د انجیکشن ځای درد، زړه بدوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '653',
    name: 'Ketamine',
    generic: 'Ketamine',
    category: 'Anesthetic / Analgesic',
    uses: 'په روغتون کې د anesthesia او د درد لپاره.',
    forms: ['Injection', 'Nasal spray'],
    side_effects: 'د توهماتو احساس، د وینې فشار لوړوالی، د زړه ګړندیتوب.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '654',
    name: 'Thiopental',
    generic: 'Thiopental',
    category: 'Anesthetic',
    uses: 'په روغتون کې د anesthesia لپاره.',
    forms: ['Injection'],
    side_effects: 'د تنفس ټیټوالی، د وینې فشار ټیټوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '655',
    name: 'Methohexital',
    generic: 'Methohexital',
    category: 'Anesthetic',
    uses: 'په روغتون کې د anesthesia لپاره.',
    forms: ['Injection'],
    side_effects: 'د تنفس ټیټوالی، د وینې فشار ټیټوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '656',
    name: 'Succinylcholine',
    generic: 'Succinylcholine',
    category: 'Neuromuscular Blocker',
    uses: 'په روغتون کې د عضلاتو د ارامولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د عضلاتو درد، د پوتاشیم لوړوالی، د زړه ورووالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '657',
    name: 'Rocuronium',
    generic: 'Rocuronium',
    category: 'Neuromuscular Blocker',
    uses: 'په روغتون کې د عضلاتو د ارامولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د عضلاتو ضعف، الرژي، د زړه ګړندیتوب.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '658',
    name: 'Vecuronium',
    generic: 'Vecuronium',
    category: 'Neuromuscular Blocker',
    uses: 'په روغتون کې د عضلاتو د ارامولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د عضلاتو ضعف، د تنفس ټیټوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '659',
    name: 'Atracurium',
    generic: 'Atracurium',
    category: 'Neuromuscular Blocker',
    uses: 'په روغتون کې د عضلاتو د ارامولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د پوستکي خارښت، د وینې فشار ټیټوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '660',
    name: 'Cisatracurium',
    generic: 'Cisatracurium',
    category: 'Neuromuscular Blocker',
    uses: 'په روغتون کې د عضلاتو د ارامولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د پوستکي خارښت، د وینې فشار ټیټوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '661',
    name: 'Pancuronium',
    generic: 'Pancuronium',
    category: 'Neuromuscular Blocker',
    uses: 'په روغتون کې د عضلاتو د ارامولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه ګړندیتوب، د وینې فشار لوړوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '662',
    name: 'Neostigmine',
    generic: 'Neostigmine',
    category: 'Cholinesterase Inhibitor',
    uses: 'په روغتون کې د Neuromuscular blocker د اغیزې د بېرته راګرځولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه ورووالی، د معدې ناروغي، د ادرار زیاتوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '663',
    name: 'Edrophonium',
    generic: 'Edrophonium',
    category: 'Cholinesterase Inhibitor',
    uses: 'په روغتون کې د Myasthenia Gravis تشخیص او د Neuromuscular blocker د اغیزې د بېرته راګرځولو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه ورووالی، د معدې ناروغي، د ادرار زیاتوالی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '664',
    name: 'Pyridostigmine',
    generic: 'Pyridostigmine',
    category: 'Cholinesterase Inhibitor',
    uses: 'د Myasthenia Gravis لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د معدې ناروغي، د ادرار زیاتوالی، د عضلاتو رعشه.',
    warning: 'د دوز تنظیم د متخصص تر څارنې لاندې.',
  },
  {
    id: '665',
    name: 'Physostigmine',
    generic: 'Physostigmine',
    category: 'Cholinesterase Inhibitor',
    uses: 'د Anticholinergic زهرجنیت لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه ورووالی، د معدې ناروغي، د ادرار زیاتوالی.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '666',
    name: 'Sugammadex',
    generic: 'Sugammadex',
    category: 'Neuromuscular Blocker Reversal',
    uses: 'په روغتون کې د Rocuronium او Vecuronium د اغیزې د بېرته راګرځولو لپاره.',
    forms: ['Injection'],
    side_effects: 'الرژي، د زړه ورووالی، د وینې فشار ټیټوالی.',
    warning: 'یوازې د anesthesia متخصص تر څارنې لاندې.',
  },
  {
    id: '667',
    name: 'Nalbuphine',
    generic: 'Nalbuphine',
    category: 'Opioid Analgesic',
    uses: 'د منځني تر شدید درد لپاره.',
    forms: ['Injection'],
    side_effects: 'خوبولي، سرګرداني، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '668',
    name: 'Butorphanol',
    generic: 'Butorphanol',
    category: 'Opioid Analgesic',
    uses: 'د منځني تر شدید درد لپاره.',
    forms: ['Injection', 'Nasal spray'],
    side_effects: 'خوبولي، سرګرداني، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '669',
    name: 'Buprenorphine',
    generic: 'Buprenorphine',
    category: 'Opioid Analgesic',
    uses: 'د Opioid dependence او د درد لپاره.',
    forms: ['Tablet', 'Injection', 'Transdermal patch'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '670',
    name: 'Pentazocine',
    generic: 'Pentazocine',
    category: 'Opioid Analgesic',
    uses: 'د منځني تر شدید درد لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبولي، سرګرداني، زړه بدوالی، د وینې فشار لوړوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '671',
    name: 'Hydrocodone',
    generic: 'Hydrocodone',
    category: 'Opioid Analgesic',
    uses: 'د منځني تر شدید درد لپاره.',
    forms: ['Tablet', 'Oral solution'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '672',
    name: 'Oxycodone',
    generic: 'Oxycodone',
    category: 'Opioid Analgesic',
    uses: 'د منځني تر شدید درد لپاره.',
    forms: ['Tablet', 'Capsule', 'Oral solution'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '673',
    name: 'Hydromorphone',
    generic: 'Hydromorphone',
    category: 'Opioid Analgesic',
    uses: 'د شدید درد لپاره.',
    forms: ['Tablet', 'Injection', 'Oral solution'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '674',
    name: 'Oxymorphone',
    generic: 'Oxymorphone',
    category: 'Opioid Analgesic',
    uses: 'د شدید درد لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '675',
    name: 'Levorphanol',
    generic: 'Levorphanol',
    category: 'Opioid Analgesic',
    uses: 'د شدید درد لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '676',
    name: 'Meperidine',
    generic: 'Meperidine (Pethidine)',
    category: 'Opioid Analgesic',
    uses: 'د منځني تر شدید درد لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'خوبولي، زړه بدوالی، د تنفس ټیټوالی، تشنج.',
    warning: 'د روږديتوب خطر لري؛ د تشنج خطر.',
  },
  {
    id: '677',
    name: 'Tapentadol',
    generic: 'Tapentadol',
    category: 'Opioid Analgesic',
    uses: 'د منځني تر شدید درد لپاره.',
    forms: ['Tablet', 'Oral solution'],
    side_effects: 'خوبولي، سرګرداني، زړه بدوالی، قبضیت.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '678',
    name: 'Dihydrocodeine',
    generic: 'Dihydrocodeine',
    category: 'Opioid Analgesic',
    uses: 'د منځني تر شدید درد لپاره.',
    forms: ['Tablet', 'Oral solution'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '679',
    name: 'Ethylmorphine',
    generic: 'Ethylmorphine',
    category: 'Opioid Analgesic',
    uses: 'د درد او د ټوخي لپاره.',
    forms: ['Tablet', 'Oral solution'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '680',
    name: 'Noscapine',
    generic: 'Noscapine',
    category: 'Antitussive',
    uses: 'د وچ ټوخي لپاره.',
    forms: ['Tablet', 'Syrup'],
    side_effects: 'زړه بدوالی، سرګرداني، خوبولي.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '681',
    name: 'Pholcodine',
    generic: 'Pholcodine',
    category: 'Antitussive',
    uses: 'د وچ ټوخي لپاره.',
    forms: ['Syrup'],
    side_effects: 'خوبولي، زړه بدوالی، سرګرداني.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '682',
    name: 'Benzonatate',
    generic: 'Benzonatate',
    category: 'Antitussive',
    uses: 'د وچ ټوخي لپاره.',
    forms: ['Capsule'],
    side_effects: 'خوبولي، سرګرداني، زړه بدوالی.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '683',
    name: 'Chlophedianol',
    generic: 'Chlophedianol',
    category: 'Antitussive',
    uses: 'د وچ ټوخي لپاره.',
    forms: ['Syrup'],
    side_effects: 'خوبولي، زړه بدوالی، سرګرداني.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '684',
    name: 'Carbetapentane',
    generic: 'Carbetapentane',
    category: 'Antitussive',
    uses: 'د وچ ټوخي لپاره.',
    forms: ['Syrup', 'Tablet'],
    side_effects: 'خوبولي، زړه بدوالی، سرګرداني.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '685',
    name: 'Codeine (Low Dose)',
    generic: 'Codeine',
    category: 'Opioid Analgesic / Antitussive',
    uses: 'د وچ ټوخي او د منځني درد لپاره.',
    forms: ['Tablet', 'Syrup'],
    side_effects: 'خوبولي، قبضیت، زړه بدوالی، د تنفس ټیټوالی.',
    warning: 'د روږديتوب خطر لري.',
  },
  {
    id: '686',
    name: 'Dextromethorphan (Extended Release)',
    generic: 'Dextromethorphan',
    category: 'Antitussive',
    uses: 'د وچ ټوخي لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'خوبولي، سرګرداني، زړه بدوالی.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '687',
    name: 'Guaifenesin (Extended Release)',
    generic: 'Guaifenesin',
    category: 'Expectorant',
    uses: 'د بلغم لرونکي ټوخي لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'زړه بدوالی، سرخوږی، د معدې ناراحتي.',
    warning: 'د دوامدارې یا شدیدې ټوخي لپاره طبي ارزونه مهمه ده.',
  },
  {
    id: '688',
    name: 'Ivy Leaf Extract',
    generic: 'Hedera helix',
    category: 'Herbal Expectorant',
    uses: 'د بلغم لرونکي ټوخي لپاره.',
    forms: ['Syrup'],
    side_effects: 'زړه بدوالی، د معدې ناراحتي، الرژي.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '689',
    name: 'Thyme Extract',
    generic: 'Thymus vulgaris',
    category: 'Herbal Expectorant',
    uses: 'د بلغم لرونکي ټوخي لپاره.',
    forms: ['Syrup'],
    side_effects: 'زړه بدوالی، د معدې ناراحتي، الرژي.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '690',
    name: 'Pelargonium Sidoides',
    generic: 'Pelargonium sidoides',
    category: 'Herbal Antiviral / Expectorant',
    uses: 'د Acute Bronchitis او د تنفسي انتاناتو لپاره.',
    forms: ['Tablet', 'Oral solution'],
    side_effects: 'زړه بدوالی، د معدې ناراحتي، الرژي.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '691',
    name: 'Echinacea',
    generic: 'Echinacea purpurea',
    category: 'Herbal Immunostimulant',
    uses: 'د زکام او د تنفسي انتاناتو د مخنیوي لپاره.',
    forms: ['Tablet', 'Capsule', 'Oral solution'],
    side_effects: 'الرژي، زړه بدوالی، د معدې ناراحتي.',
    warning: 'د autoimmune ناروغیو کې احتیاط.',
  },
  {
    id: '692',
    name: 'Ginseng',
    generic: 'Panax ginseng',
    category: 'Herbal Adaptogen',
    uses: 'د انرژۍ او د فزیکي فعالیت لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د خوب ستونزې، د وینې فشار لوړوالی، زړه بدوالی.',
    warning: 'د وینې د فشار او د شکرې درملو سره تعاملات لري.',
  },
  {
    id: '693',
    name: 'Ginkgo Biloba',
    generic: 'Ginkgo biloba',
    category: 'Herbal',
    uses: 'د حافظې او د وینې د جریان لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'سرخوږی، د وینې بهیدنه، د معدې ناراحتي.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
  {
    id: '694',
    name: 'St. John\'s Wort',
    generic: 'Hypericum perforatum',
    category: 'Herbal Antidepressant',
    uses: 'د لږ او منځني Depression لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د پوستکي حساسیت، د معدې ناراحتي، سرګرداني.',
    warning: 'د ډېرو درملو سره جدي تعاملات لري.',
  },
  {
    id: '695',
    name: 'Valerian Root',
    generic: 'Valeriana officinalis',
    category: 'Herbal Sedative',
    uses: 'د خوب د ستونزو لپاره.',
    forms: ['Tablet', 'Capsule', 'Tea'],
    side_effects: 'خوبولي، سرګرداني، د معدې ناراحتي.',
    warning: 'د sedating درملو سره تعاملات لري.',
  },
  {
    id: '696',
    name: 'Melatonin',
    generic: 'Melatonin',
    category: 'Hormone / Sleep Aid',
    uses: 'د خوب د ستونزو او د Jet Lag لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'خوبولي، سرخوږی، زړه بدوالی.',
    warning: 'د ماشومانو لپاره د روغتیايي مسلکي مشوره مهمه ده.',
  },
  {
    id: '697',
    name: 'Passionflower',
    generic: 'Passiflora incarnata',
    category: 'Herbal Sedative',
    uses: 'د اضطراب او د خوب د ستونزو لپاره.',
    forms: ['Tablet', 'Capsule', 'Tea'],
    side_effects: 'خوبولي، سرګرداني، د معدې ناراحتي.',
    warning: 'د sedating درملو سره تعاملات لري.',
  },
  {
    id: '698',
    name: 'Chamomile',
    generic: 'Matricaria chamomilla',
    category: 'Herbal',
    uses: 'د معدې د ناراحتي او د خوب د ستونزو لپاره.',
    forms: ['Tea', 'Capsule'],
    side_effects: 'الرژي، د معدې ناراحتي.',
    warning: 'د Ragweed الرژي لرونکو کسانو کې احتیاط.',
  },
  {
    id: '699',
    name: 'Peppermint Oil',
    generic: 'Mentha piperita',
    category: 'Herbal',
    uses: 'د IBS او د معدې د ناراحتي لپاره.',
    forms: ['Capsule', 'Oil'],
    side_effects: 'د معدې ناراحتي، سینه سوزش، الرژي.',
    warning: 'د GERD لرونکو کسانو کې احتیاط.',
  },
  {
    id: '700',
    name: 'Turmeric',
    generic: 'Curcuma longa',
    category: 'Herbal Anti-inflammatory',
    uses: 'د التهاب او د بندونو د درد لپاره.',
    forms: ['Capsule', 'Tablet', 'Powder'],
    side_effects: 'د معدې ناراحتي، د وینې بهیدنه، د صفرا تیږې.',
    warning: 'د وینې د لخته ضد درملو سره تعاملات لري.',
  },
];
