// ==================== medicines17.js — اوولسمه برخه ====================
export const medicines17 = [
  {
    id: '801',
    name: 'Lorlatinib',
    generic: 'Lorlatinib',
    category: 'Antineoplastic (ALK inhibitor)',
    uses: 'د ALK-positive NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د کولیسټرول لوړوالی، د پښو پړسوب، د مزاج بدلونونه.',
    warning: 'د CNS غبرګونونه او د کولیسټرول څارنه.',
  },
  {
    id: '802',
    name: 'Entrectinib',
    generic: 'Entrectinib',
    category: 'Antineoplastic (NTRK/ROS1 inhibitor)',
    uses: 'د NTRK-fusion tumors او ROS1-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'ستړیا، د وزن زیاتوالی، د مزاج بدلونونه.',
    warning: 'د CNS اغیزې او د زړه څارنه.',
  },
  {
    id: '803',
    name: 'Larotrectinib',
    generic: 'Larotrectinib',
    category: 'Antineoplastic (NTRK inhibitor)',
    uses: 'د NTRK-fusion tumors لپاره.',
    forms: ['Oral capsule', 'Oral solution'],
    side_effects: 'ستړیا، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر او د CNS څارنه.',
  },
  {
    id: '804',
    name: 'Repotrectinib',
    generic: 'Repotrectinib',
    category: 'Antineoplastic (ROS1/NTRK inhibitor)',
    uses: 'د ROS1-positive NSCLC او NTRK-fusion tumors لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د CNS اغیزې، د عضلاتو درد، ستړیا.',
    warning: 'د CNS اغیزې څارنه.',
  },
  {
    id: '805',
    name: 'Krazati (Adagrasib)',
    generic: 'Adagrasib',
    category: 'Antineoplastic (KRAS inhibitor)',
    uses: 'د KRAS G12C-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی او د ځیګر څارنه.',
  },
  {
    id: '806',
    name: 'Lumakras (Sotorasib)',
    generic: 'Sotorasib',
    category: 'Antineoplastic (KRAS inhibitor)',
    uses: 'د KRAS G12C-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر زهرجنیت څارنه.',
  },
  {
    id: '807',
    name: 'Trodelvy (Sacituzumab Govitecan)',
    generic: 'Sacituzumab Govitecan',
    category: 'Antibody-Drug Conjugate',
    uses: 'د triple-negative سینې د سرطان او bladder cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د اسهال او د وینې د حجرو څارنه.',
  },
  {
    id: '808',
    name: 'Enhertu (Fam-Trastuzumab Deruxtecan)',
    generic: 'Fam-Trastuzumab Deruxtecan',
    category: 'Antibody-Drug Conjugate',
    uses: 'د HER2-positive سینې د سرطان، gastric cancer او NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د ILD خطر، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د ILD خطر څارنه مهمه ده.',
  },
  {
    id: '809',
    name: 'Padcev (Enfortumab Vedotin)',
    generic: 'Enfortumab Vedotin',
    category: 'Antibody-Drug Conjugate',
    uses: 'د Urothelial cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د پوستکي خارښت، د اعصابو درد، ستړیا.',
    warning: 'د پوستکي او د اعصابو څارنه.',
  },
  {
    id: '810',
    name: 'Tivdak (Tisotumab Vedotin)',
    generic: 'Tisotumab Vedotin',
    category: 'Antibody-Drug Conjugate',
    uses: 'د Cervical cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د سترګو ستونزې، د اعصابو درد، د وینې بهیدنه.',
    warning: 'د سترګو او د اعصابو څارنه.',
  },
  {
    id: '811',
    name: 'Blenrep (Belantamab Mafodotin)',
    generic: 'Belantamab Mafodotin',
    category: 'Antibody-Drug Conjugate',
    uses: 'د Multiple Myeloma لپاره.',
    forms: ['Injection'],
    side_effects: 'د سترګو ستونزې، د وینې د حجرو کمښت.',
    warning: 'د سترګو څارنه مهمه ده.',
  },
  {
    id: '812',
    name: 'Zynlonta (Loncastuximab Tesirine)',
    generic: 'Loncastuximab Tesirine',
    category: 'Antibody-Drug Conjugate',
    uses: 'د Large B-cell Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د ځیګر انزایم لوړوالی، ستړیا.',
    warning: 'د ځیګر او د وینې د حجرو څارنه.',
  },
  {
    id: '813',
    name: 'Akalux (Cetuximab Sarotalocan)',
    generic: 'Cetuximab Sarotalocan',
    category: 'Photodynamic Therapy',
    uses: 'د Head and Neck Cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د پوستکي خارښت، د سوزش خطر.',
    warning: 'د لیزرو څارنه مهمه ده.',
  },
  {
    id: '814',
    name: 'Ontak (Denileukin Diftitox)',
    generic: 'Denileukin Diftitox',
    category: 'Biologic (IL-2 fusion toxin)',
    uses: 'د Cutaneous T-cell Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د وینې د حجرو کمښت.',
    warning: 'د انفوزیون غبرګونونه څارنه.',
  },
  {
    id: '815',
    name: 'Yervoy (Ipilimumab)',
    generic: 'Ipilimumab',
    category: 'Monoclonal Antibody (CTLA-4 inhibitor)',
    uses: 'د Melanoma او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '816',
    name: 'Opdivo (Nivolumab)',
    generic: 'Nivolumab',
    category: 'Monoclonal Antibody (PD-1 inhibitor)',
    uses: 'د Melanoma، NSCLC او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '817',
    name: 'Keytruda (Pembrolizumab)',
    generic: 'Pembrolizumab',
    category: 'Monoclonal Antibody (PD-1 inhibitor)',
    uses: 'د Melanoma، NSCLC او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '818',
    name: 'Tecentriq (Atezolizumab)',
    generic: 'Atezolizumab',
    category: 'Monoclonal Antibody (PD-L1 inhibitor)',
    uses: 'د NSCLC، bladder cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '819',
    name: 'Imfinzi (Durvalumab)',
    generic: 'Durvalumab',
    category: 'Monoclonal Antibody (PD-L1 inhibitor)',
    uses: 'د NSCLC او bladder cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '820',
    name: 'Bavencio (Avelumab)',
    generic: 'Avelumab',
    category: 'Monoclonal Antibody (PD-L1 inhibitor)',
    uses: 'د Merkel Cell Carcinoma او bladder cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '821',
    name: 'Libtayo (Cemiplimab)',
    generic: 'Cemiplimab',
    category: 'Monoclonal Antibody (PD-1 inhibitor)',
    uses: 'د Cutaneous Squamous Cell Carcinoma او NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '822',
    name: 'Jemperli (Dostarlimab)',
    generic: 'Dostarlimab',
    category: 'Monoclonal Antibody (PD-1 inhibitor)',
    uses: 'د Endometrial cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د immune-mediated غبرګونونه، ستړیا.',
    warning: 'د immune-mediated غبرګونونه څارنه.',
  },
  {
    id: '823',
    name: 'Retevmo (Selpercatinib)',
    generic: 'Selpercatinib',
    category: 'Antineoplastic (RET inhibitor)',
    uses: 'د RET-fusion NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې فشار لوړوالی، د QT اوږدوالی، ستړیا.',
    warning: 'د فشار او QT څارنه.',
  },
  {
    id: '824',
    name: 'Gavreto (Pralsetinib)',
    generic: 'Pralsetinib',
    category: 'Antineoplastic (RET inhibitor)',
    uses: 'د RET-fusion NSCLC او thyroid cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې فشار لوړوالی، ستړیا، د ځیګر انزایم لوړوالی.',
    warning: 'د فشار او د ځیګر څارنه.',
  },
  {
    id: '825',
    name: 'Tepmetko (Tepotinib)',
    generic: 'Tepotinib',
    category: 'Antineoplastic (MET inhibitor)',
    uses: 'د MET-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر څارنه.',
  },
  {
    id: '826',
    name: 'Tabrecta (Capmatinib)',
    generic: 'Capmatinib',
    category: 'Antineoplastic (MET inhibitor)',
    uses: 'د MET-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پښو پړسوب، زړه بدوالی، ستړیا.',
    warning: 'د ILD خطر او د ځیګر څارنه.',
  },
  {
    id: '827',
    name: 'Exkivity (Mobocertinib)',
    generic: 'Mobocertinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR exon 20 insertion-positive NSCLC لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'اسهال، د پوستکي خارښت، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی څارنه.',
  },
  {
    id: '828',
    name: 'Rybrevant (Amivantamab)',
    generic: 'Amivantamab',
    category: 'Monoclonal Antibody (anti-EGFR/MET)',
    uses: 'د EGFR exon 20 insertion-positive NSCLC لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون غبرګونونه، د پوستکي خارښت، د وینې د لخته خطر.',
    warning: 'د انفوزیون غبرګونونه څارنه.',
  },
  {
    id: '829',
    name: 'Lazcluze (Lazertinib)',
    generic: 'Lazertinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، د وینې د لخته خطر، ستړیا.',
    warning: 'د وینې د لخته څارنه.',
  },
  {
    id: '830',
    name: 'Tagrisso (Osimertinib)',
    generic: 'Osimertinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی څارنه.',
  },
  {
    id: '831',
    name: 'Iressa (Gefitinib)',
    generic: 'Gefitinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، اسهال، د ځیګر انزایم لوړوالی.',
    warning: 'د ILD خطر او د ځیګر څارنه.',
  },
  {
    id: '832',
    name: 'Tarceva (Erlotinib)',
    generic: 'Erlotinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د NSCLC او pancreatic cancer لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د پوستکي خارښت، اسهال، ستړیا.',
    warning: 'د ILD خطر او د ځیګر څارنه.',
  },
  {
    id: '833',
    name: 'Gilotrif (Afatinib)',
    generic: 'Afatinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د خولې زخمونه.',
    warning: 'د اسهال او د پوستکي څارنه.',
  },
  {
    id: '834',
    name: 'Vizimpro (Dacomitinib)',
    generic: 'Dacomitinib',
    category: 'Antineoplastic (EGFR inhibitor)',
    uses: 'د EGFR-mutated NSCLC لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د خولې زخمونه.',
    warning: 'د اسهال او د پوستکي څارنه.',
  },
  {
    id: '835',
    name: 'Nerlynx (Neratinib)',
    generic: 'Neratinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، زړه بدوالی، د ځیګر انزایم لوړوالی.',
    warning: 'د اسهال څارنه مهمه ده.',
  },
  {
    id: '836',
    name: 'Tykerb (Lapatinib)',
    generic: 'Lapatinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د پوستکي خارښت، د زړه د فعالیت بدلون.',
    warning: 'د زړه د فعالیت څارنه.',
  },
  {
    id: '837',
    name: 'Tukysa (Tucatinib)',
    generic: 'Tucatinib',
    category: 'Antineoplastic (HER2 inhibitor)',
    uses: 'د HER2-positive سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د لاسونو او پښو سندروم، د ځیګر انزایم لوړوالی.',
    warning: 'د اسهال او د ځیګر څارنه.',
  },
  {
    id: '838',
    name: 'Ibrance (Palbociclib)',
    generic: 'Palbociclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Oral capsule', 'Oral tablet'],
    side_effects: 'د وینې د حجرو کمښت، ستړیا، زړه بدوالی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '839',
    name: 'Kisqali (Ribociclib)',
    generic: 'Ribociclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د وینې د حجرو کمښت، د QT اوږدوالی، ستړیا.',
    warning: 'د QT اوږدوالی او د وینې د حجرو څارنه.',
  },
  {
    id: '840',
    name: 'Verzenio (Abemaciclib)',
    generic: 'Abemaciclib',
    category: 'Antineoplastic (CDK4/6 inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، ستړیا.',
    warning: 'د اسهال او د وینې د حجرو څارنه.',
  },
  {
    id: '841',
    name: 'Lynparza (Olaparib)',
    generic: 'Olaparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer، سینې د سرطان او prostate cancer لپاره.',
    forms: ['Oral tablet', 'Oral capsule'],
    side_effects: 'زړه بدوالی، ستړیا، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '842',
    name: 'Rubraca (Rucaparib)',
    generic: 'Rucaparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer او prostate cancer لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، ستړیا، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '843',
    name: 'Zejula (Niraparib)',
    generic: 'Niraparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د ovarian cancer لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، ستړیا.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '844',
    name: 'Talzenna (Talazoparib)',
    generic: 'Talazoparib',
    category: 'Antineoplastic (PARP inhibitor)',
    uses: 'د HER2-negative سینې د سرطان لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د وینې د حجرو کمښت، ستړیا، سرخوږی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '845',
    name: 'Idhifa (Enasidenib)',
    generic: 'Enasidenib',
    category: 'Antineoplastic (IDH2 inhibitor)',
    uses: 'د AML لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د differentiation syndrome.',
    warning: 'د differentiation syndrome څارنه.',
  },
  {
    id: '846',
    name: 'Tibsovo (Ivosidenib)',
    generic: 'Ivosidenib',
    category: 'Antineoplastic (IDH1 inhibitor)',
    uses: 'د AML او cholangiocarcinoma لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'زړه بدوالی، اسهال، د differentiation syndrome.',
    warning: 'د differentiation syndrome څارنه.',
  },
  {
    id: '847',
    name: 'Xospata (Gilteritinib)',
    generic: 'Gilteritinib',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-mutated AML لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د وینې د حجرو کمښت، اسهال، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی او د وینې د حجرو څارنه.',
  },
  {
    id: '848',
    name: 'Rydapt (Midostaurin)',
    generic: 'Midostaurin',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-mutated AML او Systemic Mastocytosis لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'زړه بدوالی، د وینې د حجرو کمښت، د QT اوږدوالی.',
    warning: 'د QT اوږدوالی څارنه.',
  },
  {
    id: '849',
    name: 'Vanflyta (Quizartinib)',
    generic: 'Quizartinib',
    category: 'Antineoplastic (FLT3 inhibitor)',
    uses: 'د FLT3-ITD positive AML لپاره.',
    forms: ['Oral tablet'],
    side_effects: 'د QT اوږدوالی، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د QT اوږدوالی څارنه مهمه ده.',
  },
  {
    id: '850',
    name: 'Turalio (Pexidartinib)',
    generic: 'Pexidartinib',
    category: 'Antineoplastic (CSF1R inhibitor)',
    uses: 'د Tenosynovial Giant Cell Tumor لپاره.',
    forms: ['Oral capsule'],
    side_effects: 'د ځیګر زهرجنیت، ستړیا، د پوستکي خارښت.',
    warning: 'د ځیګر زهرجنیت څارنه.',
  },
];
