// ==================== medicines9.js — نهمه برخه ====================
export const medicines9 = [
  {
    id: '401',
    name: 'Diazoxide',
    generic: 'Diazoxide',
    category: 'Antihypertensive / Hyperinsulinism',
    uses: 'د شدید هایپوګلایسیمیا او ځینو فشار حالتونو لپاره.',
    forms: ['Oral suspension', 'Injection'],
    side_effects: 'د وینې د شکرې لوړوالی، د اوبو ساتنه، د وېښتانو زیاتوالی.',
    warning: 'د وینې د شکرې او فشار څارنه مهمه ده.',
  },
  {
    id: '402',
    name: 'Octreotide',
    generic: 'Octreotide',
    category: 'Somatostatin Analog',
    uses: 'د Acromegaly، د کولمو د ځینو حالتونو او د وینې بهیدو لپاره.',
    forms: ['Injection', 'Oral capsule'],
    side_effects: 'د معدې ناروغي، د صفرا تیږې، د وینې د شکرې بدلونونه.',
    warning: 'د زړه د دربې او د شکرې څارنه.',
  },
  {
    id: '403',
    name: 'Cabergoline',
    generic: 'Cabergoline',
    category: 'Dopamine Agonist',
    uses: 'د Hyperprolactinemia او ځینو Parkinson حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، سرګرداني، د زړه د دریځ ستونزې.',
    warning: 'د زړه د دریځ څارنه مهمه ده.',
  },
  {
    id: '404',
    name: 'Bromocriptine',
    generic: 'Bromocriptine',
    category: 'Dopamine Agonist',
    uses: 'د Hyperprolactinemia، Acromegaly او Parkinson لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'زړه بدوالی، سرګرداني، د وینې ټیټ فشار.',
    warning: 'د لومړنیو doses پر مهال سر ګرځېدل.',
  },
  {
    id: '405',
    name: 'Desmopressin Acetate',
    generic: 'Desmopressin',
    category: 'Hormone / Antidiuretic',
    uses: 'د Diabetes insipidus او د وینې د بهیدو ځینو حالتونو لپاره.',
    forms: ['Tablet', 'Nasal spray', 'Injection'],
    side_effects: 'سرخوږی، د اوبو ساتنه، هایپوناترمیا.',
    warning: 'د اوبو د توازن او سودیم څارنه مهمه ده.',
  },
  {
    id: '406',
    name: 'Somatropin',
    generic: 'Somatropin',
    category: 'Growth Hormone',
    uses: 'د Growth Hormone deficiency او ځینو نورو حالتونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د اوبو ساتنه، د شکرې لوړوالی.',
    warning: 'د متخصص تر څارنې لاندې استعمالېږي.',
  },
  {
    id: '407',
    name: 'Pegvisomant',
    generic: 'Pegvisomant',
    category: 'Growth Hormone Receptor Antagonist',
    uses: 'د Acromegaly لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د ځیګر انزایم لوړوالی.',
    warning: 'د ځیګر فعالیت څارنه مهمه ده.',
  },
  {
    id: '408',
    name: 'Teriparatide',
    generic: 'Teriparatide',
    category: 'Parathyroid Hormone Analog',
    uses: 'د Osteoporosis لپاره.',
    forms: ['Injection'],
    side_effects: 'زړه بدوالی، د پښو درد، سرګرداني.',
    warning: 'د اوږدې مودې استعمال محدودیتونه لري.',
  },
  {
    id: '409',
    name: 'Denosumab',
    generic: 'Denosumab',
    category: 'Monoclonal Antibody (RANKL inhibitor)',
    uses: 'د Osteoporosis او ځینو سرطانونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د انتاناتو خطر، د کلسیم کمښت، د عضلاتو درد.',
    warning: 'د کلسیم او انتاناتو څارنه مهمه ده.',
  },
  {
    id: '410',
    name: 'Zoledronic Acid',
    generic: 'Zoledronic Acid',
    category: 'Bisphosphonate',
    uses: 'د Osteoporosis او د سرطان اړوند هډوکو ستونزو لپاره.',
    forms: ['Injection'],
    side_effects: 'د انفوزیون وروسته د انفلوانزا په څیر نښې، د پښتورګو ستونزې.',
    warning: 'د پښتورګو فعالیت او کلسیم څارنه.',
  },
  {
    id: '411',
    name: 'Ibandronic Acid',
    generic: 'Ibandronic Acid',
    category: 'Bisphosphonate',
    uses: 'د Osteoporosis لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د معدې ناروغي، د عضلاتو درد.',
    warning: 'د esophagus خارښت، د معدې زخم.',
  },
  {
    id: '412',
    name: 'Strontium Ranelate',
    generic: 'Strontium Ranelate',
    category: 'Bone Agent',
    uses: 'د Osteoporosis لپاره.',
    forms: ['Powder'],
    side_effects: 'د وینې د لخته خطر، د زړه پیښې، د پوستکي حساسیت.',
    warning: 'د زړه د ستونزو له امله محدودیتونه لري.',
  },
  {
    id: '413',
    name: 'Raloxifene',
    generic: 'Raloxifene',
    category: 'Selective Estrogen Receptor Modulator (SERM)',
    uses: 'د Osteoporosis او د سینې د سرطان د مخنیوي په ځینو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'د وینې د لخته خطر، د پښو پړسوب، د گرمۍ احساس.',
    warning: 'د وینې د لخته خطر له امله د طبي ارزونې اړتیا.',
  },
  {
    id: '414',
    name: 'Tamoxifen',
    generic: 'Tamoxifen',
    category: 'SERM / Antineoplastic',
    uses: 'د سینې د سرطان درملنه او مخنیوی.',
    forms: ['Tablet'],
    side_effects: 'د وینې د لخته خطر، د سترګو ستونزې، د مزاج بدلونونه.',
    warning: 'د سترګو او د وینې د لخته څارنه مهمه ده.',
  },
  {
    id: '415',
    name: 'Anastrozole',
    generic: 'Anastrozole',
    category: 'Aromatase Inhibitor',
    uses: 'د سینې د سرطان درملنه.',
    forms: ['Tablet'],
    side_effects: 'د بندونو درد، د گرمۍ احساس، د مزاج بدلونونه.',
    warning: 'د هډوکو د معدنیاتو څارنه مهمه ده.',
  },
  {
    id: '416',
    name: 'Letrozole',
    generic: 'Letrozole',
    category: 'Aromatase Inhibitor',
    uses: 'د سینې د سرطان درملنه او د ovulation د هڅولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د بندونو درد، د گرمۍ احساس، ستړیا.',
    warning: 'د هډوکو د معدنیاتو څارنه.',
  },
  {
    id: '417',
    name: 'Exemestane',
    generic: 'Exemestane',
    category: 'Aromatase Inhibitor',
    uses: 'د سینې د سرطان درملنه.',
    forms: ['Tablet'],
    side_effects: 'د بندونو درد، ستړیا، د خوب ستونزې.',
    warning: 'د هډوکو د معدنیاتو څارنه مهمه ده.',
  },
  {
    id: '418',
    name: 'Megestrol',
    generic: 'Megestrol Acetate',
    category: 'Progestin / Antineoplastic',
    uses: 'د ځینو سرطانونو او د اشتها د زیاتولو لپاره.',
    forms: ['Tablet', 'Oral suspension'],
    side_effects: 'د وزن زیاتوالی، د وینې د لخته خطر، د اوبو ساتنه.',
    warning: 'د وینې د لخته خطر.',
  },
  {
    id: '419',
    name: 'Medroxyprogesterone Acetate',
    generic: 'Medroxyprogesterone Acetate',
    category: 'Progestin',
    uses: 'د هورموني درملنې او د ځینو سرطانونو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وینې بهیدنه، د وزن زیاتوالی، د مزاج بدلونونه.',
    warning: 'د وینې د لخته خطر.',
  },
  {
    id: '420',
    name: 'Leuprolide',
    generic: 'Leuprolide Acetate',
    category: 'GnRH Agonist',
    uses: 'د Prostate cancer، Endometriosis او ځینو نورو حالتونو لپاره.',
    forms: ['Injection', 'Implant'],
    side_effects: 'د گرمۍ احساس، د مزاج بدلونونه، د هډوکو درد.',
    warning: 'د هورموني بدلونونو څارنه مهمه ده.',
  },
  {
    id: '421',
    name: 'Goserelin',
    generic: 'Goserelin Acetate',
    category: 'GnRH Agonist',
    uses: 'د Prostate cancer او سینې د سرطان لپاره.',
    forms: ['Implant'],
    side_effects: 'د گرمۍ احساس، د مزاج بدلونونه، د هډوکو درد.',
    warning: 'د هورموني بدلونونو څارنه.',
  },
  {
    id: '422',
    name: 'Triptorelin',
    generic: 'Triptorelin',
    category: 'GnRH Agonist',
    uses: 'د Prostate cancer او ځینو نورو حالتونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د گرمۍ احساس، د مزاج بدلونونه، د هډوکو درد.',
    warning: 'د هورموني بدلونونو څارنه مهمه ده.',
  },
  {
    id: '423',
    name: 'Degarelix',
    generic: 'Degarelix',
    category: 'GnRH Antagonist',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، د گرمۍ احساس، ستړیا.',
    warning: 'د هورموني او د انجیکشن ځای څارنه.',
  },
  {
    id: '424',
    name: 'Abiraterone',
    generic: 'Abiraterone Acetate',
    category: 'Antineoplastic (CYP17 inhibitor)',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې لوړ فشار، د پوتاشیم کمښت، د اوبو ساتنه.',
    warning: 'د فشار او پوتاشیم څارنه مهمه ده.',
  },
  {
    id: '425',
    name: 'Enzalutamide',
    generic: 'Enzalutamide',
    category: 'Antineoplastic (Androgen Receptor Antagonist)',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'ستړیا، د وینې لوړ فشار، د تشنج خطر.',
    warning: 'د تشنج خطر او د وینې فشار څارنه.',
  },
  {
    id: '426',
    name: 'Apalutamide',
    generic: 'Apalutamide',
    category: 'Antineoplastic (Androgen Receptor Antagonist)',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Tablet'],
    side_effects: 'ستړیا، د وینې لوړ فشار، د پوستکي خارښت.',
    warning: 'د تشنج خطر او د فشار څارنه.',
  },
  {
    id: '427',
    name: 'Darolutamide',
    generic: 'Darolutamide',
    category: 'Antineoplastic (Androgen Receptor Antagonist)',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Tablet'],
    side_effects: 'ستړیا، د بندونو درد، د وینې لوړ فشار.',
    warning: 'د فشار او د ځیګر څارنه.',
  },
  {
    id: '428',
    name: 'Bicalutamide',
    generic: 'Bicalutamide',
    category: 'Antineoplastic (Androgen Receptor Antagonist)',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Tablet'],
    side_effects: 'د سینې پړسوب، د گرمۍ احساس، ستړیا.',
    warning: 'د ځیګر فعالیت څارنه مهمه ده.',
  },
  {
    id: '429',
    name: 'Flutamide',
    generic: 'Flutamide',
    category: 'Antineoplastic (Androgen Receptor Antagonist)',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Tablet', 'Capsule'],
    side_effects: 'د ځیګر زهرجنیت، د معدې ناروغي، د سینې پړسوب.',
    warning: 'د ځیګر زهرجنیت خطر.',
  },
  {
    id: '430',
    name: 'Nilutamide',
    generic: 'Nilutamide',
    category: 'Antineoplastic (Androgen Receptor Antagonist)',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Tablet'],
    side_effects: 'د لید ستونزې، د الکول سره غبرګون، د ځیګر ستونزې.',
    warning: 'د ځیګر او د لید څارنه.',
  },
  {
    id: '431',
    name: 'Mitotane',
    generic: 'Mitotane',
    category: 'Antineoplastic (Adrenal Cytotoxic)',
    uses: 'د Adrenal cortical carcinoma لپاره.',
    forms: ['Tablet'],
    side_effects: 'زړه بدوالی، اسهال، د CNS اغیزې.',
    warning: 'د adrenal function څارنه مهمه ده.',
  },
  {
    id: '432',
    name: 'Ketoconazole (High Dose)',
    generic: 'Ketoconazole',
    category: 'Antifungal / Endocrine',
    uses: 'د Cushing syndrome په ځینو حالتونو کې.',
    forms: ['Tablet'],
    side_effects: 'د ځیګر زهرجنیت، د معدې ناروغي، د هورموني بدلونونو.',
    warning: 'د ځیګر زهرجنیت خطر.',
  },
  {
    id: '433',
    name: 'Metyrapone',
    generic: 'Metyrapone',
    category: 'Endocrine Diagnostic / Therapeutic',
    uses: 'د Cushing syndrome تشخیص او درملنه.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، سرګرداني، د پوستکي خارښت.',
    warning: 'د adrenal function څارنه مهمه ده.',
  },
  {
    id: '434',
    name: 'Aminoglutethimide',
    generic: 'Aminoglutethimide',
    category: 'Endocrine / Antineoplastic',
    uses: 'د Cushing syndrome او د سینې د سرطان لپاره.',
    forms: ['Tablet'],
    side_effects: 'خوبولي، د پوستکي خارښت، د معدې ناروغي.',
    warning: 'د هورموني بدلونونو څارنه.',
  },
  {
    id: '435',
    name: 'Danazol',
    generic: 'Danazol',
    category: 'Hormonal Agent',
    uses: 'د Endometriosis او ځینو نورو حالتونو لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وزن زیاتوالی، د مزاج بدلونونه، د پوستکي خارښت.',
    warning: 'د هورموني بدلونونو څارنه.',
  },
  {
    id: '436',
    name: 'Nafarelin',
    generic: 'Nafarelin',
    category: 'GnRH Agonist',
    uses: 'د Endometriosis او ځینو نورو حالتونو لپاره.',
    forms: ['Nasal spray'],
    side_effects: 'د گرمۍ احساس، د مزاج بدلونونه، د پوزې irritation.',
    warning: 'د هورموني بدلونونو څارنه.',
  },
  {
    id: '437',
    name: 'Histrelin',
    generic: 'Histrelin',
    category: 'GnRH Agonist',
    uses: 'د Prostate cancer او ځینو نورو حالتونو لپاره.',
    forms: ['Implant'],
    side_effects: 'د گرمۍ احساس، د مزاج بدلونونه، د هډوکو درد.',
    warning: 'د هورموني بدلونونو څارنه.',
  },
  {
    id: '438',
    name: 'Cetrorelix',
    generic: 'Cetrorelix',
    category: 'GnRH Antagonist',
    uses: 'د ovulation د کنټرول لپاره د fertility درملنې په پروګرامونو کې.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی، د معدې ناروغي.',
    warning: 'د fertility متخصص تر څارنې لاندې.',
  },
  {
    id: '439',
    name: 'Ganirelix',
    generic: 'Ganirelix',
    category: 'GnRH Antagonist',
    uses: 'د ovulation د کنټرول لپاره د fertility درملنې په پروګرامونو کې.',
    forms: ['Injection'],
    side_effects: 'د انجیکشن ځای غبرګونونه، سرخوږی، د معدې ناروغي.',
    warning: 'د fertility متخصص تر څارنې لاندې.',
  },
  {
    id: '440',
    name: 'Urofollitropin',
    generic: 'Urofollitropin',
    category: 'Gonadotropin',
    uses: 'د fertility درملنې لپاره.',
    forms: ['Injection'],
    side_effects: 'د ovulation ډېر ځله، د اوبو ساتنه، د انجیکشن ځای غبرګونونه.',
    warning: 'د fertility متخصص تر څارنې لاندې.',
  },
  {
    id: '441',
    name: 'Follitropin Alfa',
    generic: 'Follitropin Alfa',
    category: 'Gonadotropin',
    uses: 'د fertility درملنې لپاره.',
    forms: ['Injection'],
    side_effects: 'د ovulation ډېر ځله، د اوبو ساتنه، د انجیکشن ځای غبرګونونه.',
    warning: 'د fertility متخصص تر څارنې لاندې.',
  },
  {
    id: '442',
    name: 'Follitropin Beta',
    generic: 'Follitropin Beta',
    category: 'Gonadotropin',
    uses: 'د fertility درملنې لپاره.',
    forms: ['Injection'],
    side_effects: 'د ovulation ډېر ځله، د اوبو ساتنه، د انجیکشن ځای غبرګونونه.',
    warning: 'د fertility متخصص تر څارنې لاندې.',
  },
  {
    id: '443',
    name: 'Menotropins',
    generic: 'Menotropins',
    category: 'Gonadotropin',
    uses: 'د fertility درملنې لپاره.',
    forms: ['Injection'],
    side_effects: 'د ovulation ډېر ځله، د اوبو ساتنه، د انجیکشن ځای غبرګونونه.',
    warning: 'د fertility متخصص تر څارنې لاندې.',
  },
  {
    id: '444',
    name: 'Chorionic Gonadotropin',
    generic: 'Chorionic Gonadotropin (hCG)',
    category: 'Gonadotropin',
    uses: 'د fertility درملنې او د testosterone د کموالي لپاره.',
    forms: ['Injection'],
    side_effects: 'د ovulation ډېر ځله، د اوبو ساتنه، د انجیکشن ځای غبرګونونه.',
    warning: 'د متخصص تر څارنې لاندې.',
  },
  {
    id: '445',
    name: 'Clomiphene',
    generic: 'Clomiphene Citrate',
    category: 'Ovulation Inducer',
    uses: 'د ovulation د هڅولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د گرمۍ احساس، د مزاج بدلونونه، د لید ستونزې.',
    warning: 'د متخصص تر څارنې لاندې.',
  },
  {
    id: '446',
    name: 'Mifepristone',
    generic: 'Mifepristone',
    category: 'Antiprogestin',
    uses: 'د امیندوارۍ د ختمولو او ځینو نورو حالتونو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې بهیدنه، د معدې cramp، زړه بدوالی.',
    warning: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: '447',
    name: 'Misoprostol',
    generic: 'Misoprostol',
    category: 'Prostaglandin Analog',
    uses: 'د معدې د زخم د مخنیوي او د امیندوارۍ د ختمولو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د معدې cramp، اسهال، د وینې بهیدنه.',
    warning: 'د امیندوارۍ په وخت کې د طبي لارښوونې پرته مه کاروئ.',
  },
  {
    id: '447b',
    name: 'Dinoprostone',
    generic: 'Dinoprostone',
    category: 'Prostaglandin',
    uses: 'د زیږون د هڅولو لپاره.',
    forms: ['Gel', 'Insert'],
    side_effects: 'د رحم contractions، زړه بدوالی، د وینې فشار بدلونونه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '448',
    name: 'Carboprost',
    generic: 'Carboprost Tromethamine',
    category: 'Prostaglandin',
    uses: 'د وینې د بهیدو د کنټرول لپاره د زیږون وروسته.',
    forms: ['Injection'],
    side_effects: 'د معدې ناروغي، اسهال، د وینې فشار بدلونونه.',
    warning: 'یوازې د روغتون په څارنه کې.',
  },
  {
    id: '449',
    name: 'Methylergonovine',
    generic: 'Methylergonovine',
    category: 'Ergot Alkaloid',
    uses: 'د وینې د بهیدو د کنټرول لپاره د زیږون وروسته.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وینې فشار لوړوالی، زړه بدوالی، سرخوږی.',
    warning: 'د وینې فشار څارنه مهمه ده.',
  },
  {
    id: '450',
    name: 'Ergonovine',
    generic: 'Ergonovine',
    category: 'Ergot Alkaloid',
    uses: 'د وینې د بهیدو د کنټرول لپاره د زیږون وروسته.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وینې فشار لوړوالی، زړه بدوالی، سرخوږی.',
    warning: 'د وینې فشار څارنه مهمه ده.',
  },
];
