// ==================== medicines11.js — یوولسمه برخه ====================
export const medicines11 = [
  {
    id: '501',
    name: 'Chlorambucil',
    generic: 'Chlorambucil',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د Chronic Lymphocytic Leukemia (CLL) او ځینو نورو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د حجرو کمښت، د انتاناتو خطر، زړه بدوالی.',
    warning: 'د وینې د حجرو منظم څارنه اړینه ده.',
  },
  {
    id: '502',
    name: 'Cyclophosphamide',
    generic: 'Cyclophosphamide',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د ځینو سرطانونو او Autoimmune ناروغیو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وینې د حجرو کمښت، د وینې بهیدنه، د مثانې ستونزې.',
    warning: 'د اوبو ډېر مصرف او د مثانې څارنه مهمه ده.',
  },
  {
    id: '503',
    name: 'Ifosfamide',
    generic: 'Ifosfamide',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د ځینو سرطانونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د مثانې ستونزې، د اعصابو عوارض.',
    warning: 'د Mesna سره یوځای کارول کېږي.',
  },
  {
    id: '504',
    name: 'Melphalan',
    generic: 'Melphalan',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د Multiple Myeloma او ځینو نورو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د معدې ناروغي.',
    warning: 'د وینې د حجرو څارنه مهمه ده.',
  },
  {
    id: '505',
    name: 'Busulfan',
    generic: 'Busulfan',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د CML او د stem cell transplant دمخه.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وینې د حجرو کمښت، د سږو ستونزې، د ځیګر زهرجنیت.',
    warning: 'د وینې د حجرو او د سږو څارنه.',
  },
  {
    id: '506',
    name: 'Carmustine',
    generic: 'Carmustine',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د brain tumors، lymphoma او ځینو نورو لپاره.',
    forms: ['Injection', 'Implant'],
    side_effects: 'د وینې د حجرو کمښت، د سږو ستونزې، زړه بدوالی.',
    warning: 'د وینې د حجرو او د سږو څارنه.',
  },
  {
    id: '507',
    name: 'Lomustine',
    generic: 'Lomustine',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د brain tumors او lymphoma لپاره.',
    forms: ['Capsule'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د ځیګر ستونزې.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '508',
    name: 'Streptozocin',
    generic: 'Streptozocin',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د pancreatic islet cell cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د پښتورګو زهرجنیت، زړه بدوالی، د وینې د شکرې بدلونونه.',
    warning: 'د پښتورګو او د شکرې څارنه.',
  },
  {
    id: '509',
    name: 'Dacarbazine',
    generic: 'Dacarbazine',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د melanoma او Hodgkin lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'زړه بدوالی، د وینې د حجرو کمښت، د انفلوانزا په څیر نښې.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '510',
    name: 'Temozolomide',
    generic: 'Temozolomide',
    category: 'Antineoplastic (Alkylating Agent)',
    uses: 'د brain tumors لپاره.',
    forms: ['Capsule', 'Injection'],
    side_effects: 'زړه بدوالی، د وینې د حجرو کمښت، سرخوږی.',
    warning: 'د وینې د حجرو څارنه مهمه ده.',
  },
  {
    id: '511',
    name: 'Altretamine',
    generic: 'Altretamine',
    category: 'Antineoplastic',
    uses: 'د ovarian cancer لپاره.',
    forms: ['Capsule'],
    side_effects: 'زړه بدوالی، د وینې د حجرو کمښت، د اعصابو عوارض.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '512',
    name: 'Mercaptopurine',
    generic: 'Mercaptopurine',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د ALL، CML او ځینو نورو لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د حجرو کمښت، د ځیګر زهرجنیت، زړه بدوالی.',
    warning: 'د وینې د حجرو او د ځیګر څارنه.',
  },
  {
    id: '513',
    name: 'Thioguanine',
    generic: 'Thioguanine',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د AML او ALL لپاره.',
    forms: ['Tablet'],
    side_effects: 'د وینې د حجرو کمښت، د ځیګر زهرجنیت، زړه بدوالی.',
    warning: 'د وینې د حجرو او د ځیګر څارنه.',
  },
  {
    id: '514',
    name: 'Cladribine',
    generic: 'Cladribine',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د Hairy Cell Leukemia او Multiple Sclerosis لپاره.',
    forms: ['Injection', 'Tablet'],
    side_effects: 'د وینې د حجرو کمښت، د انتاناتو خطر، ستړیا.',
    warning: 'د وینې د حجرو څارنه مهمه ده.',
  },
  {
    id: '515',
    name: 'Fludarabine',
    generic: 'Fludarabine',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د CLL او ځینو نورو لپاره.',
    forms: ['Tablet', 'Injection'],
    side_effects: 'د وینې د حجرو کمښت، د انتاناتو خطر، د اعصابو عوارض.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '516',
    name: 'Pentostatin',
    generic: 'Pentostatin',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د Hairy Cell Leukemia لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د پوستکي خارښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '517',
    name: 'Nelarabine',
    generic: 'Nelarabine',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د T-cell ALL او T-cell Lymphoblastic Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د اعصابو عوارض، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د اعصابو څارنه مهمه ده.',
  },
  {
    id: '518',
    name: 'Capecitabine',
    generic: 'Capecitabine',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د colorectal cancer او سینې د سرطان لپاره.',
    forms: ['Tablet'],
    side_effects: 'اسهال، د لاسونو او پښو سندروم، د وینې د حجرو کمښت.',
    warning: 'د لاسونو او پښو څارنه مهمه ده.',
  },
  {
    id: '519',
    name: 'Cytarabine',
    generic: 'Cytarabine',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د AML، ALL او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د سترګو ستونزې.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '520',
    name: 'Gemcitabine',
    generic: 'Gemcitabine',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د pancreatic cancer، lung cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د انفلوانزا په څیر نښې، اسهال.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '521',
    name: 'Fluorouracil (5-FU)',
    generic: 'Fluorouracil',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د colorectal cancer، سینې د سرطان او نورو لپاره.',
    forms: ['Injection', 'Topical'],
    side_effects: 'زړه بدوالی، اسهال، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '522',
    name: 'Hydroxyurea',
    generic: 'Hydroxyurea',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د CML، Sickle Cell Disease او ځینو نورو لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د پوستکي خارښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '523',
    name: 'Methotrexate (High Dose)',
    generic: 'Methotrexate',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د ځینو سرطانونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د ځیګر زهرجنیت، د پښتورګو ستونزې.',
    warning: 'د Leucovorin سره یوځای کارول کېږي.',
  },
  {
    id: '524',
    name: 'Pemetrexed',
    generic: 'Pemetrexed',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د mesothelioma او lung cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، ستړیا، د پوستکي خارښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '525',
    name: 'Pralatrexate',
    generic: 'Pralatrexate',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د Peripheral T-cell Lymphoma لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د خولې زخمونه، ستړیا.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '526',
    name: 'Raltitrexed',
    generic: 'Raltitrexed',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د colorectal cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، اسهال، ستړیا.',
    warning: 'د وینې د حجرو او د پښتورګو څارنه.',
  },
  {
    id: '527',
    name: 'Doxorubicin',
    generic: 'Doxorubicin',
    category: 'Antineoplastic (Anthracycline)',
    uses: 'د ډېرو سرطانونو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه زهرجنیت، د وینې د حجرو کمښت، د خولې زخمونه.',
    warning: 'د زړه زهرجنیت څارنه مهمه ده.',
  },
  {
    id: '528',
    name: 'Daunorubicin',
    generic: 'Daunorubicin',
    category: 'Antineoplastic (Anthracycline)',
    uses: 'د AML او ALL لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه زهرجنیت، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د زړه زهرجنیت څارنه مهمه ده.',
  },
  {
    id: '529',
    name: 'Epirubicin',
    generic: 'Epirubicin',
    category: 'Antineoplastic (Anthracycline)',
    uses: 'د سینې د سرطان، gastric cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه زهرجنیت، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د زړه زهرجنیت څارنه.',
  },
  {
    id: '530',
    name: 'Idarubicin',
    generic: 'Idarubicin',
    category: 'Antineoplastic (Anthracycline)',
    uses: 'د AML لپاره.',
    forms: ['Capsule', 'Injection'],
    side_effects: 'د زړه زهرجنیت، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د زړه زهرجنیت څارنه.',
  },
  {
    id: '531',
    name: 'Mitoxantrone',
    generic: 'Mitoxantrone',
    category: 'Antineoplastic (Anthracenedione)',
    uses: 'د Prostate cancer، Multiple Sclerosis او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د زړه زهرجنیت، د وینې د حجرو کمښت، د وینې د ادرار رنګ بدلون.',
    warning: 'د زړه زهرجنیت څارنه.',
  },
  {
    id: '532',
    name: 'Mitomycin',
    generic: 'Mitomycin',
    category: 'Antineoplastic (Antibiotic)',
    uses: 'د gastric cancer، bladder cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د پښتورګو ستونزې، د پوستکي خارښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '533',
    name: 'Bleomycin',
    generic: 'Bleomycin',
    category: 'Antineoplastic (Antibiotic)',
    uses: 'د Hodgkin lymphoma، testicular cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د سږو فایبروسس، د پوستکي خارښت، د وینې د حجرو کمښت.',
    warning: 'د سږو فایبروسس څارنه مهمه ده.',
  },
  {
    id: '534',
    name: 'Dactinomycin',
    generic: 'Dactinomycin',
    category: 'Antineoplastic (Antibiotic)',
    uses: 'د Wilms tumor، Rhabdomyosarcoma او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د پوستکي خارښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '535',
    name: 'Mithramycin',
    generic: 'Mithramycin (Plicamycin)',
    category: 'Antineoplastic (Antibiotic)',
    uses: 'د testicular cancer او د کلسیم د لوړوالي لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د وینې بهیدنه، د پښتورګو ستونزې.',
    warning: 'د وینې د حجرو او کلسیم څارنه.',
  },
  {
    id: '536',
    name: 'Irinotecan',
    generic: 'Irinotecan',
    category: 'Antineoplastic (Topoisomerase Inhibitor)',
    uses: 'د colorectal cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'اسهال، د وینې د حجرو کمښت، زړه بدوالی.',
    warning: 'د اسهال او د وینې د حجرو څارنه.',
  },
  {
    id: '537',
    name: 'Topotecan',
    generic: 'Topotecan',
    category: 'Antineoplastic (Topoisomerase Inhibitor)',
    uses: 'د ovarian cancer، lung cancer او نورو لپاره.',
    forms: ['Injection', 'Capsule'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د وینې د حجرو کمښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '538',
    name: 'Etoposide',
    generic: 'Etoposide',
    category: 'Antineoplastic (Topoisomerase Inhibitor)',
    uses: 'د testicular cancer، lung cancer او نورو لپاره.',
    forms: ['Capsule', 'Injection'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د وینې فشار ټیټوالی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '539',
    name: 'Teniposide',
    generic: 'Teniposide',
    category: 'Antineoplastic (Topoisomerase Inhibitor)',
    uses: 'د ALL او ځینو نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د وینې فشار ټیټوالی.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '540',
    name: 'Paclitaxel',
    generic: 'Paclitaxel',
    category: 'Antineoplastic (Taxane)',
    uses: 'د سینې د سرطان، ovarian cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د اعصابو درد، د وینې د حجرو کمښت، د وېښتانو کمښت.',
    warning: 'د اعصابو څارنه مهمه ده.',
  },
  {
    id: '541',
    name: 'Docetaxel',
    generic: 'Docetaxel',
    category: 'Antineoplastic (Taxane)',
    uses: 'د سینې د سرطان، prostate cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د اوبو ساتنه، د اعصابو درد.',
    warning: 'د وینې د حجرو او د اوبو څارنه.',
  },
  {
    id: '542',
    name: 'Cabazitaxel',
    generic: 'Cabazitaxel',
    category: 'Antineoplastic (Taxane)',
    uses: 'د Prostate cancer لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، اسهال، د اعصابو درد.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '543',
    name: 'Vinblastine',
    generic: 'Vinblastine',
    category: 'Antineoplastic (Vinca Alkaloid)',
    uses: 'د Hodgkin lymphoma، testicular cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، د اعصابو درد، قبضیت.',
    warning: 'د اعصابو څارنه مهمه ده.',
  },
  {
    id: '544',
    name: 'Vincristine',
    generic: 'Vincristine',
    category: 'Antineoplastic (Vinca Alkaloid)',
    uses: 'د ALL، lymphoma او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د اعصابو درد، قبضیت، د وېښتانو کمښت.',
    warning: 'د اعصابو څارنه مهمه ده.',
  },
  {
    id: '545',
    name: 'Vinorelbine',
    generic: 'Vinorelbine',
    category: 'Antineoplastic (Vinca Alkaloid)',
    uses: 'د lung cancer او سینې د سرطان لپاره.',
    forms: ['Injection', 'Capsule'],
    side_effects: 'د وینې د حجرو کمښت، د اعصابو درد، ستړیا.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '546',
    name: 'Vindesine',
    generic: 'Vindesine',
    category: 'Antineoplastic (Vinca Alkaloid)',
    uses: 'د ALL، lung cancer او نورو لپاره.',
    forms: ['Injection'],
    side_effects: 'د اعصابو درد، د وینې د حجرو کمښت، د وېښتانو کمښت.',
    warning: 'د اعصابو څارنه.',
  },
  {
    id: '547',
    name: 'Asparaginase (Pegylated)',
    generic: 'Pegaspargase',
    category: 'Antineoplastic Enzyme',
    uses: 'د ALL لپاره.',
    forms: ['Injection'],
    side_effects: 'د hypersensitivity غبرګونونه، pancreatitis، thrombosis.',
    warning: 'د pancreatitis او thrombosis څارنه.',
  },
  {
    id: '548',
    name: 'Hydroxycarbamide',
    generic: 'Hydroxycarbamide (Hydroxyurea)',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د CML او Sickle Cell Disease لپاره.',
    forms: ['Capsule', 'Tablet'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د پوستکي خارښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
  {
    id: '549',
    name: 'Anagrelide',
    generic: 'Anagrelide',
    category: 'Platelet-lowering agent',
    uses: 'د essential thrombocythemia درملنه.',
    forms: ['Oral capsule'],
    side_effects: 'د زړه ګړندیتوب، پرنجی، د سینې درد، اسهال.',
    warning: 'د QT اوږدوالی او ventricular tachycardia.',
  },
  {
    id: '550',
    name: 'Pentostatin',
    generic: 'Pentostatin',
    category: 'Antineoplastic (Antimetabolite)',
    uses: 'د Hairy Cell Leukemia لپاره.',
    forms: ['Injection'],
    side_effects: 'د وینې د حجرو کمښت، زړه بدوالی، د پوستکي خارښت.',
    warning: 'د وینې د حجرو څارنه.',
  },
];
