// ==================== pregnancy_warnings.js ====================
// هغه درمل چې حامله ښځو ته زیان رسوي
// ټول ۱۵۰ درمل

export const pregnancyWarnings = [
  // ==================== 🔴 خورا خطرناک (Category X) ====================
  {
    id: 'p1',
    name: 'Methotrexate',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان، د امیندوارۍ پای، د زیږون نقصونه',
    advice: 'هیڅکله مه استعمالوئ. لږ تر لږه ۶ میاشتې مخکې یې بند کړئ.',
  },
  {
    id: 'p2',
    name: 'Warfarin',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین د وینې بهېدنه، د زیږون نقصونه، د مړینې خطر',
    advice: 'له استعمال څخه ډډه وکړئ. د Heparin بدیل وکاروئ.',
  },
  {
    id: 'p3',
    name: 'Isotretinoin',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان، د زیږون نقصونه',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p4',
    name: 'Thalidomide',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین د غړو زیان، د زیږون نقصونه',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p5',
    name: 'Lenalidomide',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p6',
    name: 'Pomalidomide',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p7',
    name: 'Finasteride',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین د تناسلي غړو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p8',
    name: 'Dutasteride',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین د تناسلي غړو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p9',
    name: 'Misoprostol',
    severity: '🔴 خورا خطرناک',
    effect: 'د رحم contractions، د امیندوارۍ پای',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p10',
    name: 'Mifepristone',
    severity: '🔴 خورا خطرناک',
    effect: 'د امیندوارۍ پای',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p11',
    name: 'Danazol',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین د تناسلي غړو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p12',
    name: 'Ergonovine',
    severity: '🔴 خورا خطرناک',
    effect: 'د رحم contractions',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p13',
    name: 'Methylergonovine',
    severity: '🔴 خورا خطرناک',
    effect: 'د رحم contractions',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p14',
    name: 'Ribavirin',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p15',
    name: 'Tretinoin (Oral)',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p16',
    name: 'Tazarotene',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p17',
    name: 'Bexarotene',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p18',
    name: 'Acitretin',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p19',
    name: 'Mycophenolate Mofetil',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p20',
    name: 'Leflunomide',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p21',
    name: 'Bosentan',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p22',
    name: 'Ambrisentan',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p23',
    name: 'Macitentan',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p24',
    name: 'Riociguat',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p25',
    name: 'Atrasentan',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p26',
    name: 'Vamorolone',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p27',
    name: 'Treosulfan',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p28',
    name: 'Palopegteriparatide',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p29',
    name: 'Diazoxide Choline',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p30',
    name: 'Mirdametinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p31',
    name: 'Vimseltinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p32',
    name: 'Eculizumab',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p33',
    name: 'Fitusiran',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p34',
    name: 'Erlotinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p35',
    name: 'Gefitinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p36',
    name: 'Osimertinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p37',
    name: 'Crizotinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p38',
    name: 'Alectinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p39',
    name: 'Brigatinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p40',
    name: 'Lorlatinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p41',
    name: 'Entrectinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p42',
    name: 'Larotrectinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p43',
    name: 'Selpercatinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p44',
    name: 'Pralsetinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p45',
    name: 'Tepotinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p46',
    name: 'Capmatinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p47',
    name: 'Mobocertinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p48',
    name: 'Amivantamab',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p49',
    name: 'Lazertinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p50',
    name: 'Afatinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p51',
    name: 'Dacomitinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p52',
    name: 'Neratinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p53',
    name: 'Lapatinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p54',
    name: 'Tucatinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p55',
    name: 'Palbociclib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p56',
    name: 'Ribociclib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p57',
    name: 'Abemaciclib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p58',
    name: 'Olaparib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p59',
    name: 'Rucaparib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p60',
    name: 'Niraparib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p61',
    name: 'Talazoparib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p62',
    name: 'Enasidenib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p63',
    name: 'Ivosidenib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p64',
    name: 'Gilteritinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p65',
    name: 'Midostaurin',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p66',
    name: 'Quizartinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p67',
    name: 'Pexidartinib',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p68',
    name: 'Sacituzumab Govitecan',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p69',
    name: 'Fam-Trastuzumab Deruxtecan',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p70',
    name: 'Enfortumab Vedotin',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p71',
    name: 'Tisotumab Vedotin',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p72',
    name: 'Belantamab Mafodotin',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p73',
    name: 'Loncastuximab Tesirine',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p74',
    name: 'Denileukin Diftitox',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p75',
    name: 'Cetuximab Sarotalocan',
    severity: '🔴 خورا خطرناک',
    effect: 'د جنین جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },

  // ==================== 🟠 خطرناک (Category D) ====================
  {
    id: 'p76',
    name: 'Lisinopril',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان، د مړینې خطر',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p77',
    name: 'Enalapril',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p78',
    name: 'Ramipril',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p79',
    name: 'Captopril',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p80',
    name: 'Benazepril',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p81',
    name: 'Perindopril',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p82',
    name: 'Valsartan',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p83',
    name: 'Losartan',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p84',
    name: 'Candesartan',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p85',
    name: 'Irbesartan',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p86',
    name: 'Telmisartan',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p87',
    name: 'Olmesartan',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پښتورګو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p88',
    name: 'Doxycycline',
    severity: '🟠 خطرناک',
    effect: 'د جنین د غاښونو رنګ بدلون، د هډوکو د ودې ستونزې',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p89',
    name: 'Tetracycline',
    severity: '🟠 خطرناک',
    effect: 'د جنین د غاښونو رنګ بدلون، د هډوکو د ودې ستونزې',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p90',
    name: 'Minocycline',
    severity: '🟠 خطرناک',
    effect: 'د جنین د غاښونو رنګ بدلون',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p91',
    name: 'Fluconazole (High Dose)',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زیږون نقصونه',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p92',
    name: 'Carbamazepine',
    severity: '🟠 خطرناک',
    effect: 'د جنین د عصبي سیستم زیان، د زیږون نقصونه',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p93',
    name: 'Phenytoin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زیږون نقصونه',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p94',
    name: 'Valproic Acid',
    severity: '🟠 خطرناک',
    effect: 'د جنین د عصبي سیستم جدي زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p95',
    name: 'Lithium',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زړه زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p96',
    name: 'Phenobarbital',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زیږون نقصونه',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p97',
    name: 'Primidone',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زیږون نقصونه',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p98',
    name: 'Methimazole',
    severity: '🟠 خطرناک',
    effect: 'د جنین د پوستکي زیان، د زیږون نقصونه',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p99',
    name: 'Propylthiouracil',
    severity: '🟠 خطرناک',
    effect: 'د جنین د thyroid زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p100',
    name: 'Radioactive Iodine',
    severity: '🟠 خطرناک',
    effect: 'د جنین د thyroid جدي زیان',
    advice: 'هیڅکله مه استعمالوئ.',
  },
  {
    id: 'p101',
    name: 'Streptomycin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د غوږونو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p102',
    name: 'Kanamycin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د غوږونو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p103',
    name: 'Amikacin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د غوږونو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p104',
    name: 'Chloramphenicol',
    severity: '🟠 خطرناک',
    effect: 'د جنین د وینې د حجرو زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p105',
    name: 'Nitrofurantoin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د وینې د حجرو زیان (د امیندوارۍ په وروستیو میاشتو کې)',
    advice: 'د امیندوارۍ په وروستیو میاشتو کې له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p106',
    name: 'Ciprofloxacin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د بندونو زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p107',
    name: 'Levofloxacin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د بندونو زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p108',
    name: 'Moxifloxacin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د بندونو زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p109',
    name: 'Norfloxacin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د بندونو زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p110',
    name: 'Aspirin (High Dose)',
    severity: '🟠 خطرناک',
    effect: 'د وینې بهېدنه، د زیږون مخکې ستونزې',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p111',
    name: 'Ibuprofen',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زړه ستونزې، د جنین د پښتورګو ستونزې',
    advice: 'له استعمال څخه ډډه وکړئ. د Paracetamol وکاروئ.',
  },
  {
    id: 'p112',
    name: 'Diclofenac',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زړه ستونزې',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p113',
    name: 'Naproxen',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زړه ستونزې',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p114',
    name: 'Ketorolac',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زړه ستونزې',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p115',
    name: 'Meloxicam',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زړه ستونزې',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p116',
    name: 'Celecoxib',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زړه ستونزې',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p117',
    name: 'Prednisolone (High Dose)',
    severity: '🟠 خطرناک',
    effect: 'د جنین د adrenal اغېزه، د زیږون نقصونه',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p118',
    name: 'Dexamethasone',
    severity: '🟠 خطرناک',
    effect: 'د جنین د adrenal اغېزه',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p119',
    name: 'Betamethasone',
    severity: '🟠 خطرناک',
    effect: 'د جنین د adrenal اغېزه',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p120',
    name: 'Spironolactone',
    severity: '🟠 خطرناک',
    effect: 'د جنین د هورموني سیستم اغېزه',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p121',
    name: 'Hydrochlorothiazide',
    severity: '🟠 خطرناک',
    effect: 'د جنین د الکترولایتونو عدم توازن',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p122',
    name: 'Furosemide',
    severity: '🟠 خطرناک',
    effect: 'د جنین د الکترولایتونو عدم توازن',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p123',
    name: 'Sulfasalazine',
    severity: '🟠 خطرناک',
    effect: 'د فولیک اسید کمښت',
    advice: 'د فولیک اسید سره یوځای وکاروئ.',
  },
  {
    id: 'p124',
    name: 'Azathioprine',
    severity: '🟠 خطرناک',
    effect: 'د جنین د معافیتي سیستم زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p125',
    name: 'Cyclosporine',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p126',
    name: 'Tacrolimus',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p127',
    name: 'Rituximab',
    severity: '🟠 خطرناک',
    effect: 'د جنین د معافیتي سیستم اغېزه',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p128',
    name: 'Adalimumab',
    severity: '🟠 خطرناک',
    effect: 'د جنین د معافیتي سیستم اغېزه',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p129',
    name: 'Infliximab',
    severity: '🟠 خطرناک',
    effect: 'د جنین د معافیتي سیستم اغېزه',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p130',
    name: 'Metronidazole (High Dose)',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p131',
    name: 'Griseofulvin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د زیږون نقصونه',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p132',
    name: 'Ketoconazole (Oral)',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p133',
    name: 'Itraconazole',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p134',
    name: 'Voriconazole',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p135',
    name: 'Amphotericin B',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p136',
    name: 'Flucytosine',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p137',
    name: 'Atovaquone',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p138',
    name: 'Pentamidine',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p139',
    name: 'Primaquine',
    severity: '🟠 خطرناک',
    effect: 'د جنین د G6PD زیان',
    advice: 'له استعمال څخه ډډه وکړئ.',
  },
  {
    id: 'p140',
    name: 'Chloroquine (High Dose)',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p141',
    name: 'Hydroxychloroquine',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p142',
    name: 'Mefloquine',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p143',
    name: 'Quinine (High Dose)',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p144',
    name: 'Artemether',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p145',
    name: 'Artesunate',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p146',
    name: 'Dihydroartemisinin',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p147',
    name: 'Dapsone',
    severity: '🟠 خطرناک',
    effect: 'د جنین د وینې د حجرو زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p148',
    name: 'Sulfamethoxazole/Trimethoprim',
    severity: '🟠 خطرناک',
    effect: 'د جنین د فولیک اسید کمښت',
    advice: 'له استعمال څخه ډډه وکړئ (د امیندوارۍ په لومړیو میاشتو کې).',
  },
  {
    id: 'p149',
    name: 'Fosfomycin',
    severity: '🟠 خطرناک',
    effect: 'د جنین زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },
  {
    id: 'p150',
    name: 'Tobramycin',
    severity: '🟠 خطرناک',
    effect: 'د جنین د غوږونو زیان',
    advice: 'یوازې د متخصص تر څارنې لاندې.',
  },

  // ==================== 🟡 احتیاط (Category C) ====================
  {
    id: 'p151',
    name: 'Paracetamol',
    severity: '🟡 احتیاط',
    effect: 'د اوږدې مودې استعمال د جنین زیان',
    advice: 'یوازې د اړتیا په صورت کې او لږ دوز.',
  },
  {
    id: 'p152',
    name: 'Omeprazole',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p153',
    name: 'Pantoprazole',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p154',
    name: 'Metformin',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p155',
    name: 'Insulin',
    severity: '🟡 احتیاط',
    effect: 'د وینې د شکرې بدلونونه',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p156',
    name: 'Salbutamol',
    severity: '🟡 احتیاط',
    effect: 'د جنین د زړه د ضربان بدلون',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p157',
    name: 'Cetirizine',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p158',
    name: 'Loratadine',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p159',
    name: 'Amoxicillin',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p160',
    name: 'Cephalexin',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p161',
    name: 'Azithromycin',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p162',
    name: 'Clarithromycin',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p163',
    name: 'Erythromycin',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p164',
    name: 'Metronidazole',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p165',
    name: 'Fluconazole (Low Dose)',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p166',
    name: 'Acyclovir',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p167',
    name: 'Oseltamivir',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p168',
    name: 'Labetalol',
    severity: '🟡 احتیاط',
    effect: 'د جنین د زړه د ضربان بدلون',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p169',
    name: 'Nifedipine',
    severity: '🟡 احتیاط',
    effect: 'د جنین د زړه د ضربان بدلون',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p170',
    name: 'Methyldopa',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p171',
    name: 'Levothyroxine',
    severity: '🟡 احتیاط',
    effect: 'د thyroid د کموالي د درملنې لپاره اړین',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p172',
    name: 'Heparin',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p173',
    name: 'Enoxaparin',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p174',
    name: 'Insulin Glargine',
    severity: '🟡 احتیاط',
    effect: 'د وینې د شکرې بدلونونه',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p175',
    name: 'Ranitidine',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p176',
    name: 'Famotidine',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p177',
    name: 'Ondansetron',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p178',
    name: 'Metoclopramide',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p179',
    name: 'Domperidone',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p180',
    name: 'Loperamide',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p181',
    name: 'Lactulose',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p182',
    name: 'Bisacodyl',
    severity: '🟡 احتیاط',
    effect: 'د جنین زیان',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p183',
    name: 'Senna',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p184',
    name: 'Glycerol Suppository',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p185',
    name: 'Docusate',
    severity: '🟡 احتیاط',
    effect: 'عموماً خوندي',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p186',
    name: 'Ferrous Sulfate',
    severity: '🟡 احتیاط',
    effect: 'د اوسپنې د کمښت لپاره اړین',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p187',
    name: 'Folic Acid',
    severity: '🟡 احتیاط',
    effect: 'د جنین د عصبي سیستم لپاره اړین',
    advice: 'د امیندوارۍ په پلان کې یې وکاروئ.',
  },
  {
    id: 'p188',
    name: 'Calcium Carbonate',
    severity: '🟡 احتیاط',
    effect: 'د جنین د هډوکو لپاره اړین',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p189',
    name: 'Vitamin D',
    severity: '🟡 احتیاط',
    effect: 'د جنین د هډوکو لپاره اړین',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
  {
    id: 'p190',
    name: 'Vitamin B12',
    severity: '🟡 احتیاط',
    effect: 'د جنین د عصبي سیستم لپاره اړین',
    advice: 'یوازې د ډاکټر تر څارنې لاندې.',
  },
];
